In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
import missingno as msno
import seaborn as sns
import scipy.stats as st
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import xgboost as xg
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, f1_score
from eli5.sklearn import PermutationImportance
from eli5 import show_weights
from sklearn.tree import DecisionTreeClassifier
from bayes_opt import BayesianOptimization

In [2]:
#Загрузим данные из файла.
df = pd.read_excel('/home/rik/Рабочий стол/МИФИ/учеба/мо/curse/data.xlsx', index_col=0)
df.head()

IC50, mM    CC50, mM         SI  MaxAbsEStateIndex  MaxEStateIndex  \
0    6.239374  175.482382  28.125000           5.094096        5.094096   
1    0.771831    5.402819   7.000000           3.961417        3.961417   
2  223.808778  161.142320   0.720000           2.627117        2.627117   
3    1.705624  107.855654  63.235294           5.097360        5.097360   
4  107.131532  139.270991   1.300000           5.150510        5.150510   

   MinAbsEStateIndex  MinEStateIndex       qed        SPS    MolWt  ...  \
0           0.387225        0.387225  0.417362  42.928571  384.652  ...   
1           0.533868        0.533868  0.462473  45.214286  388.684  ...   
2           0.543231        0.543231  0.260923  42.187500  446.808  ...   
3           0.390603        0.390603  0.377846  41.862069  398.679  ...   
4           0.270476        0.270476  0.429038  36.514286  466.713  ...   

   fr_sulfide  fr_sulfonamd  fr_sulfone  fr_term_acetylene  fr_tetrazole  \
0           0             0           0                  0             0   
1           0             0           0                  0             0   
2           0             0           0                  0             0   
3           0             0           0                  0             0   
4           0             0           0                  0             0   

   fr_thiazole  fr_thiocyan  fr_thiophene  fr_unbrch_alkane  fr_urea  
0            0            0             0                 3        0  
1            0            0             0                 3        0  
2            0            0             0                 3        0  
3            0            0             0                 4        0  
4            0            0             0                 0        0  

[5 rows x 213 columns]

In [3]:
print("train.shape = {} rows, {} cols".format(*df.shape))

train.shape = 1001 rows, 213 cols


# Предобработка данных.

In [4]:
def transform(df): 
    discrete_feature = [feature for feature in df.columns if len(df[feature].unique())<25]
    count_discrete_feature = {}
    for i in tqdm(discrete_feature):
        cnt = 0
        for j in df[i]:
            if j != 0:
                cnt += 1
        count_discrete_feature[f'{i}'] = cnt
    count_discrete_feature = pd.Series(count_discrete_feature)
    df = df.drop(columns=count_discrete_feature[count_discrete_feature == 0].index.to_list())
    df = df.dropna()
    feature_del = ['BertzCT', 'Chi0', 'Chi0v', 'Chi1', 'Chi1n', 'Chi1v', 'Chi2v', 'Chi3n', 'Chi3v', 'Chi4n', 'Chi4v',
     'ExactMolWt', 'FpDensityMorgan1', 'FpDensityMorgan3', 'HeavyAtomCount', 'HeavyAtomMolWt', 'Kappa1', 'Kappa2',
     'Kappa3', 'LabuteASA', 'MaxAbsEStateIndex', 'MaxAbsPartialCharge', 'MolMR', 'MolWt', 'NHOHCount', 'NumAromaticCarbocycles',
     'NumHAcceptors', 'NumHeteroatoms', 'NumSaturatedCarbocycles', 'NumValenceElectrons', 'SMR_VSA4', 'SMR_VSA9',
     'SlogP_VSA6', 'TPSA', 'VSA_EState2', 'VSA_EState3', 'VSA_EState6', 'fr_Al_OH_noTert', 'fr_COO', 'fr_COO2',
     'fr_C_O_noCOO', 'fr_Nhpyrrole', 'fr_benzene', 'fr_nitro_arom_nonortho', 'fr_phenol', 'fr_phenol_noOrthoHbond',
    'MinAbsPartialCharge', 'Chi2n']
    df = df.drop(columns=feature_del)
   
    return df
    

In [5]:
df = transform(df)

100%|███████████████████████████████████████| 110/110 [00:00<00:00, 6375.73it/s]


In [6]:
val_median = df['CC50, mM'].median()
df['CC50, mM'] = df['CC50, mM'].apply(lambda x: 0 if x < val_median else 1)
df['CC50, mM'].head()

0    0
1    0
2    0
3    0
4    0
Name: CC50, mM, dtype: int64

## Обучение нескольких моделей, их сравнение. 

In [7]:
target = df['CC50, mM']
data = df.drop(['CC50, mM','IC50, mM','SI'], axis=1)

In [8]:
x_train, x_valid = train_test_split(
    data, train_size=0.8, random_state=1
)
y_train, y_valid = train_test_split(
    target, train_size=0.8, random_state=1
)
print("x_train.shape = {} rows, {} cols".format(*x_train.shape))
print("x_valid.shape = {} rows, {} cols".format(*x_valid.shape))

x_train.shape = 798 rows, 144 cols
x_valid.shape = 200 rows, 144 cols


In [9]:
# Создадим модель дерева решений
tree = DecisionTreeClassifier(random_state=27)
# Создадим модель CatBoost
model = CatBoostClassifier(random_state=27)
# Создадим модель lightgbm
model_LGBM = LGBMClassifier(random_state=27)
# Создадим модель xgboost
xgb_r = xg.XGBClassifier() 
# обучение моделей
tree.fit(x_train, y_train)
model.fit(x_train, y_train, verbose=0)
model_LGBM.fit(x_train, y_train, verbose=0)
xgb_r.fit(x_train, y_train, verbose=0)
# предсказание ответов для тренеровочной выборки
y_pred_tree_train = tree.predict(x_train)
y_pred_сat_Boost_train = model.predict(x_train)
y_pred_LGBM_train = model_LGBM.predict(x_train)
y_pred_xgb_train = xgb_r.predict(x_train)
# предсказание ответов для тестовой выборки
y_pred_tree = tree.predict(x_valid)
y_pred_сat_Boost = model.predict(x_valid)
y_pred_LGBM = model_LGBM.predict(x_valid)
y_pred_xgb = xgb_r.predict(x_valid)

print("Train tree f1_score: ", f1_score(y_train, y_pred_tree_train))
print("Train tree accuracy_score: ", accuracy_score(y_train, y_pred_tree_train))
print("Validation tree f1_score: ", f1_score(y_valid, y_pred_tree))
print("Validation tree accuracy_score: ", accuracy_score(y_valid, y_pred_tree))
print('*' * 50)
print("Train сat_Boost f1_score: ", f1_score(y_train, y_pred_сat_Boost_train))
print("Train сat_Boost accuracy_score: ", accuracy_score(y_train, y_pred_сat_Boost_train))
print("Validation сat_Boost f1_score: ", f1_score(y_valid, y_pred_сat_Boost))
print("Validation сat_Boost accuracy_score: ", accuracy_score(y_valid, y_pred_сat_Boost))
print('*' * 50)
print("Train LGBM f1_score: ", f1_score(y_train, y_pred_LGBM_train))
print("Train LGBM accuracy_score: ", accuracy_score(y_train, y_pred_LGBM_train))
print("Validation LGBM f1_score: ", f1_score(y_valid, y_pred_LGBM))
print("Validation LGBM accuracy_score: ", accuracy_score(y_valid, y_pred_LGBM))
print('*' * 50)
print("Train xgb f1_score: ", f1_score(y_train, y_pred_xgb_train))
print("Train xgb accuracy_score: ", accuracy_score(y_train, y_pred_xgb_train))
print("Validation xgb f1_score: ", f1_score(y_valid, y_pred_xgb))
print("Validation xgb accuracy_score: ", accuracy_score(y_valid, y_pred_xgb))

/usr/local/lib/python3.8/dist-packages/lightgbm/sklearn.py:736: UserWarning: 'verbose' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose' argument is deprecated and will be removed in a future release of LightGBM. "


Train tree f1_score:  0.9698492462311556
Train tree accuracy_score:  0.9699248120300752
Validation tree f1_score:  0.6907216494845362
Validation tree accuracy_score:  0.7
**************************************************
Train сat_Boost f1_score:  0.9486552567237163
Train сat_Boost accuracy_score:  0.9473684210526315
Validation сat_Boost f1_score:  0.7821782178217821
Validation сat_Boost accuracy_score:  0.78
**************************************************
Train LGBM f1_score:  0.9702970297029703
Train LGBM accuracy_score:  0.9699248120300752
Validation LGBM f1_score:  0.75
Validation LGBM accuracy_score:  0.75
**************************************************
Train xgb f1_score:  0.9702970297029703
Train xgb accuracy_score:  0.9699248120300752
Validation xgb f1_score:  0.75
Validation xgb accuracy_score:  0.75


Из приведенных данных выше мы видим хорошее качество моделей, а также переобучение. Наилучшие результаты показали модели сat_Boost, LGBM и XGBClassifier. С ними и продолжим работать.

# Подбор признаков, их анализ и оценка важности.

**CatBoost**

In [10]:
col = x_train.columns.tolist()
estimator_cat_boost = PermutationImportance(
    model, scoring= "f1", random_state=27
)
importance_cat_boost = estimator_cat_boost.fit(x_train, y_train)

In [11]:
show_weights(importance_cat_boost, feature_names=col, top=x_train.shape[1])

Оставим только те признаки которые которые улучшают работу модели. И посмотрим как изменится метрика

In [12]:
feature_cat_boost = ['EState_VSA4','PEOE_VSA6','fr_NH2','MinPartialCharge','EState_VSA3','BalabanJ','MinAbsEStateIndex',
'AvgIpc','BCUT2D_MWLOW','PEOE_VSA10','EState_VSA2','qed','BCUT2D_MRLOW','SlogP_VSA1','SMR_VSA5','BCUT2D_LOGPLOW',
'MolLogP','NumSaturatedHeterocycles','VSA_EState7','VSA_EState5','NumRotatableBonds','fr_C_O','SMR_VSA6','BCUT2D_MRHI',
'EState_VSA5','PEOE_VSA1','BCUT2D_CHGLO','EState_VSA8','EState_VSA7','PEOE_VSA8','EState_VSA10','SlogP_VSA3',
'SlogP_VSA5','VSA_EState8','PEOE_VSA9','VSA_EState1','Chi0n','SMR_VSA10','PEOE_VSA7','fr_unbrch_alkane',
'fr_urea','fr_bicyclic','fr_ether','SlogP_VSA2','SMR_VSA7','fr_aryl_methyl','fr_ester','fr_ketone_Topliss',
'NumAliphaticRings','PEOE_VSA13','MinEStateIndex','MaxEStateIndex','Ipc','EState_VSA6','FractionCSP3','PEOE_VSA3',
'SlogP_VSA4','fr_allylic_oxid','NumAromaticHeterocycles','NumAliphaticCarbocycles','NumAliphaticHeterocycles',
'SlogP_VSA8','BCUT2D_MWHI','HallKierAlpha','SMR_VSA1','PEOE_VSA2','PEOE_VSA12','SMR_VSA3','VSA_EState10',
'fr_alkyl_halide','fr_NH0','VSA_EState4','SPS','fr_sulfide','BCUT2D_LOGPHI','PEOE_VSA11','SlogP_VSA12',
'VSA_EState9','EState_VSA9','BCUT2D_CHGHI','PEOE_VSA4','NOCount','fr_Imine','NumSaturatedRings','fr_morpholine',
'RingCount','fr_Ndealkylation1','fr_para_hydroxylation','fr_piperdine','FpDensityMorgan2','fr_ArN','MaxPartialCharge',
'fr_Ar_OH',]

In [13]:
target = df['CC50, mM']
data_cb = data[feature_cat_boost]

In [14]:
x_train_cb, x_valid_cb = train_test_split(
    data_cb, train_size=0.8, random_state=1
)
y_train_cb, y_valid_cb = train_test_split(
    target, train_size=0.8, random_state=1
)
print("x_train.shape = {} rows, {} cols".format(*x_train_cb.shape))
print("x_valid.shape = {} rows, {} cols".format(*x_valid_cb.shape))

x_train.shape = 798 rows, 93 cols
x_valid.shape = 200 rows, 93 cols


In [15]:
# Создадим модель CatBoost
model = CatBoostClassifier(random_state=27)
# обучение моделей
model.fit(x_train_cb, y_train_cb, verbose=0)
# предсказание ответов для тренеровочной выборки
y_pred_сat_Boost_train = model.predict(x_train_cb)
# предсказание ответов для тестовой выборки
y_pred_сat_Boost = model.predict(x_valid_cb)


print("Train сat_Boost f1_score: ", f1_score(y_train_cb, y_pred_сat_Boost_train))
print("Train сat_Boost accuracy_score: ", accuracy_score(y_train_cb, y_pred_сat_Boost_train))
print("Validation сat_Boost f1_score: ", f1_score(y_valid_cb, y_pred_сat_Boost))
print("Validation сat_Boost accuracy_score: ", accuracy_score(y_valid_cb, y_pred_сat_Boost))


Train сat_Boost f1_score:  0.9509803921568627
Train сat_Boost accuracy_score:  0.949874686716792
Validation сat_Boost f1_score:  0.7821782178217821
Validation сat_Boost accuracy_score:  0.78


Отобрав признаки улучшить метрику не удалось, но удалось уменьшить размерность датасета со 144 признаков до 93.

**LGBM**

In [16]:
col = x_train.columns.tolist()
estimator_LGBM = PermutationImportance(
    model_LGBM, scoring= "f1", random_state=27
)
importance_LGBM = estimator_LGBM.fit(x_train, y_train)


In [17]:
show_weights(importance_LGBM, feature_names=col, top=x_train.shape[1])

Оставим только те признаки которые которые улучшают работу модели. И посмотрим как изменится метрика

In [18]:
feature_LGBM = ['PEOE_VSA6','MolLogP','MinPartialCharge','SMR_VSA7','EState_VSA7','PEOE_VSA7','VSA_EState4',
'PEOE_VSA8','BCUT2D_MWLOW','BCUT2D_MRLOW','fr_NH2','Ipc','NumSaturatedHeterocycles','SMR_VSA5','HallKierAlpha',
'BalabanJ','NumRotatableBonds','SlogP_VSA3','SMR_VSA10','EState_VSA8','EState_VSA2','BCUT2D_MWHI','MinAbsEStateIndex',
'EState_VSA10','EState_VSA6','fr_Ar_OH','FractionCSP3','BCUT2D_MRHI','NumHDonors','BCUT2D_CHGLO','EState_VSA5',
'MaxPartialCharge','MinEStateIndex','EState_VSA3','fr_bicyclic','NumAromaticHeterocycles','Chi0n','fr_Al_OH',
'SlogP_VSA2','PEOE_VSA3','NumSaturatedRings','fr_NH0','fr_sulfide','SlogP_VSA4','SlogP_VSA8','BCUT2D_LOGPHI',
'SMR_VSA1','VSA_EState8','PEOE_VSA1','EState_VSA9','FpDensityMorgan2','PEOE_VSA5','NumAliphaticRings',
'SlogP_VSA7','NumAromaticRings','SlogP_VSA11','PEOE_VSA13','fr_para_hydroxylation','fr_Ar_N','fr_NH1','fr_Ndealkylation2',
'fr_ester','fr_ether','PEOE_VSA12']

In [19]:
target_LGBM = df['CC50, mM']
data_LGBM = data[feature_LGBM]

In [20]:
x_train_LGBM, x_valid_LGBM = train_test_split(
    data_LGBM, train_size=0.8, random_state=1
)
y_train_LGBM, y_valid_LGBM = train_test_split(
    target_LGBM, train_size=0.8, random_state=1
)
print("x_train.shape = {} rows, {} cols".format(*x_train_LGBM.shape))
print("x_valid.shape = {} rows, {} cols".format(*x_valid_LGBM.shape))

x_train.shape = 798 rows, 64 cols
x_valid.shape = 200 rows, 64 cols


In [21]:
model_LGBM = LGBMClassifier(random_state=27)
model_LGBM.fit(x_train_LGBM, y_train_LGBM)
# предсказание ответов для тренеровочной выборки
y_pred_LGBM_train = model_LGBM.predict(x_train_LGBM)
# предсказание ответов для тестовой выборки
y_pred_LGBM = model_LGBM.predict(x_valid_LGBM)

print("Train LGBM f1_score: ", f1_score(y_train_LGBM, y_pred_LGBM_train))
print("Train LGBM accuracy_score: ", accuracy_score(y_train_LGBM, y_pred_LGBM_train))
print("Validation LGBM f1_score: ", f1_score(y_valid_LGBM, y_pred_LGBM))
print("Validation LGBM accuracy_score: ", accuracy_score(y_valid_LGBM, y_pred_LGBM))

Train LGBM f1_score:  0.9702233250620347
Train LGBM accuracy_score:  0.9699248120300752
Validation LGBM f1_score:  0.7722772277227722
Validation LGBM accuracy_score:  0.77


Отобрав признаки мы улучшили метрики для модели LGBMClassifier на вадидации f1_score: 0.77, accuracy_score: 0.77.

**xgboost**

In [22]:
col = x_train.columns.tolist()
estimator_xgb = PermutationImportance(
    xgb_r, scoring= "neg_mean_squared_error", random_state=27
)
importance_xgb = estimator_xgb.fit(x_train, y_train)

In [23]:
show_weights(importance_xgb, feature_names=col, top=x_train.shape[1])

Оставим только те признаки которые которые улучшают работу модели. И посмотрим как изменится метрика

In [24]:
feature_xgb = ['BCUT2D_MWLOW','PEOE_VSA6','BCUT2D_MRLOW','MolLogP','fr_Al_OH','PEOE_VSA7','VSA_EState5','PEOE_VSA3',
'EState_VSA10','EState_VSA2','SMR_VSA5','SMR_VSA6','VSA_EState1','NumRotatableBonds','NumSaturatedHeterocycles',
'VSA_EState4','EState_VSA9','MinAbsEStateIndex','EState_VSA6','VSA_EState7','NOCount','SlogP_VSA3','EState_VSA7',
'PEOE_VSA1','VSA_EState9','fr_bicyclic','NumAliphaticCarbocycles','SMR_VSA7','fr_allylic_oxid','fr_halogen',
'SMR_VSA10','AvgIpc','qed','SPS','fr_Ar_OH','PEOE_VSA2','EState_VSA8','fr_NH2','fr_NH1','EState_VSA5','fr_NH0',
'NumSaturatedRings','fr_amide','EState_VSA3','NumHDonors','SlogP_VSA2','SlogP_VSA11','HallKierAlpha','SlogP_VSA4',
'FractionCSP3','MinEStateIndex',]

In [25]:
target_xgb = df['CC50, mM']
data_xgb = data[feature_xgb]

In [26]:
x_train_xgb, x_valid_xgb = train_test_split(
    data_xgb, train_size=0.8, random_state=1
)
y_train_xgb, y_valid_xgb = train_test_split(
    target_xgb, train_size=0.8, random_state=1
)
print("x_train.shape = {} rows, {} cols".format(*x_train_xgb.shape))
print("x_valid.shape = {} rows, {} cols".format(*x_valid_xgb.shape))

x_train.shape = 798 rows, 51 cols
x_valid.shape = 200 rows, 51 cols


In [27]:
model_xgb = xg.XGBClassifier(random_state=27)
model_xgb.fit(x_train_xgb, y_train_xgb, verbose=100)
y_pred_xgb = model_xgb.predict(x_train_xgb)
y_val_xgb = model_xgb.predict(x_valid_xgb)
print("Train f1_score: ", f1_score(y_train_xgb, y_pred_xgb))
print("Train accuracy_score: ", accuracy_score(y_train_xgb, y_pred_xgb))
print("Validation f1_score: ", f1_score(y_valid_xgb, y_val_xgb))
print("Validation accuracy_score: ", accuracy_score(y_valid_xgb, y_val_xgb))

Train f1_score:  0.9702233250620347
Train accuracy_score:  0.9699248120300752
Validation f1_score:  0.7738693467336683
Validation accuracy_score:  0.775


Отобрав признаки мы улучшили метрики для модели xgboost на вадидации f1_score: 0.77, accuracy_score: 0.78.

# Подбор гиперпараметров

**CatBoost**

In [28]:
def catboost_cv(depth, learning_rate,n_estimators):
    depth = int(depth)
    n_estimators = int(n_estimators)
    model = CatBoostClassifier(
        depth=depth,
        learning_rate=learning_rate,
        n_estimators=n_estimators,
        eval_metric  = 'F1',
        random_seed=27
    )
    model.fit(x_train_cb, y_train_cb, verbose=100)

    return f1_score(y_valid_cb, model.predict(x_valid_cb))

In [29]:
param_space = {
    'depth': (2, 10),             
    'learning_rate': (0.001, 0.3),
    'n_estimators': (50, 2000)
}

bayesian_opt = BayesianOptimization(
    f=catboost_cv, pbounds=param_space, random_state=27)
bayesian_opt.maximize(init_points=5, n_iter=25)
results = pd.DataFrame(bayesian_opt.res)
results.sort_values(by='target', ascending=False, inplace=True)

|   iter    |  target   |   depth   | learni... | n_esti... |
-------------------------------------------------------------
0:	learn: 0.7087277	total: 18.1ms	remaining: 26.9s
100:	learn: 0.9702970	total: 612ms	remaining: 8.38s
200:	learn: 0.9702970	total: 1.17s	remaining: 7.45s
300:	learn: 0.9702970	total: 1.71s	remaining: 6.72s
400:	learn: 0.9701493	total: 2.23s	remaining: 6.03s
500:	learn: 0.9702970	total: 2.72s	remaining: 5.34s
600:	learn: 0.9702970	total: 3.28s	remaining: 4.82s
700:	learn: 0.9702970	total: 3.74s	remaining: 4.17s
800:	learn: 0.9702970	total: 4.2s	remaining: 3.58s
900:	learn: 0.9702970	total: 4.64s	remaining: 3.01s
1000:	learn: 0.9702970	total: 5.11s	remaining: 2.47s
1100:	learn: 0.9704433	total: 5.56s	remaining: 1.94s
1200:	learn: 0.9703704	total: 6.01s	remaining: 1.42s
1300:	learn: 0.9704433	total: 6.45s	remaining: 908ms
1400:	learn: 0.9701493	total: 6.89s	remaining: 408ms
1483:	learn: 0.9702233	total: 7.25s	remaining: 0us
| 1         | 0.7745    | 5.406     | 0.24

1000:	learn: 0.9678218	total: 1.61s	remaining: 1.29s
1100:	learn: 0.9678218	total: 1.84s	remaining: 1.17s
1200:	learn: 0.9702970	total: 2s	remaining: 1.01s
1300:	learn: 0.9702970	total: 2.18s	remaining: 842ms
1400:	learn: 0.9702970	total: 2.32s	remaining: 667ms
1500:	learn: 0.9702970	total: 2.47s	remaining: 498ms
1600:	learn: 0.9702970	total: 2.61s	remaining: 331ms
1700:	learn: 0.9702970	total: 2.76s	remaining: 167ms
1800:	learn: 0.9702970	total: 3.01s	remaining: 5.02ms
1803:	learn: 0.9702970	total: 3.02s	remaining: 0us
| 11        | 0.76      | 2.028     | 0.07283   | 1.804e+03 |
0:	learn: 0.7156489	total: 2.41ms	remaining: 120ms
50:	learn: 0.8627936	total: 81.9ms	remaining: 0us
| 12        | 0.7411    | 2.51      | 0.2802    | 51.34     |
0:	learn: 0.7156489	total: 1.8ms	remaining: 1.16s
100:	learn: 0.9117647	total: 151ms	remaining: 814ms
200:	learn: 0.9557740	total: 303ms	remaining: 669ms
300:	learn: 0.9690977	total: 473ms	remaining: 541ms
400:	learn: 0.9702970	total: 618ms	remainin

500:	learn: 0.9702233	total: 6.8s	remaining: 1.67s
600:	learn: 0.9704433	total: 8.05s	remaining: 308ms
623:	learn: 0.9702970	total: 8.37s	remaining: 0us
| 22        | 0.7562    | 7.137     | 0.2241    | 624.8     |
0:	learn: 0.7087277	total: 7.13ms	remaining: 969ms
100:	learn: 0.9702970	total: 508ms	remaining: 181ms
136:	learn: 0.9704433	total: 706ms	remaining: 0us
| 23        | 0.7451    | 5.513     | 0.2198    | 137.7     |
0:	learn: 0.7005291	total: 4.5ms	remaining: 1.23s
100:	learn: 0.9702970	total: 302ms	remaining: 518ms
200:	learn: 0.9702233	total: 597ms	remaining: 217ms
273:	learn: 0.9702233	total: 838ms	remaining: 0us
| 24        | 0.7822    | 4.104     | 0.2313    | 274.6     |
0:	learn: 0.7206385	total: 35.2ms	remaining: 36.3s
100:	learn: 0.9374233	total: 2.67s	remaining: 24.6s
200:	learn: 0.9640644	total: 5.3s	remaining: 21.9s
300:	learn: 0.9702970	total: 7.95s	remaining: 19.3s
400:	learn: 0.9702970	total: 10.6s	remaining: 16.6s
500:	learn: 0.9702970	total: 13.2s	remaining: 

In [30]:
best_hyperparameters = bayesian_opt.max
best_hyperparameters['params'] = {param: int(value) if param in [
    'depth', 'iterations', 'l2_leaf_reg'] else value for param, value in best_hyperparameters['params'].items()}
print("Best hyperparameters:", best_hyperparameters['params'])
print(f"Best R-squared Score: {best_hyperparameters['target']:.4f}")

Best hyperparameters: {'depth': 7, 'learning_rate': 0.2661536369860892, 'n_estimators': 1723.124788664315}
Best R-squared Score: 0.7864


In [31]:
params = {
    'depth': 7,             
    'learning_rate': 0.2661536369860892, 
    'n_estimators': 1723
}
model = CatBoostClassifier(**params, random_state=27)
model.fit(x_train_cb, y_train_cb, verbose=100)
y_pred_cb = model.predict(x_train_cb)
y_val_cb = model.predict(x_valid_cb)
print("Train сat_Boost f1_score: ", f1_score(y_train_cb, y_pred_cb))
print("Train сat_Boost accuracy_score: ", accuracy_score(y_train_cb, y_pred_cb))
print("Validation сat_Boost f1_score: ", f1_score(y_valid_cb, y_val_cb))
print("Validation сat_Boost accuracy_score: ", accuracy_score(y_valid_cb, y_val_cb))

0:	learn: 0.6282430	total: 19.6ms	remaining: 33.7s
100:	learn: 0.0807359	total: 1.43s	remaining: 23s
200:	learn: 0.0626392	total: 2.76s	remaining: 20.9s
300:	learn: 0.0589864	total: 4.11s	remaining: 19.4s
400:	learn: 0.0573007	total: 5.51s	remaining: 18.2s
500:	learn: 0.0567344	total: 6.92s	remaining: 16.9s
600:	learn: 0.0563437	total: 8.28s	remaining: 15.5s
700:	learn: 0.0560691	total: 9.62s	remaining: 14s
800:	learn: 0.0559058	total: 11s	remaining: 12.6s
900:	learn: 0.0557205	total: 12.3s	remaining: 11.2s
1000:	learn: 0.0555831	total: 13.6s	remaining: 9.84s
1100:	learn: 0.0554654	total: 14.9s	remaining: 8.44s
1200:	learn: 0.0554134	total: 16.3s	remaining: 7.08s
1300:	learn: 0.0553675	total: 17.6s	remaining: 5.72s
1400:	learn: 0.0553318	total: 18.9s	remaining: 4.35s
1500:	learn: 0.0553071	total: 20.5s	remaining: 3.03s
1600:	learn: 0.0552628	total: 21.8s	remaining: 1.66s
1700:	learn: 0.0552347	total: 23.3s	remaining: 301ms
1722:	learn: 0.0552241	total: 23.6s	remaining: 0us
Train сat_Bo

После подбора гиперпараметров мы незначительно улучшили метрики модели CatBoost на вадидации f1_score: 0.786, accuracy_score: 0.78.



**LGBM**

In [32]:
def LGBM_cv(max_depth, learning_rate, n_estimators):
    max_depth = int(max_depth)
    n_estimators = int(n_estimators)
    model = LGBMClassifier(
        max_depth=max_depth,
        learning_rate=learning_rate,
        n_estimators=n_estimators,          
        eval_metric  = 'F1',
        random_seed=27
    )
    model.fit(x_train_LGBM, y_train_LGBM, eval_set = (x_valid_LGBM, y_valid_LGBM))
    return f1_score(y_valid_LGBM, model.predict(x_valid_LGBM))

In [33]:
param_space = {
    'max_depth': (2, 10),            
    'learning_rate': (0.001, 0.3),
    'n_estimators': (50, 2000)
}

bayesian_opt = BayesianOptimization(
    f=LGBM_cv, pbounds=param_space, random_state=27)
bayesian_opt.maximize(init_points=5, n_iter=50)
results = pd.DataFrame(bayesian_opt.res)
results.sort_values(by='target', ascending=False, inplace=True)

|   iter    |  target   | learni... | max_depth | n_esti... |
-------------------------------------------------------------
[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.656695
[2]	valid_0's binary_logloss: 0.623143
[3]	valid_0's binary_logloss: 0.596106
[4]	valid_0's binary_logloss: 0.571459
[5]	valid_0's binary_logloss: 0.557189
[6]	valid_0's binary_logloss: 0.543868
[7]	valid_0's binary_logloss: 0.526205
[8]	valid_0's binary_logloss: 0.51654
[9]	valid_0's binary_logloss: 0.510353
[10]	valid_0's binary_logloss: 0.497961
[11]	valid_0's binary_logloss: 0.491303
[12]	valid_0's binary_logloss: 0.488841
[13]	valid_0's binary_logloss: 0.48929
[14]	valid_0's binary_logloss: 0.488627
[15]	valid_0's binary_logloss: 0.487116
[16]	valid_0's binary_logloss: 0.486606
[17]	valid_0's binary_logloss: 0.488827
[18]	valid_0's binary_logloss: 0.485225
[19]	valid_0's binary_logloss: 0.482083
[20]	valid_0's binary_logloss: 0.476905
[21]	valid_0's binary_logloss: 0.47

[216]	valid_0's binary_logloss: 0.807417
[217]	valid_0's binary_logloss: 0.809377
[218]	valid_0's binary_logloss: 0.8106
[219]	valid_0's binary_logloss: 0.814086
[220]	valid_0's binary_logloss: 0.814744
[221]	valid_0's binary_logloss: 0.819844
[222]	valid_0's binary_logloss: 0.820764
[223]	valid_0's binary_logloss: 0.822251
[224]	valid_0's binary_logloss: 0.822189
[225]	valid_0's binary_logloss: 0.823979
[226]	valid_0's binary_logloss: 0.823354
[227]	valid_0's binary_logloss: 0.82325
[228]	valid_0's binary_logloss: 0.822619
[229]	valid_0's binary_logloss: 0.827286
[230]	valid_0's binary_logloss: 0.828681
[231]	valid_0's binary_logloss: 0.830261
[232]	valid_0's binary_logloss: 0.83203
[233]	valid_0's binary_logloss: 0.83266
[234]	valid_0's binary_logloss: 0.833597
[235]	valid_0's binary_logloss: 0.83394
[236]	valid_0's binary_logloss: 0.834721
[237]	valid_0's binary_logloss: 0.839435
[238]	valid_0's binary_logloss: 0.843106
[239]	valid_0's binary_logloss: 0.844327
[240]	valid_0's binary

[528]	valid_0's binary_logloss: 1.1411
[529]	valid_0's binary_logloss: 1.14158
[530]	valid_0's binary_logloss: 1.14413
[531]	valid_0's binary_logloss: 1.14499
[532]	valid_0's binary_logloss: 1.14537
[533]	valid_0's binary_logloss: 1.14564
[534]	valid_0's binary_logloss: 1.14556
[535]	valid_0's binary_logloss: 1.14663
[536]	valid_0's binary_logloss: 1.14691
[537]	valid_0's binary_logloss: 1.14915
[538]	valid_0's binary_logloss: 1.15135
[539]	valid_0's binary_logloss: 1.15244
[540]	valid_0's binary_logloss: 1.1525
[541]	valid_0's binary_logloss: 1.15276
[542]	valid_0's binary_logloss: 1.15283
[543]	valid_0's binary_logloss: 1.1531
[544]	valid_0's binary_logloss: 1.15298
[545]	valid_0's binary_logloss: 1.15322
[546]	valid_0's binary_logloss: 1.15329
[547]	valid_0's binary_logloss: 1.15477
[548]	valid_0's binary_logloss: 1.15468
[549]	valid_0's binary_logloss: 1.15471
[550]	valid_0's binary_logloss: 1.15441
[551]	valid_0's binary_logloss: 1.15447
[552]	valid_0's binary_logloss: 1.15554
[55

[824]	valid_0's binary_logloss: 1.20888
[825]	valid_0's binary_logloss: 1.20891
[826]	valid_0's binary_logloss: 1.20895
[827]	valid_0's binary_logloss: 1.20892
[828]	valid_0's binary_logloss: 1.20893
[829]	valid_0's binary_logloss: 1.20893
[830]	valid_0's binary_logloss: 1.21033
[831]	valid_0's binary_logloss: 1.21032
[832]	valid_0's binary_logloss: 1.21024
[833]	valid_0's binary_logloss: 1.21028
[834]	valid_0's binary_logloss: 1.21027
[835]	valid_0's binary_logloss: 1.21029
[836]	valid_0's binary_logloss: 1.21032
[837]	valid_0's binary_logloss: 1.21033
[838]	valid_0's binary_logloss: 1.2104
[839]	valid_0's binary_logloss: 1.21041
[840]	valid_0's binary_logloss: 1.21057
[841]	valid_0's binary_logloss: 1.20986
[842]	valid_0's binary_logloss: 1.20985
[843]	valid_0's binary_logloss: 1.20993
[844]	valid_0's binary_logloss: 1.20996
[845]	valid_0's binary_logloss: 1.21051
[846]	valid_0's binary_logloss: 1.21066
[847]	valid_0's binary_logloss: 1.21068
[848]	valid_0's binary_logloss: 1.21072
[

[1169]	valid_0's binary_logloss: 1.23358
[1170]	valid_0's binary_logloss: 1.2336
[1171]	valid_0's binary_logloss: 1.23359
[1172]	valid_0's binary_logloss: 1.23362
[1173]	valid_0's binary_logloss: 1.23369
[1174]	valid_0's binary_logloss: 1.23371
[1175]	valid_0's binary_logloss: 1.2337
[1176]	valid_0's binary_logloss: 1.23374
[1177]	valid_0's binary_logloss: 1.23376
[1178]	valid_0's binary_logloss: 1.23377
[1179]	valid_0's binary_logloss: 1.2338
[1180]	valid_0's binary_logloss: 1.23387
[1181]	valid_0's binary_logloss: 1.23392
[1182]	valid_0's binary_logloss: 1.23406
[1183]	valid_0's binary_logloss: 1.23405
[1184]	valid_0's binary_logloss: 1.23402
[1185]	valid_0's binary_logloss: 1.23405
[1186]	valid_0's binary_logloss: 1.23412
[1187]	valid_0's binary_logloss: 1.2339
[1188]	valid_0's binary_logloss: 1.23392
[1189]	valid_0's binary_logloss: 1.23398
[1190]	valid_0's binary_logloss: 1.23403
[1191]	valid_0's binary_logloss: 1.23699
[1192]	valid_0's binary_logloss: 1.23701
[1193]	valid_0's bin

| 1         | 0.722     | 0.1283    | 8.517     | 1.484e+03 |
[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.628447
[2]	valid_0's binary_logloss: 0.594211
[3]	valid_0's binary_logloss: 0.56891
[4]	valid_0's binary_logloss: 0.545598
[5]	valid_0's binary_logloss: 0.532655
[6]	valid_0's binary_logloss: 0.521232
[7]	valid_0's binary_logloss: 0.506776
[8]	valid_0's binary_logloss: 0.50795
[9]	valid_0's binary_logloss: 0.502741
[10]	valid_0's binary_logloss: 0.494247
[11]	valid_0's binary_logloss: 0.491875
[12]	valid_0's binary_logloss: 0.484158
[13]	valid_0's binary_logloss: 0.4927
[14]	valid_0's binary_logloss: 0.485324
[15]	valid_0's binary_logloss: 0.484239
[16]	valid_0's binary_logloss: 0.487596
[17]	valid_0's binary_logloss: 0.484133
[18]	valid_0's binary_logloss: 0.491356
[19]	valid_0's binary_logloss: 0.489796
[20]	valid_0's binary_logloss: 0.49172
[21]	valid_0's binary_logloss: 0.484254
[22]	valid_0's binary_logloss: 0.483449
[23]	valid_0's binar

[222]	valid_0's binary_logloss: 0.874695
[223]	valid_0's binary_logloss: 0.874994
[224]	valid_0's binary_logloss: 0.875043
[225]	valid_0's binary_logloss: 0.877015
[226]	valid_0's binary_logloss: 0.878236
[227]	valid_0's binary_logloss: 0.881028
[228]	valid_0's binary_logloss: 0.880623
[229]	valid_0's binary_logloss: 0.884587
[230]	valid_0's binary_logloss: 0.88654
[231]	valid_0's binary_logloss: 0.888423
[232]	valid_0's binary_logloss: 0.891156
[233]	valid_0's binary_logloss: 0.89045
[234]	valid_0's binary_logloss: 0.891651
[235]	valid_0's binary_logloss: 0.891468
[236]	valid_0's binary_logloss: 0.891246
[237]	valid_0's binary_logloss: 0.893636
[238]	valid_0's binary_logloss: 0.896768
[239]	valid_0's binary_logloss: 0.893386
[240]	valid_0's binary_logloss: 0.894278
[241]	valid_0's binary_logloss: 0.894846
[242]	valid_0's binary_logloss: 0.894977
[243]	valid_0's binary_logloss: 0.896916
[244]	valid_0's binary_logloss: 0.900986
[245]	valid_0's binary_logloss: 0.905154
[246]	valid_0's bi

[480]	valid_0's binary_logloss: 1.15846
[481]	valid_0's binary_logloss: 1.16356
[482]	valid_0's binary_logloss: 1.16409
[483]	valid_0's binary_logloss: 1.16446
[484]	valid_0's binary_logloss: 1.16457
[485]	valid_0's binary_logloss: 1.16568
[486]	valid_0's binary_logloss: 1.16579
[487]	valid_0's binary_logloss: 1.16566
[488]	valid_0's binary_logloss: 1.16623
[489]	valid_0's binary_logloss: 1.16605
[490]	valid_0's binary_logloss: 1.16842
[491]	valid_0's binary_logloss: 1.16887
[492]	valid_0's binary_logloss: 1.16897
[493]	valid_0's binary_logloss: 1.16923
[494]	valid_0's binary_logloss: 1.16925
[495]	valid_0's binary_logloss: 1.16836
[496]	valid_0's binary_logloss: 1.16752
[497]	valid_0's binary_logloss: 1.16774
[498]	valid_0's binary_logloss: 1.16745
[499]	valid_0's binary_logloss: 1.16845
[500]	valid_0's binary_logloss: 1.16862
[501]	valid_0's binary_logloss: 1.16895
[502]	valid_0's binary_logloss: 1.16836
[503]	valid_0's binary_logloss: 1.16841
[504]	valid_0's binary_logloss: 1.16843


[755]	valid_0's binary_logloss: 1.21549
[756]	valid_0's binary_logloss: 1.21544
[757]	valid_0's binary_logloss: 1.21557
[758]	valid_0's binary_logloss: 1.21567
[759]	valid_0's binary_logloss: 1.21572
[760]	valid_0's binary_logloss: 1.21576
[761]	valid_0's binary_logloss: 1.21576
[762]	valid_0's binary_logloss: 1.21576
[763]	valid_0's binary_logloss: 1.2158
[764]	valid_0's binary_logloss: 1.21571
[765]	valid_0's binary_logloss: 1.21565
[766]	valid_0's binary_logloss: 1.2157
[767]	valid_0's binary_logloss: 1.21565
[768]	valid_0's binary_logloss: 1.2156
[769]	valid_0's binary_logloss: 1.21574
[770]	valid_0's binary_logloss: 1.2158
[771]	valid_0's binary_logloss: 1.21594
[772]	valid_0's binary_logloss: 1.21601
[773]	valid_0's binary_logloss: 1.21617
[774]	valid_0's binary_logloss: 1.21619
[775]	valid_0's binary_logloss: 1.21614
[776]	valid_0's binary_logloss: 1.21606
[777]	valid_0's binary_logloss: 1.21601
[778]	valid_0's binary_logloss: 1.21601
[779]	valid_0's binary_logloss: 1.21788
[780

[1027]	valid_0's binary_logloss: 1.25371
[1028]	valid_0's binary_logloss: 1.25384
[1029]	valid_0's binary_logloss: 1.25388
[1030]	valid_0's binary_logloss: 1.25392
[1031]	valid_0's binary_logloss: 1.2539
[1032]	valid_0's binary_logloss: 1.25389
[1033]	valid_0's binary_logloss: 1.25396
[1034]	valid_0's binary_logloss: 1.25402
[1035]	valid_0's binary_logloss: 1.25411
[1036]	valid_0's binary_logloss: 1.25417
[1037]	valid_0's binary_logloss: 1.254
[1038]	valid_0's binary_logloss: 1.25408
[1039]	valid_0's binary_logloss: 1.25405
[1040]	valid_0's binary_logloss: 1.25406
[1041]	valid_0's binary_logloss: 1.25411
[1042]	valid_0's binary_logloss: 1.25414
[1043]	valid_0's binary_logloss: 1.25416
[1044]	valid_0's binary_logloss: 1.25423
[1045]	valid_0's binary_logloss: 1.25416
[1046]	valid_0's binary_logloss: 1.25414
[1047]	valid_0's binary_logloss: 1.25415
[1048]	valid_0's binary_logloss: 1.25406
[1049]	valid_0's binary_logloss: 1.25417
[1050]	valid_0's binary_logloss: 1.25419
[1051]	valid_0's bi

[1280]	valid_0's binary_logloss: 1.26422
[1281]	valid_0's binary_logloss: 1.2642
[1282]	valid_0's binary_logloss: 1.26416
[1283]	valid_0's binary_logloss: 1.26422
[1284]	valid_0's binary_logloss: 1.26432
[1285]	valid_0's binary_logloss: 1.26436
[1286]	valid_0's binary_logloss: 1.26444
[1287]	valid_0's binary_logloss: 1.26448
[1288]	valid_0's binary_logloss: 1.26457
[1289]	valid_0's binary_logloss: 1.26454
[1290]	valid_0's binary_logloss: 1.26453
[1291]	valid_0's binary_logloss: 1.26447
[1292]	valid_0's binary_logloss: 1.26448
[1293]	valid_0's binary_logloss: 1.26459
[1294]	valid_0's binary_logloss: 1.26458
[1295]	valid_0's binary_logloss: 1.26475
[1296]	valid_0's binary_logloss: 1.26473
[1297]	valid_0's binary_logloss: 1.26483
[1298]	valid_0's binary_logloss: 1.26486
[1299]	valid_0's binary_logloss: 1.26488
[1300]	valid_0's binary_logloss: 1.26495
[1301]	valid_0's binary_logloss: 1.26506
[1302]	valid_0's binary_logloss: 1.26511
[1303]	valid_0's binary_logloss: 1.26514
[1304]	valid_0's 

[1558]	valid_0's binary_logloss: 1.28959
[1559]	valid_0's binary_logloss: 1.2896
[1560]	valid_0's binary_logloss: 1.28965
[1561]	valid_0's binary_logloss: 1.28974
[1562]	valid_0's binary_logloss: 1.28979
[1563]	valid_0's binary_logloss: 1.28988
[1564]	valid_0's binary_logloss: 1.28987
[1565]	valid_0's binary_logloss: 1.28976
[1566]	valid_0's binary_logloss: 1.2898
[1567]	valid_0's binary_logloss: 1.2898
[1568]	valid_0's binary_logloss: 1.28979
[1569]	valid_0's binary_logloss: 1.28985
[1570]	valid_0's binary_logloss: 1.29276
[1571]	valid_0's binary_logloss: 1.29276
[1572]	valid_0's binary_logloss: 1.29276
[1573]	valid_0's binary_logloss: 1.29283
[1574]	valid_0's binary_logloss: 1.29284
[1575]	valid_0's binary_logloss: 1.29281
[1576]	valid_0's binary_logloss: 1.29281
[1577]	valid_0's binary_logloss: 1.29289
[1578]	valid_0's binary_logloss: 1.29292
[1579]	valid_0's binary_logloss: 1.29302
[1580]	valid_0's binary_logloss: 1.293
[1581]	valid_0's binary_logloss: 1.29305
[1582]	valid_0's bina

[1813]	valid_0's binary_logloss: 1.30203
[1814]	valid_0's binary_logloss: 1.30203
[1815]	valid_0's binary_logloss: 1.30203
[1816]	valid_0's binary_logloss: 1.30194
[1817]	valid_0's binary_logloss: 1.30199
[1818]	valid_0's binary_logloss: 1.30204
[1819]	valid_0's binary_logloss: 1.30202
[1820]	valid_0's binary_logloss: 1.30201
[1821]	valid_0's binary_logloss: 1.30203
[1822]	valid_0's binary_logloss: 1.30561
[1823]	valid_0's binary_logloss: 1.30562
[1824]	valid_0's binary_logloss: 1.30561
[1825]	valid_0's binary_logloss: 1.30567
[1826]	valid_0's binary_logloss: 1.30569
[1827]	valid_0's binary_logloss: 1.30568
[1828]	valid_0's binary_logloss: 1.30571
[1829]	valid_0's binary_logloss: 1.30573
[1830]	valid_0's binary_logloss: 1.30571
[1831]	valid_0's binary_logloss: 1.30576
[1832]	valid_0's binary_logloss: 1.30572
[1833]	valid_0's binary_logloss: 1.30583
[1834]	valid_0's binary_logloss: 1.30581
[1835]	valid_0's binary_logloss: 1.30584
[1836]	valid_0's binary_logloss: 1.30591
[1837]	valid_0's

[60]	valid_0's binary_logloss: 0.498046
[61]	valid_0's binary_logloss: 0.497241
[62]	valid_0's binary_logloss: 0.497571
[63]	valid_0's binary_logloss: 0.497643
[64]	valid_0's binary_logloss: 0.497097
[65]	valid_0's binary_logloss: 0.496639
[66]	valid_0's binary_logloss: 0.494723
[67]	valid_0's binary_logloss: 0.494691
[68]	valid_0's binary_logloss: 0.496814
[69]	valid_0's binary_logloss: 0.498211
[70]	valid_0's binary_logloss: 0.497963
[71]	valid_0's binary_logloss: 0.497703
[72]	valid_0's binary_logloss: 0.499434
[73]	valid_0's binary_logloss: 0.498864
[74]	valid_0's binary_logloss: 0.500031
[75]	valid_0's binary_logloss: 0.498805
[76]	valid_0's binary_logloss: 0.498436
[77]	valid_0's binary_logloss: 0.502132
[78]	valid_0's binary_logloss: 0.506983
[79]	valid_0's binary_logloss: 0.507367
[80]	valid_0's binary_logloss: 0.505923
[81]	valid_0's binary_logloss: 0.506251
[82]	valid_0's binary_logloss: 0.505634
[83]	valid_0's binary_logloss: 0.50997
[84]	valid_0's binary_logloss: 0.512099
[

[397]	valid_0's binary_logloss: 0.852164
[398]	valid_0's binary_logloss: 0.856161
[399]	valid_0's binary_logloss: 0.853736
[400]	valid_0's binary_logloss: 0.855565
[401]	valid_0's binary_logloss: 0.854966
[402]	valid_0's binary_logloss: 0.855789
[403]	valid_0's binary_logloss: 0.856341
[404]	valid_0's binary_logloss: 0.856667
[405]	valid_0's binary_logloss: 0.855011
[406]	valid_0's binary_logloss: 0.854652
[407]	valid_0's binary_logloss: 0.854045
[408]	valid_0's binary_logloss: 0.856668
[409]	valid_0's binary_logloss: 0.858896
[410]	valid_0's binary_logloss: 0.860883
[411]	valid_0's binary_logloss: 0.861234
[412]	valid_0's binary_logloss: 0.859608
[413]	valid_0's binary_logloss: 0.861796
[414]	valid_0's binary_logloss: 0.86182
[415]	valid_0's binary_logloss: 0.859363
[416]	valid_0's binary_logloss: 0.86042
[417]	valid_0's binary_logloss: 0.864564
[418]	valid_0's binary_logloss: 0.865933
[419]	valid_0's binary_logloss: 0.869843
[420]	valid_0's binary_logloss: 0.871434
[421]	valid_0's bi

[710]	valid_0's binary_logloss: 1.09437
[711]	valid_0's binary_logloss: 1.09066
[712]	valid_0's binary_logloss: 1.08987
[713]	valid_0's binary_logloss: 1.09298
[714]	valid_0's binary_logloss: 1.09288
[715]	valid_0's binary_logloss: 1.09472
[716]	valid_0's binary_logloss: 1.09501
[717]	valid_0's binary_logloss: 1.09461
[718]	valid_0's binary_logloss: 1.0959
[719]	valid_0's binary_logloss: 1.10004
[720]	valid_0's binary_logloss: 1.10147
[721]	valid_0's binary_logloss: 1.10154
[722]	valid_0's binary_logloss: 1.09987
[723]	valid_0's binary_logloss: 1.10101
[724]	valid_0's binary_logloss: 1.09974
[725]	valid_0's binary_logloss: 1.09992
[726]	valid_0's binary_logloss: 1.09885
[727]	valid_0's binary_logloss: 1.09875
[728]	valid_0's binary_logloss: 1.09843
[729]	valid_0's binary_logloss: 1.09899
[730]	valid_0's binary_logloss: 1.10622
[731]	valid_0's binary_logloss: 1.10729
[732]	valid_0's binary_logloss: 1.10731
[733]	valid_0's binary_logloss: 1.10802
[734]	valid_0's binary_logloss: 1.10801
[

[1052]	valid_0's binary_logloss: 1.23212
[1053]	valid_0's binary_logloss: 1.23232
[1054]	valid_0's binary_logloss: 1.2325
[1055]	valid_0's binary_logloss: 1.23417
[1056]	valid_0's binary_logloss: 1.23457
[1057]	valid_0's binary_logloss: 1.23528
[1058]	valid_0's binary_logloss: 1.2353
[1059]	valid_0's binary_logloss: 1.23526
[1060]	valid_0's binary_logloss: 1.23795
[1061]	valid_0's binary_logloss: 1.23792
[1062]	valid_0's binary_logloss: 1.23849
[1063]	valid_0's binary_logloss: 1.23857
[1064]	valid_0's binary_logloss: 1.2387
[1065]	valid_0's binary_logloss: 1.23873
[1066]	valid_0's binary_logloss: 1.24046
[1067]	valid_0's binary_logloss: 1.24041
[1068]	valid_0's binary_logloss: 1.24038
[1069]	valid_0's binary_logloss: 1.24173
[1070]	valid_0's binary_logloss: 1.24211
[1071]	valid_0's binary_logloss: 1.24392
[1072]	valid_0's binary_logloss: 1.24393
[1073]	valid_0's binary_logloss: 1.24398
[1074]	valid_0's binary_logloss: 1.24413
[1075]	valid_0's binary_logloss: 1.24427
[1076]	valid_0's bi

[1458]	valid_0's binary_logloss: 1.30527
[1459]	valid_0's binary_logloss: 1.30633
[1460]	valid_0's binary_logloss: 1.30643
[1461]	valid_0's binary_logloss: 1.30643
[1462]	valid_0's binary_logloss: 1.30651
[1463]	valid_0's binary_logloss: 1.30655
[1464]	valid_0's binary_logloss: 1.30648
[1465]	valid_0's binary_logloss: 1.30653
[1466]	valid_0's binary_logloss: 1.30659
[1467]	valid_0's binary_logloss: 1.30657
[1468]	valid_0's binary_logloss: 1.30655
[1469]	valid_0's binary_logloss: 1.3072
[1470]	valid_0's binary_logloss: 1.30721
[1471]	valid_0's binary_logloss: 1.3073
[1472]	valid_0's binary_logloss: 1.30735
[1473]	valid_0's binary_logloss: 1.30727
[1474]	valid_0's binary_logloss: 1.30696
[1475]	valid_0's binary_logloss: 1.30693
[1476]	valid_0's binary_logloss: 1.30714
[1477]	valid_0's binary_logloss: 1.30647
[1478]	valid_0's binary_logloss: 1.30644
[1479]	valid_0's binary_logloss: 1.30647
[1480]	valid_0's binary_logloss: 1.30657
[1481]	valid_0's binary_logloss: 1.30654
[1482]	valid_0's b

[272]	valid_0's binary_logloss: 1.07205
[273]	valid_0's binary_logloss: 1.07524
[274]	valid_0's binary_logloss: 1.07819
[275]	valid_0's binary_logloss: 1.07975
[276]	valid_0's binary_logloss: 1.07941
[277]	valid_0's binary_logloss: 1.08089
[278]	valid_0's binary_logloss: 1.08076
[279]	valid_0's binary_logloss: 1.0821
[280]	valid_0's binary_logloss: 1.08624
[281]	valid_0's binary_logloss: 1.0864
[282]	valid_0's binary_logloss: 1.08709
[283]	valid_0's binary_logloss: 1.0886
[284]	valid_0's binary_logloss: 1.09052
[285]	valid_0's binary_logloss: 1.09605
[286]	valid_0's binary_logloss: 1.09979
[287]	valid_0's binary_logloss: 1.10037
[288]	valid_0's binary_logloss: 1.10149
[289]	valid_0's binary_logloss: 1.1039
[290]	valid_0's binary_logloss: 1.10386
[291]	valid_0's binary_logloss: 1.10339
[292]	valid_0's binary_logloss: 1.10388
[293]	valid_0's binary_logloss: 1.10505
[294]	valid_0's binary_logloss: 1.10523
[295]	valid_0's binary_logloss: 1.11229
[296]	valid_0's binary_logloss: 1.112
[297]	

[584]	valid_0's binary_logloss: 1.21641
[585]	valid_0's binary_logloss: 1.21638
[586]	valid_0's binary_logloss: 1.21642
[587]	valid_0's binary_logloss: 1.21647
[588]	valid_0's binary_logloss: 1.2165
[589]	valid_0's binary_logloss: 1.21655
[590]	valid_0's binary_logloss: 1.21658
[591]	valid_0's binary_logloss: 1.21677
[592]	valid_0's binary_logloss: 1.21673
[593]	valid_0's binary_logloss: 1.21672
[594]	valid_0's binary_logloss: 1.2168
[595]	valid_0's binary_logloss: 1.21669
[596]	valid_0's binary_logloss: 1.21684
[597]	valid_0's binary_logloss: 1.21689
[598]	valid_0's binary_logloss: 1.21689
[599]	valid_0's binary_logloss: 1.21699
[600]	valid_0's binary_logloss: 1.21705
[601]	valid_0's binary_logloss: 1.21725
[602]	valid_0's binary_logloss: 1.21724
[603]	valid_0's binary_logloss: 1.21733
[604]	valid_0's binary_logloss: 1.21724
[605]	valid_0's binary_logloss: 1.21734
[606]	valid_0's binary_logloss: 1.2175
[607]	valid_0's binary_logloss: 1.21754
[608]	valid_0's binary_logloss: 1.21761
[60

[840]	valid_0's binary_logloss: 1.2459
[841]	valid_0's binary_logloss: 1.24602
[842]	valid_0's binary_logloss: 1.24604
[843]	valid_0's binary_logloss: 1.24609
[844]	valid_0's binary_logloss: 1.24611
[845]	valid_0's binary_logloss: 1.24617
[846]	valid_0's binary_logloss: 1.24617
[847]	valid_0's binary_logloss: 1.2462
[848]	valid_0's binary_logloss: 1.24638
[849]	valid_0's binary_logloss: 1.2489
[850]	valid_0's binary_logloss: 1.24894
[851]	valid_0's binary_logloss: 1.24899
[852]	valid_0's binary_logloss: 1.24903
[853]	valid_0's binary_logloss: 1.24903
[854]	valid_0's binary_logloss: 1.24903
[855]	valid_0's binary_logloss: 1.24903
[856]	valid_0's binary_logloss: 1.24903
[857]	valid_0's binary_logloss: 1.24915
[858]	valid_0's binary_logloss: 1.24924
[859]	valid_0's binary_logloss: 1.24929
[860]	valid_0's binary_logloss: 1.2493
[861]	valid_0's binary_logloss: 1.24943
[862]	valid_0's binary_logloss: 1.2495
[863]	valid_0's binary_logloss: 1.24957
[864]	valid_0's binary_logloss: 1.24961
[865]

[1138]	valid_0's binary_logloss: 1.26746
[1139]	valid_0's binary_logloss: 1.26749
[1140]	valid_0's binary_logloss: 1.26752
[1141]	valid_0's binary_logloss: 1.26762
[1142]	valid_0's binary_logloss: 1.26764
[1143]	valid_0's binary_logloss: 1.26759
[1144]	valid_0's binary_logloss: 1.26752
[1145]	valid_0's binary_logloss: 1.26752
[1146]	valid_0's binary_logloss: 1.26754
[1147]	valid_0's binary_logloss: 1.26755
[1148]	valid_0's binary_logloss: 1.26754
[1149]	valid_0's binary_logloss: 1.26757
[1150]	valid_0's binary_logloss: 1.26764
[1151]	valid_0's binary_logloss: 1.26772
[1152]	valid_0's binary_logloss: 1.26774
[1153]	valid_0's binary_logloss: 1.26778
[1154]	valid_0's binary_logloss: 1.26778
[1155]	valid_0's binary_logloss: 1.26775
[1156]	valid_0's binary_logloss: 1.26782
[1157]	valid_0's binary_logloss: 1.26785
[1158]	valid_0's binary_logloss: 1.26782
[1159]	valid_0's binary_logloss: 1.26786
[1160]	valid_0's binary_logloss: 1.26789
[1161]	valid_0's binary_logloss: 1.2679
[1162]	valid_0's 

[1466]	valid_0's binary_logloss: 1.28015
[1467]	valid_0's binary_logloss: 1.28023
[1468]	valid_0's binary_logloss: 1.28025
[1469]	valid_0's binary_logloss: 1.28024
[1470]	valid_0's binary_logloss: 1.28032
[1471]	valid_0's binary_logloss: 1.28036
[1472]	valid_0's binary_logloss: 1.28035
[1473]	valid_0's binary_logloss: 1.28042
[1474]	valid_0's binary_logloss: 1.28049
[1475]	valid_0's binary_logloss: 1.28055
[1476]	valid_0's binary_logloss: 1.28062
[1477]	valid_0's binary_logloss: 1.28061
[1478]	valid_0's binary_logloss: 1.28056
[1479]	valid_0's binary_logloss: 1.28062
[1480]	valid_0's binary_logloss: 1.2806
[1481]	valid_0's binary_logloss: 1.28064
[1482]	valid_0's binary_logloss: 1.28064
[1483]	valid_0's binary_logloss: 1.28064
[1484]	valid_0's binary_logloss: 1.28069
[1485]	valid_0's binary_logloss: 1.28073
[1486]	valid_0's binary_logloss: 1.28076
[1487]	valid_0's binary_logloss: 1.28078
[1488]	valid_0's binary_logloss: 1.28084
[1489]	valid_0's binary_logloss: 1.28091
[1490]	valid_0's 

| 4         | 0.7327    | 0.1993    | 9.094     | 1.723e+03 |
[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.633926
[2]	valid_0's binary_logloss: 0.590955
[3]	valid_0's binary_logloss: 0.558749
[4]	valid_0's binary_logloss: 0.535503
[5]	valid_0's binary_logloss: 0.521047
[6]	valid_0's binary_logloss: 0.514739
[7]	valid_0's binary_logloss: 0.498951
[8]	valid_0's binary_logloss: 0.487897
[9]	valid_0's binary_logloss: 0.485764
[10]	valid_0's binary_logloss: 0.48801
[11]	valid_0's binary_logloss: 0.491735
[12]	valid_0's binary_logloss: 0.493733
[13]	valid_0's binary_logloss: 0.486641
[14]	valid_0's binary_logloss: 0.484944
[15]	valid_0's binary_logloss: 0.481424
[16]	valid_0's binary_logloss: 0.478668
[17]	valid_0's binary_logloss: 0.481022
[18]	valid_0's binary_logloss: 0.491769
[19]	valid_0's binary_logloss: 0.494399
[20]	valid_0's binary_logloss: 0.490343
[21]	valid_0's binary_logloss: 0.491984
[22]	valid_0's binary_logloss: 0.487896
[23]	valid_0's b

[317]	valid_0's binary_logloss: 1.16107
[318]	valid_0's binary_logloss: 1.16774
[319]	valid_0's binary_logloss: 1.1703
[320]	valid_0's binary_logloss: 1.16977
[321]	valid_0's binary_logloss: 1.17052
[322]	valid_0's binary_logloss: 1.17046
[323]	valid_0's binary_logloss: 1.17031
[324]	valid_0's binary_logloss: 1.17158
[325]	valid_0's binary_logloss: 1.17132
[326]	valid_0's binary_logloss: 1.17117
[327]	valid_0's binary_logloss: 1.17201
[328]	valid_0's binary_logloss: 1.17206
[329]	valid_0's binary_logloss: 1.17228
[330]	valid_0's binary_logloss: 1.17227
[331]	valid_0's binary_logloss: 1.1725
[332]	valid_0's binary_logloss: 1.17248
[333]	valid_0's binary_logloss: 1.17257
[334]	valid_0's binary_logloss: 1.17293
[335]	valid_0's binary_logloss: 1.173
[336]	valid_0's binary_logloss: 1.1731
[337]	valid_0's binary_logloss: 1.17348
[338]	valid_0's binary_logloss: 1.17727
[339]	valid_0's binary_logloss: 1.1821
[340]	valid_0's binary_logloss: 1.18242
[341]	valid_0's binary_logloss: 1.18251
[342]	

[219]	valid_0's binary_logloss: 0.485659
[220]	valid_0's binary_logloss: 0.485311
[221]	valid_0's binary_logloss: 0.484982
[222]	valid_0's binary_logloss: 0.484677
[223]	valid_0's binary_logloss: 0.484693
[224]	valid_0's binary_logloss: 0.484585
[225]	valid_0's binary_logloss: 0.484377
[226]	valid_0's binary_logloss: 0.483877
[227]	valid_0's binary_logloss: 0.483676
[228]	valid_0's binary_logloss: 0.48336
[229]	valid_0's binary_logloss: 0.483241
[230]	valid_0's binary_logloss: 0.483058
[231]	valid_0's binary_logloss: 0.482753
[232]	valid_0's binary_logloss: 0.482569
[233]	valid_0's binary_logloss: 0.482285
[234]	valid_0's binary_logloss: 0.482096
[235]	valid_0's binary_logloss: 0.48182
[236]	valid_0's binary_logloss: 0.48163
[237]	valid_0's binary_logloss: 0.481357
[238]	valid_0's binary_logloss: 0.481901
[239]	valid_0's binary_logloss: 0.481631
[240]	valid_0's binary_logloss: 0.481197
[241]	valid_0's binary_logloss: 0.481222
[242]	valid_0's binary_logloss: 0.481332
[243]	valid_0's bin

[586]	valid_0's binary_logloss: 0.48446
[587]	valid_0's binary_logloss: 0.484583
[588]	valid_0's binary_logloss: 0.484815
[589]	valid_0's binary_logloss: 0.48472
[590]	valid_0's binary_logloss: 0.48473
[591]	valid_0's binary_logloss: 0.484738
[592]	valid_0's binary_logloss: 0.48495
[593]	valid_0's binary_logloss: 0.48487
[594]	valid_0's binary_logloss: 0.484864
[595]	valid_0's binary_logloss: 0.484638
[596]	valid_0's binary_logloss: 0.484562
[597]	valid_0's binary_logloss: 0.48462
[598]	valid_0's binary_logloss: 0.485116
[599]	valid_0's binary_logloss: 0.485447
[600]	valid_0's binary_logloss: 0.485472
[601]	valid_0's binary_logloss: 0.485966
[602]	valid_0's binary_logloss: 0.48591
[603]	valid_0's binary_logloss: 0.486082
[604]	valid_0's binary_logloss: 0.486087
[605]	valid_0's binary_logloss: 0.486374
[606]	valid_0's binary_logloss: 0.48638
[607]	valid_0's binary_logloss: 0.486215
[608]	valid_0's binary_logloss: 0.486342
[609]	valid_0's binary_logloss: 0.486019
[610]	valid_0's binary_l

[927]	valid_0's binary_logloss: 0.507079
[928]	valid_0's binary_logloss: 0.507008
[929]	valid_0's binary_logloss: 0.507074
[930]	valid_0's binary_logloss: 0.50714
[931]	valid_0's binary_logloss: 0.507206
[932]	valid_0's binary_logloss: 0.507272
[933]	valid_0's binary_logloss: 0.507544
[934]	valid_0's binary_logloss: 0.507695
[935]	valid_0's binary_logloss: 0.507742
[936]	valid_0's binary_logloss: 0.507767
[937]	valid_0's binary_logloss: 0.507833
[938]	valid_0's binary_logloss: 0.507858
[939]	valid_0's binary_logloss: 0.507922
[940]	valid_0's binary_logloss: 0.507948
[941]	valid_0's binary_logloss: 0.508228
[942]	valid_0's binary_logloss: 0.508359
[943]	valid_0's binary_logloss: 0.508719
[944]	valid_0's binary_logloss: 0.508595
[945]	valid_0's binary_logloss: 0.508639
[946]	valid_0's binary_logloss: 0.508645
[947]	valid_0's binary_logloss: 0.508709
[948]	valid_0's binary_logloss: 0.508645
[949]	valid_0's binary_logloss: 0.508816
[950]	valid_0's binary_logloss: 0.508883
[951]	valid_0's b

[1275]	valid_0's binary_logloss: 0.534615
[1276]	valid_0's binary_logloss: 0.534787
[1277]	valid_0's binary_logloss: 0.535012
[1278]	valid_0's binary_logloss: 0.535071
[1279]	valid_0's binary_logloss: 0.535278
[1280]	valid_0's binary_logloss: 0.535589
[1281]	valid_0's binary_logloss: 0.535643
[1282]	valid_0's binary_logloss: 0.535624
[1283]	valid_0's binary_logloss: 0.535763
[1284]	valid_0's binary_logloss: 0.535815
[1285]	valid_0's binary_logloss: 0.535823
[1286]	valid_0's binary_logloss: 0.535893
[1287]	valid_0's binary_logloss: 0.535856
[1288]	valid_0's binary_logloss: 0.536087
[1289]	valid_0's binary_logloss: 0.536057
[1290]	valid_0's binary_logloss: 0.536042
[1291]	valid_0's binary_logloss: 0.535846
[1292]	valid_0's binary_logloss: 0.535865
[1293]	valid_0's binary_logloss: 0.535597
[1294]	valid_0's binary_logloss: 0.535705
[1295]	valid_0's binary_logloss: 0.536038
[1296]	valid_0's binary_logloss: 0.536351
[1297]	valid_0's binary_logloss: 0.536598
[1298]	valid_0's binary_logloss: 0

| 6         | 0.7562    | 0.02226   | 3.304     | 1.497e+03 |
[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.655844
[2]	valid_0's binary_logloss: 0.621198
[3]	valid_0's binary_logloss: 0.592636
[4]	valid_0's binary_logloss: 0.569944
[5]	valid_0's binary_logloss: 0.552101
[6]	valid_0's binary_logloss: 0.538444
[7]	valid_0's binary_logloss: 0.53205
[8]	valid_0's binary_logloss: 0.522959
[9]	valid_0's binary_logloss: 0.516792
[10]	valid_0's binary_logloss: 0.503756
[11]	valid_0's binary_logloss: 0.493479
[12]	valid_0's binary_logloss: 0.491557
[13]	valid_0's binary_logloss: 0.491807
[14]	valid_0's binary_logloss: 0.485217
[15]	valid_0's binary_logloss: 0.483254
[16]	valid_0's binary_logloss: 0.480024
[17]	valid_0's binary_logloss: 0.478256
[18]	valid_0's binary_logloss: 0.476482
[19]	valid_0's binary_logloss: 0.476982
[20]	valid_0's binary_logloss: 0.473293
[21]	valid_0's binary_logloss: 0.47507
[22]	valid_0's binary_logloss: 0.472382
[23]	valid_0's bi

[333]	valid_0's binary_logloss: 1.02936
[334]	valid_0's binary_logloss: 1.02965
[335]	valid_0's binary_logloss: 1.03019
[336]	valid_0's binary_logloss: 1.0312
[337]	valid_0's binary_logloss: 1.03455
[338]	valid_0's binary_logloss: 1.03496
[339]	valid_0's binary_logloss: 1.03556
[340]	valid_0's binary_logloss: 1.03626
[341]	valid_0's binary_logloss: 1.03751
[342]	valid_0's binary_logloss: 1.03824
[343]	valid_0's binary_logloss: 1.03972
[344]	valid_0's binary_logloss: 1.04142
[345]	valid_0's binary_logloss: 1.04318
[346]	valid_0's binary_logloss: 1.04514
[347]	valid_0's binary_logloss: 1.04657
[348]	valid_0's binary_logloss: 1.04815
[349]	valid_0's binary_logloss: 1.04977
[350]	valid_0's binary_logloss: 1.0506
[351]	valid_0's binary_logloss: 1.05146
[352]	valid_0's binary_logloss: 1.05262
[353]	valid_0's binary_logloss: 1.05302
[354]	valid_0's binary_logloss: 1.05183
[355]	valid_0's binary_logloss: 1.05291
[356]	valid_0's binary_logloss: 1.05445
[357]	valid_0's binary_logloss: 1.05505
[3

[674]	valid_0's binary_logloss: 1.19392
[675]	valid_0's binary_logloss: 1.19391
[676]	valid_0's binary_logloss: 1.19391
[677]	valid_0's binary_logloss: 1.19385
[678]	valid_0's binary_logloss: 1.19394
[679]	valid_0's binary_logloss: 1.19401
[680]	valid_0's binary_logloss: 1.19412
[681]	valid_0's binary_logloss: 1.19407
[682]	valid_0's binary_logloss: 1.19405
[683]	valid_0's binary_logloss: 1.19409
[684]	valid_0's binary_logloss: 1.19421
[685]	valid_0's binary_logloss: 1.19436
[686]	valid_0's binary_logloss: 1.19443
[687]	valid_0's binary_logloss: 1.19454
[688]	valid_0's binary_logloss: 1.1946
[689]	valid_0's binary_logloss: 1.19459
[690]	valid_0's binary_logloss: 1.19463
[691]	valid_0's binary_logloss: 1.19474
[692]	valid_0's binary_logloss: 1.19479
[693]	valid_0's binary_logloss: 1.19483
[694]	valid_0's binary_logloss: 1.1949
[695]	valid_0's binary_logloss: 1.19483
[696]	valid_0's binary_logloss: 1.19479
[697]	valid_0's binary_logloss: 1.19486
[698]	valid_0's binary_logloss: 1.19489
[6

[937]	valid_0's binary_logloss: 1.2221
[938]	valid_0's binary_logloss: 1.22212
[939]	valid_0's binary_logloss: 1.2222
[940]	valid_0's binary_logloss: 1.22236
[941]	valid_0's binary_logloss: 1.2224
[942]	valid_0's binary_logloss: 1.2225
[943]	valid_0's binary_logloss: 1.22261
[944]	valid_0's binary_logloss: 1.22262
[945]	valid_0's binary_logloss: 1.2226
[946]	valid_0's binary_logloss: 1.22285
[947]	valid_0's binary_logloss: 1.22296
[948]	valid_0's binary_logloss: 1.223
[949]	valid_0's binary_logloss: 1.22303
[950]	valid_0's binary_logloss: 1.22302
[951]	valid_0's binary_logloss: 1.22308
[952]	valid_0's binary_logloss: 1.22316
[953]	valid_0's binary_logloss: 1.22316
[954]	valid_0's binary_logloss: 1.22319
[955]	valid_0's binary_logloss: 1.22329
[956]	valid_0's binary_logloss: 1.22329
[957]	valid_0's binary_logloss: 1.22338
[958]	valid_0's binary_logloss: 1.2235
[959]	valid_0's binary_logloss: 1.22353
[960]	valid_0's binary_logloss: 1.22357
[961]	valid_0's binary_logloss: 1.22362
[962]	va

[1280]	valid_0's binary_logloss: 1.24664
[1281]	valid_0's binary_logloss: 1.24673
[1282]	valid_0's binary_logloss: 1.24675
[1283]	valid_0's binary_logloss: 1.2468
[1284]	valid_0's binary_logloss: 1.24682
[1285]	valid_0's binary_logloss: 1.24686
[1286]	valid_0's binary_logloss: 1.24689
[1287]	valid_0's binary_logloss: 1.24692
[1288]	valid_0's binary_logloss: 1.24691
[1289]	valid_0's binary_logloss: 1.24693
[1290]	valid_0's binary_logloss: 1.24699
[1291]	valid_0's binary_logloss: 1.24695
[1292]	valid_0's binary_logloss: 1.24693
[1293]	valid_0's binary_logloss: 1.24698
[1294]	valid_0's binary_logloss: 1.24698
[1295]	valid_0's binary_logloss: 1.247
[1296]	valid_0's binary_logloss: 1.24699
[1297]	valid_0's binary_logloss: 1.24698
[1298]	valid_0's binary_logloss: 1.24701
[1299]	valid_0's binary_logloss: 1.24703
[1300]	valid_0's binary_logloss: 1.24709
[1301]	valid_0's binary_logloss: 1.24716
[1302]	valid_0's binary_logloss: 1.24716
[1303]	valid_0's binary_logloss: 1.24712
[1304]	valid_0's bi

[1609]	valid_0's binary_logloss: 1.25739
[1610]	valid_0's binary_logloss: 1.25747
[1611]	valid_0's binary_logloss: 1.25751
[1612]	valid_0's binary_logloss: 1.25757
[1613]	valid_0's binary_logloss: 1.25758
[1614]	valid_0's binary_logloss: 1.25759
[1615]	valid_0's binary_logloss: 1.2576
[1616]	valid_0's binary_logloss: 1.25912
[1617]	valid_0's binary_logloss: 1.25914
[1618]	valid_0's binary_logloss: 1.25916
[1619]	valid_0's binary_logloss: 1.25918
[1620]	valid_0's binary_logloss: 1.25921
[1621]	valid_0's binary_logloss: 1.25924
[1622]	valid_0's binary_logloss: 1.25925
[1623]	valid_0's binary_logloss: 1.2593
[1624]	valid_0's binary_logloss: 1.25931
[1625]	valid_0's binary_logloss: 1.25938
[1626]	valid_0's binary_logloss: 1.25939
[1627]	valid_0's binary_logloss: 1.25942
[1628]	valid_0's binary_logloss: 1.25945
[1629]	valid_0's binary_logloss: 1.25948
[1630]	valid_0's binary_logloss: 1.25956
[1631]	valid_0's binary_logloss: 1.25959
[1632]	valid_0's binary_logloss: 1.25963
[1633]	valid_0's b

[1940]	valid_0's binary_logloss: 1.27151
[1941]	valid_0's binary_logloss: 1.27152
[1942]	valid_0's binary_logloss: 1.27156
[1943]	valid_0's binary_logloss: 1.27155
[1944]	valid_0's binary_logloss: 1.27157
[1945]	valid_0's binary_logloss: 1.27162
[1946]	valid_0's binary_logloss: 1.27168
[1947]	valid_0's binary_logloss: 1.2717
[1948]	valid_0's binary_logloss: 1.27176
[1949]	valid_0's binary_logloss: 1.27178
[1950]	valid_0's binary_logloss: 1.27181
[1951]	valid_0's binary_logloss: 1.27179
[1952]	valid_0's binary_logloss: 1.27182
[1953]	valid_0's binary_logloss: 1.27185
[1954]	valid_0's binary_logloss: 1.27187
[1955]	valid_0's binary_logloss: 1.27186
[1956]	valid_0's binary_logloss: 1.27188
[1957]	valid_0's binary_logloss: 1.27186
[1958]	valid_0's binary_logloss: 1.27184
[1959]	valid_0's binary_logloss: 1.27188
[1960]	valid_0's binary_logloss: 1.27188
[1961]	valid_0's binary_logloss: 1.27194
[1962]	valid_0's binary_logloss: 1.27195
[1963]	valid_0's binary_logloss: 1.27196
[1964]	valid_0's 

[253]	valid_0's binary_logloss: 0.481502
[254]	valid_0's binary_logloss: 0.481425
[255]	valid_0's binary_logloss: 0.481465
[256]	valid_0's binary_logloss: 0.48091
[257]	valid_0's binary_logloss: 0.480971
[258]	valid_0's binary_logloss: 0.481372
[259]	valid_0's binary_logloss: 0.481555
[260]	valid_0's binary_logloss: 0.481674
[261]	valid_0's binary_logloss: 0.482174
[262]	valid_0's binary_logloss: 0.4822
[263]	valid_0's binary_logloss: 0.482327
[264]	valid_0's binary_logloss: 0.48253
[265]	valid_0's binary_logloss: 0.482682
[266]	valid_0's binary_logloss: 0.483028
[267]	valid_0's binary_logloss: 0.483065
[268]	valid_0's binary_logloss: 0.482819
[269]	valid_0's binary_logloss: 0.48318
[270]	valid_0's binary_logloss: 0.48353
[271]	valid_0's binary_logloss: 0.4839
[272]	valid_0's binary_logloss: 0.484098
[273]	valid_0's binary_logloss: 0.484279
[274]	valid_0's binary_logloss: 0.484576
[275]	valid_0's binary_logloss: 0.484851
[276]	valid_0's binary_logloss: 0.485259
[277]	valid_0's binary_l

[544]	valid_0's binary_logloss: 0.526873
[545]	valid_0's binary_logloss: 0.527442
[546]	valid_0's binary_logloss: 0.527687
[547]	valid_0's binary_logloss: 0.527905
[548]	valid_0's binary_logloss: 0.527883
[549]	valid_0's binary_logloss: 0.527932
[550]	valid_0's binary_logloss: 0.527843
[551]	valid_0's binary_logloss: 0.528019
[552]	valid_0's binary_logloss: 0.527859
[553]	valid_0's binary_logloss: 0.528086
[554]	valid_0's binary_logloss: 0.528257
[555]	valid_0's binary_logloss: 0.528737
[556]	valid_0's binary_logloss: 0.52886
[557]	valid_0's binary_logloss: 0.52895
[558]	valid_0's binary_logloss: 0.528873
[559]	valid_0's binary_logloss: 0.528995
[560]	valid_0's binary_logloss: 0.529429
[561]	valid_0's binary_logloss: 0.529465
[562]	valid_0's binary_logloss: 0.529769
[563]	valid_0's binary_logloss: 0.530075
[564]	valid_0's binary_logloss: 0.530517
[565]	valid_0's binary_logloss: 0.531114
[566]	valid_0's binary_logloss: 0.531557
[567]	valid_0's binary_logloss: 0.532062
[568]	valid_0's bi

[834]	valid_0's binary_logloss: 0.58875
[835]	valid_0's binary_logloss: 0.588793
[836]	valid_0's binary_logloss: 0.588651
[837]	valid_0's binary_logloss: 0.588701
[838]	valid_0's binary_logloss: 0.589518
[839]	valid_0's binary_logloss: 0.589559
[840]	valid_0's binary_logloss: 0.589822
[841]	valid_0's binary_logloss: 0.589461
[842]	valid_0's binary_logloss: 0.589432
[843]	valid_0's binary_logloss: 0.589682
[844]	valid_0's binary_logloss: 0.589686
[845]	valid_0's binary_logloss: 0.589767
[846]	valid_0's binary_logloss: 0.59034
[847]	valid_0's binary_logloss: 0.591099
[848]	valid_0's binary_logloss: 0.59134
[849]	valid_0's binary_logloss: 0.591406
[850]	valid_0's binary_logloss: 0.591454
[851]	valid_0's binary_logloss: 0.592027
[852]	valid_0's binary_logloss: 0.592257
[853]	valid_0's binary_logloss: 0.592491
[854]	valid_0's binary_logloss: 0.592801
[855]	valid_0's binary_logloss: 0.592948
[856]	valid_0's binary_logloss: 0.593254
[857]	valid_0's binary_logloss: 0.593357
[858]	valid_0's bin

[1119]	valid_0's binary_logloss: 0.64715
[1120]	valid_0's binary_logloss: 0.647036
[1121]	valid_0's binary_logloss: 0.647284
[1122]	valid_0's binary_logloss: 0.647432
[1123]	valid_0's binary_logloss: 0.647569
[1124]	valid_0's binary_logloss: 0.647656
[1125]	valid_0's binary_logloss: 0.647868
[1126]	valid_0's binary_logloss: 0.647824
[1127]	valid_0's binary_logloss: 0.648006
[1128]	valid_0's binary_logloss: 0.648273
[1129]	valid_0's binary_logloss: 0.648493
[1130]	valid_0's binary_logloss: 0.648594
[1131]	valid_0's binary_logloss: 0.648694
[1132]	valid_0's binary_logloss: 0.648766
[1133]	valid_0's binary_logloss: 0.648559
[1134]	valid_0's binary_logloss: 0.648377
[1135]	valid_0's binary_logloss: 0.648773
[1136]	valid_0's binary_logloss: 0.648579
[1137]	valid_0's binary_logloss: 0.648452
[1138]	valid_0's binary_logloss: 0.648681
[1139]	valid_0's binary_logloss: 0.649013
[1140]	valid_0's binary_logloss: 0.648927
[1141]	valid_0's binary_logloss: 0.649136
[1142]	valid_0's binary_logloss: 0.

[1418]	valid_0's binary_logloss: 0.714118
[1419]	valid_0's binary_logloss: 0.714646
[1420]	valid_0's binary_logloss: 0.714892
[1421]	valid_0's binary_logloss: 0.71534
[1422]	valid_0's binary_logloss: 0.716111
[1423]	valid_0's binary_logloss: 0.716915
[1424]	valid_0's binary_logloss: 0.716689
[1425]	valid_0's binary_logloss: 0.7167
[1426]	valid_0's binary_logloss: 0.717499
[1427]	valid_0's binary_logloss: 0.717529
[1428]	valid_0's binary_logloss: 0.717498
[1429]	valid_0's binary_logloss: 0.717573
[1430]	valid_0's binary_logloss: 0.71769
[1431]	valid_0's binary_logloss: 0.717879
[1432]	valid_0's binary_logloss: 0.717919
[1433]	valid_0's binary_logloss: 0.718399
[1434]	valid_0's binary_logloss: 0.718489
[1435]	valid_0's binary_logloss: 0.718629
[1436]	valid_0's binary_logloss: 0.718991
[1437]	valid_0's binary_logloss: 0.719404
[1438]	valid_0's binary_logloss: 0.719643
[1439]	valid_0's binary_logloss: 0.719928
[1440]	valid_0's binary_logloss: 0.72024
[1441]	valid_0's binary_logloss: 0.7206

[1705]	valid_0's binary_logloss: 0.773613
[1706]	valid_0's binary_logloss: 0.773917
[1707]	valid_0's binary_logloss: 0.774095
[1708]	valid_0's binary_logloss: 0.774457
[1709]	valid_0's binary_logloss: 0.774712
[1710]	valid_0's binary_logloss: 0.774953
[1711]	valid_0's binary_logloss: 0.775123
[1712]	valid_0's binary_logloss: 0.775295
[1713]	valid_0's binary_logloss: 0.775532
[1714]	valid_0's binary_logloss: 0.775938
[1715]	valid_0's binary_logloss: 0.776392
[1716]	valid_0's binary_logloss: 0.776646
[1717]	valid_0's binary_logloss: 0.776931
[1718]	valid_0's binary_logloss: 0.776949
[1719]	valid_0's binary_logloss: 0.777321
[1720]	valid_0's binary_logloss: 0.777573
[1721]	valid_0's binary_logloss: 0.777591
[1722]	valid_0's binary_logloss: 0.777948
[1723]	valid_0's binary_logloss: 0.778257
[1724]	valid_0's binary_logloss: 0.778526
[1725]	valid_0's binary_logloss: 0.778808
[1726]	valid_0's binary_logloss: 0.778776
[1727]	valid_0's binary_logloss: 0.779076
[1728]	valid_0's binary_logloss: 0

| 8         | 0.7586    | 0.01539   | 8.501     | 1.95e+03  |
[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.669985
[2]	valid_0's binary_logloss: 0.648497
[3]	valid_0's binary_logloss: 0.636931
[4]	valid_0's binary_logloss: 0.616977
[5]	valid_0's binary_logloss: 0.60609
[6]	valid_0's binary_logloss: 0.593103
[7]	valid_0's binary_logloss: 0.581937
[8]	valid_0's binary_logloss: 0.573592
[9]	valid_0's binary_logloss: 0.564076
[10]	valid_0's binary_logloss: 0.556404
[11]	valid_0's binary_logloss: 0.558936
[12]	valid_0's binary_logloss: 0.55888
[13]	valid_0's binary_logloss: 0.551801
[14]	valid_0's binary_logloss: 0.54599
[15]	valid_0's binary_logloss: 0.541646
[16]	valid_0's binary_logloss: 0.540574
[17]	valid_0's binary_logloss: 0.538748
[18]	valid_0's binary_logloss: 0.536527
[19]	valid_0's binary_logloss: 0.538951
[20]	valid_0's binary_logloss: 0.535787
[21]	valid_0's binary_logloss: 0.534379
[22]	valid_0's binary_logloss: 0.533528
[23]	valid_0's bin

[648]	valid_0's binary_logloss: 0.745652
[649]	valid_0's binary_logloss: 0.746355
[650]	valid_0's binary_logloss: 0.748369
[651]	valid_0's binary_logloss: 0.748096
[652]	valid_0's binary_logloss: 0.748309
[653]	valid_0's binary_logloss: 0.748435
[654]	valid_0's binary_logloss: 0.750974
[655]	valid_0's binary_logloss: 0.749664
[656]	valid_0's binary_logloss: 0.750109
[657]	valid_0's binary_logloss: 0.751748
[658]	valid_0's binary_logloss: 0.753786
[659]	valid_0's binary_logloss: 0.754497
[660]	valid_0's binary_logloss: 0.753402
[661]	valid_0's binary_logloss: 0.752381
[662]	valid_0's binary_logloss: 0.752804
[663]	valid_0's binary_logloss: 0.752173
[664]	valid_0's binary_logloss: 0.752548
[665]	valid_0's binary_logloss: 0.753711
[666]	valid_0's binary_logloss: 0.754237
[667]	valid_0's binary_logloss: 0.754385
[668]	valid_0's binary_logloss: 0.753358
[669]	valid_0's binary_logloss: 0.75444
[670]	valid_0's binary_logloss: 0.754023
[671]	valid_0's binary_logloss: 0.753317
[672]	valid_0's b

[1126]	valid_0's binary_logloss: 0.921044
[1127]	valid_0's binary_logloss: 0.921346
[1128]	valid_0's binary_logloss: 0.921611
[1129]	valid_0's binary_logloss: 0.921936
[1130]	valid_0's binary_logloss: 0.921784
[1131]	valid_0's binary_logloss: 0.923802
[1132]	valid_0's binary_logloss: 0.92361
[1133]	valid_0's binary_logloss: 0.92422
[1134]	valid_0's binary_logloss: 0.923925
[1135]	valid_0's binary_logloss: 0.924497
[1136]	valid_0's binary_logloss: 0.925878
[1137]	valid_0's binary_logloss: 0.925458
[1138]	valid_0's binary_logloss: 0.925264
[1139]	valid_0's binary_logloss: 0.925041
[1140]	valid_0's binary_logloss: 0.925445
[1141]	valid_0's binary_logloss: 0.925795
[1142]	valid_0's binary_logloss: 0.926033
[1143]	valid_0's binary_logloss: 0.927939
[1144]	valid_0's binary_logloss: 0.929852
[1145]	valid_0's binary_logloss: 0.928711
[1146]	valid_0's binary_logloss: 0.928319
[1147]	valid_0's binary_logloss: 0.92772
[1148]	valid_0's binary_logloss: 0.926193
[1149]	valid_0's binary_logloss: 0.92

[1655]	valid_0's binary_logloss: 1.07247
[1656]	valid_0's binary_logloss: 1.07211
[1657]	valid_0's binary_logloss: 1.07212
[1658]	valid_0's binary_logloss: 1.07109
[1659]	valid_0's binary_logloss: 1.07173
[1660]	valid_0's binary_logloss: 1.07119
[1661]	valid_0's binary_logloss: 1.0712
[1662]	valid_0's binary_logloss: 1.07025
[1663]	valid_0's binary_logloss: 1.07031
[1664]	valid_0's binary_logloss: 1.07082
[1665]	valid_0's binary_logloss: 1.0717
[1666]	valid_0's binary_logloss: 1.07134
[1667]	valid_0's binary_logloss: 1.07078
[1668]	valid_0's binary_logloss: 1.07194
[1669]	valid_0's binary_logloss: 1.07306
[1670]	valid_0's binary_logloss: 1.07179
[1671]	valid_0's binary_logloss: 1.07281
[1672]	valid_0's binary_logloss: 1.07269
[1673]	valid_0's binary_logloss: 1.07269
[1674]	valid_0's binary_logloss: 1.07298
[1675]	valid_0's binary_logloss: 1.07277
[1676]	valid_0's binary_logloss: 1.07386
[1677]	valid_0's binary_logloss: 1.07382
[1678]	valid_0's binary_logloss: 1.07492
[1679]	valid_0's b

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.645129
[2]	valid_0's binary_logloss: 0.602647
[3]	valid_0's binary_logloss: 0.575762
[4]	valid_0's binary_logloss: 0.548147
[5]	valid_0's binary_logloss: 0.534958
[6]	valid_0's binary_logloss: 0.51744
[7]	valid_0's binary_logloss: 0.506678
[8]	valid_0's binary_logloss: 0.503232
[9]	valid_0's binary_logloss: 0.504574
[10]	valid_0's binary_logloss: 0.505555
[11]	valid_0's binary_logloss: 0.497169
[12]	valid_0's binary_logloss: 0.496913
[13]	valid_0's binary_logloss: 0.487532
[14]	valid_0's binary_logloss: 0.482837
[15]	valid_0's binary_logloss: 0.490436
[16]	valid_0's binary_logloss: 0.493155
[17]	valid_0's binary_logloss: 0.493946
[18]	valid_0's binary_logloss: 0.495699
[19]	valid_0's binary_logloss: 0.493697
[20]	valid_0's binary_logloss: 0.497829
[21]	valid_0's binary_logloss: 0.495481
[22]	valid_0's binary_logloss: 0.498323
[23]	valid_0's binary_logloss: 0.500466
[24]	valid_0's binary_logloss: 0.50138

[315]	valid_0's binary_logloss: 1.12128
[316]	valid_0's binary_logloss: 1.12359
[317]	valid_0's binary_logloss: 1.12651
[318]	valid_0's binary_logloss: 1.12663
[319]	valid_0's binary_logloss: 1.13048
[320]	valid_0's binary_logloss: 1.13064
[321]	valid_0's binary_logloss: 1.13259
[322]	valid_0's binary_logloss: 1.13279
[323]	valid_0's binary_logloss: 1.13273
[324]	valid_0's binary_logloss: 1.13466
[325]	valid_0's binary_logloss: 1.13499
[326]	valid_0's binary_logloss: 1.13563
[327]	valid_0's binary_logloss: 1.13714
[328]	valid_0's binary_logloss: 1.14027
[329]	valid_0's binary_logloss: 1.14155
[330]	valid_0's binary_logloss: 1.14326
[331]	valid_0's binary_logloss: 1.14381
[332]	valid_0's binary_logloss: 1.14347
[333]	valid_0's binary_logloss: 1.14454
[334]	valid_0's binary_logloss: 1.14417
[335]	valid_0's binary_logloss: 1.14427
[336]	valid_0's binary_logloss: 1.14809
[337]	valid_0's binary_logloss: 1.14823
[338]	valid_0's binary_logloss: 1.14818
[339]	valid_0's binary_logloss: 1.14926


[660]	valid_0's binary_logloss: 1.22518
[661]	valid_0's binary_logloss: 1.22527
[662]	valid_0's binary_logloss: 1.22536
[663]	valid_0's binary_logloss: 1.22539
[664]	valid_0's binary_logloss: 1.22536
[665]	valid_0's binary_logloss: 1.22539
[666]	valid_0's binary_logloss: 1.22532
[667]	valid_0's binary_logloss: 1.22536
[668]	valid_0's binary_logloss: 1.22538
[669]	valid_0's binary_logloss: 1.22529
[670]	valid_0's binary_logloss: 1.22533
[671]	valid_0's binary_logloss: 1.22542
[672]	valid_0's binary_logloss: 1.22552
[673]	valid_0's binary_logloss: 1.22546
[674]	valid_0's binary_logloss: 1.22533
[675]	valid_0's binary_logloss: 1.22544
[676]	valid_0's binary_logloss: 1.2255
[677]	valid_0's binary_logloss: 1.22557
[678]	valid_0's binary_logloss: 1.22548
[679]	valid_0's binary_logloss: 1.22559
[680]	valid_0's binary_logloss: 1.22556
[681]	valid_0's binary_logloss: 1.22552
[682]	valid_0's binary_logloss: 1.22561
[683]	valid_0's binary_logloss: 1.22568
[684]	valid_0's binary_logloss: 1.22759
[

[1027]	valid_0's binary_logloss: 1.25223
[1028]	valid_0's binary_logloss: 1.25225
[1029]	valid_0's binary_logloss: 1.25225
[1030]	valid_0's binary_logloss: 1.25232
[1031]	valid_0's binary_logloss: 1.25238
[1032]	valid_0's binary_logloss: 1.25237
[1033]	valid_0's binary_logloss: 1.25238
[1034]	valid_0's binary_logloss: 1.25234
[1035]	valid_0's binary_logloss: 1.25238
[1036]	valid_0's binary_logloss: 1.25245
[1037]	valid_0's binary_logloss: 1.25237
[1038]	valid_0's binary_logloss: 1.25244
[1039]	valid_0's binary_logloss: 1.25256
[1040]	valid_0's binary_logloss: 1.2526
[1041]	valid_0's binary_logloss: 1.25318
[1042]	valid_0's binary_logloss: 1.25313
[1043]	valid_0's binary_logloss: 1.2532
[1044]	valid_0's binary_logloss: 1.25334
[1045]	valid_0's binary_logloss: 1.25338
[1046]	valid_0's binary_logloss: 1.25342
[1047]	valid_0's binary_logloss: 1.25345
[1048]	valid_0's binary_logloss: 1.25702
[1049]	valid_0's binary_logloss: 1.25698
[1050]	valid_0's binary_logloss: 1.25779
[1051]	valid_0's b

[1377]	valid_0's binary_logloss: 1.27559
[1378]	valid_0's binary_logloss: 1.2756
[1379]	valid_0's binary_logloss: 1.27564
[1380]	valid_0's binary_logloss: 1.27563
[1381]	valid_0's binary_logloss: 1.27561
[1382]	valid_0's binary_logloss: 1.27558
[1383]	valid_0's binary_logloss: 1.27567
[1384]	valid_0's binary_logloss: 1.27572
[1385]	valid_0's binary_logloss: 1.27573
[1386]	valid_0's binary_logloss: 1.27577
[1387]	valid_0's binary_logloss: 1.27579
[1388]	valid_0's binary_logloss: 1.27581
[1389]	valid_0's binary_logloss: 1.27581
[1390]	valid_0's binary_logloss: 1.27587
[1391]	valid_0's binary_logloss: 1.2759
[1392]	valid_0's binary_logloss: 1.27584
[1393]	valid_0's binary_logloss: 1.27586
[1394]	valid_0's binary_logloss: 1.27589
[1395]	valid_0's binary_logloss: 1.27596
[1396]	valid_0's binary_logloss: 1.276
[1397]	valid_0's binary_logloss: 1.27602
[1398]	valid_0's binary_logloss: 1.27602
[1399]	valid_0's binary_logloss: 1.276
[1400]	valid_0's binary_logloss: 1.27601
[1401]	valid_0's binar

[164]	valid_0's binary_logloss: 1.06015
[165]	valid_0's binary_logloss: 1.06021
[166]	valid_0's binary_logloss: 1.06465
[167]	valid_0's binary_logloss: 1.06478
[168]	valid_0's binary_logloss: 1.0632
[169]	valid_0's binary_logloss: 1.06526
[170]	valid_0's binary_logloss: 1.06644
[171]	valid_0's binary_logloss: 1.06524
[172]	valid_0's binary_logloss: 1.06782
[173]	valid_0's binary_logloss: 1.06827
[174]	valid_0's binary_logloss: 1.07376
[175]	valid_0's binary_logloss: 1.07803
[176]	valid_0's binary_logloss: 1.07651
[177]	valid_0's binary_logloss: 1.07591
[178]	valid_0's binary_logloss: 1.07737
[179]	valid_0's binary_logloss: 1.07653
[180]	valid_0's binary_logloss: 1.07679
[181]	valid_0's binary_logloss: 1.07946
[182]	valid_0's binary_logloss: 1.07898
[183]	valid_0's binary_logloss: 1.08432
[184]	valid_0's binary_logloss: 1.08747
[185]	valid_0's binary_logloss: 1.08835
[186]	valid_0's binary_logloss: 1.09041
[187]	valid_0's binary_logloss: 1.0917
[188]	valid_0's binary_logloss: 1.09324
[1

[505]	valid_0's binary_logloss: 1.20739
[506]	valid_0's binary_logloss: 1.2076
[507]	valid_0's binary_logloss: 1.2076
[508]	valid_0's binary_logloss: 1.20768
[509]	valid_0's binary_logloss: 1.20788
[510]	valid_0's binary_logloss: 1.20799
[511]	valid_0's binary_logloss: 1.20826
[512]	valid_0's binary_logloss: 1.20833
[513]	valid_0's binary_logloss: 1.20828
[514]	valid_0's binary_logloss: 1.20837
[515]	valid_0's binary_logloss: 1.20842
[516]	valid_0's binary_logloss: 1.2085
[517]	valid_0's binary_logloss: 1.20853
[518]	valid_0's binary_logloss: 1.2086
[519]	valid_0's binary_logloss: 1.2088
[520]	valid_0's binary_logloss: 1.20886
[521]	valid_0's binary_logloss: 1.209
[522]	valid_0's binary_logloss: 1.21621
[523]	valid_0's binary_logloss: 1.21636
[524]	valid_0's binary_logloss: 1.21635
[525]	valid_0's binary_logloss: 1.2165
[526]	valid_0's binary_logloss: 1.21652
[527]	valid_0's binary_logloss: 1.21672
[528]	valid_0's binary_logloss: 1.21676
[529]	valid_0's binary_logloss: 1.2168
[530]	val

[838]	valid_0's binary_logloss: 1.2498
[839]	valid_0's binary_logloss: 1.24973
[840]	valid_0's binary_logloss: 1.24983
[841]	valid_0's binary_logloss: 1.24988
[842]	valid_0's binary_logloss: 1.24998
[843]	valid_0's binary_logloss: 1.24998
[844]	valid_0's binary_logloss: 1.24999
[845]	valid_0's binary_logloss: 1.25005
[846]	valid_0's binary_logloss: 1.25017
[847]	valid_0's binary_logloss: 1.25008
[848]	valid_0's binary_logloss: 1.25007
[849]	valid_0's binary_logloss: 1.25009
[850]	valid_0's binary_logloss: 1.2501
[851]	valid_0's binary_logloss: 1.25008
[852]	valid_0's binary_logloss: 1.25009
[853]	valid_0's binary_logloss: 1.25024
[854]	valid_0's binary_logloss: 1.25021
[855]	valid_0's binary_logloss: 1.25019
[856]	valid_0's binary_logloss: 1.25017
[857]	valid_0's binary_logloss: 1.25015
[858]	valid_0's binary_logloss: 1.25018
[859]	valid_0's binary_logloss: 1.25031
[860]	valid_0's binary_logloss: 1.25039
[861]	valid_0's binary_logloss: 1.25047
[862]	valid_0's binary_logloss: 1.25054
[8

[1166]	valid_0's binary_logloss: 1.27967
[1167]	valid_0's binary_logloss: 1.27968
[1168]	valid_0's binary_logloss: 1.27979
[1169]	valid_0's binary_logloss: 1.27985
[1170]	valid_0's binary_logloss: 1.27982
[1171]	valid_0's binary_logloss: 1.27981
[1172]	valid_0's binary_logloss: 1.27983
[1173]	valid_0's binary_logloss: 1.2798
[1174]	valid_0's binary_logloss: 1.27987
[1175]	valid_0's binary_logloss: 1.2799
[1176]	valid_0's binary_logloss: 1.27999
[1177]	valid_0's binary_logloss: 1.27998
[1178]	valid_0's binary_logloss: 1.28002
[1179]	valid_0's binary_logloss: 1.28001
[1180]	valid_0's binary_logloss: 1.28009
[1181]	valid_0's binary_logloss: 1.28011
[1182]	valid_0's binary_logloss: 1.28015
[1183]	valid_0's binary_logloss: 1.28009
[1184]	valid_0's binary_logloss: 1.28012
[1185]	valid_0's binary_logloss: 1.28015
[1186]	valid_0's binary_logloss: 1.28018
[1187]	valid_0's binary_logloss: 1.28022
[1188]	valid_0's binary_logloss: 1.28031
[1189]	valid_0's binary_logloss: 1.2804
[1190]	valid_0's bi

[1436]	valid_0's binary_logloss: 1.29145
[1437]	valid_0's binary_logloss: 1.29147
[1438]	valid_0's binary_logloss: 1.29153
[1439]	valid_0's binary_logloss: 1.29157
[1440]	valid_0's binary_logloss: 1.2916
[1441]	valid_0's binary_logloss: 1.29167
[1442]	valid_0's binary_logloss: 1.29172
[1443]	valid_0's binary_logloss: 1.29177
[1444]	valid_0's binary_logloss: 1.29179
[1445]	valid_0's binary_logloss: 1.29189
[1446]	valid_0's binary_logloss: 1.29196
[1447]	valid_0's binary_logloss: 1.29203
[1448]	valid_0's binary_logloss: 1.29212
[1449]	valid_0's binary_logloss: 1.29216
[1450]	valid_0's binary_logloss: 1.29222
[1451]	valid_0's binary_logloss: 1.2923
[1452]	valid_0's binary_logloss: 1.29237
[1453]	valid_0's binary_logloss: 1.29248
[1454]	valid_0's binary_logloss: 1.29253
[1455]	valid_0's binary_logloss: 1.29257
[1456]	valid_0's binary_logloss: 1.29267
[1457]	valid_0's binary_logloss: 1.29265
[1458]	valid_0's binary_logloss: 1.29274
[1459]	valid_0's binary_logloss: 1.29282
[1460]	valid_0's b

[134]	valid_0's binary_logloss: 0.509799
[135]	valid_0's binary_logloss: 0.507839
[136]	valid_0's binary_logloss: 0.50848
[137]	valid_0's binary_logloss: 0.507542
[138]	valid_0's binary_logloss: 0.50529
[139]	valid_0's binary_logloss: 0.506717
[140]	valid_0's binary_logloss: 0.509673
[141]	valid_0's binary_logloss: 0.511572
[142]	valid_0's binary_logloss: 0.514513
[143]	valid_0's binary_logloss: 0.514238
[144]	valid_0's binary_logloss: 0.516626
[145]	valid_0's binary_logloss: 0.518704
[146]	valid_0's binary_logloss: 0.51642
[147]	valid_0's binary_logloss: 0.514497
[148]	valid_0's binary_logloss: 0.518211
[149]	valid_0's binary_logloss: 0.518817
[150]	valid_0's binary_logloss: 0.517145
[151]	valid_0's binary_logloss: 0.518341
[152]	valid_0's binary_logloss: 0.521573
[153]	valid_0's binary_logloss: 0.521578
[154]	valid_0's binary_logloss: 0.52074
[155]	valid_0's binary_logloss: 0.518362
[156]	valid_0's binary_logloss: 0.520247
[157]	valid_0's binary_logloss: 0.521674
[158]	valid_0's bina

[597]	valid_0's binary_logloss: 0.790928
[598]	valid_0's binary_logloss: 0.791862
[599]	valid_0's binary_logloss: 0.793902
[600]	valid_0's binary_logloss: 0.794268
[601]	valid_0's binary_logloss: 0.794026
[602]	valid_0's binary_logloss: 0.794461
[603]	valid_0's binary_logloss: 0.795376
[604]	valid_0's binary_logloss: 0.795823
[605]	valid_0's binary_logloss: 0.794927
[606]	valid_0's binary_logloss: 0.793745
[607]	valid_0's binary_logloss: 0.795173
[608]	valid_0's binary_logloss: 0.795847
[609]	valid_0's binary_logloss: 0.797849
[610]	valid_0's binary_logloss: 0.798228
[611]	valid_0's binary_logloss: 0.798969
[612]	valid_0's binary_logloss: 0.799362
[613]	valid_0's binary_logloss: 0.799741
[614]	valid_0's binary_logloss: 0.800301
[615]	valid_0's binary_logloss: 0.798568
[616]	valid_0's binary_logloss: 0.797323
[617]	valid_0's binary_logloss: 0.798987
[618]	valid_0's binary_logloss: 0.799476
[619]	valid_0's binary_logloss: 0.7982
[620]	valid_0's binary_logloss: 0.797798
[621]	valid_0's bi

[1032]	valid_0's binary_logloss: 0.975486
[1033]	valid_0's binary_logloss: 0.975624
[1034]	valid_0's binary_logloss: 0.975434
[1035]	valid_0's binary_logloss: 0.974686
[1036]	valid_0's binary_logloss: 0.974965
[1037]	valid_0's binary_logloss: 0.974751
[1038]	valid_0's binary_logloss: 0.974774
[1039]	valid_0's binary_logloss: 0.974948
[1040]	valid_0's binary_logloss: 0.975592
[1041]	valid_0's binary_logloss: 0.974132
[1042]	valid_0's binary_logloss: 0.975681
[1043]	valid_0's binary_logloss: 0.979017
[1044]	valid_0's binary_logloss: 0.980097
[1045]	valid_0's binary_logloss: 0.979907
[1046]	valid_0's binary_logloss: 0.979556
[1047]	valid_0's binary_logloss: 0.982165
[1048]	valid_0's binary_logloss: 0.982104
[1049]	valid_0's binary_logloss: 0.981997
[1050]	valid_0's binary_logloss: 0.982026
[1051]	valid_0's binary_logloss: 0.981971
[1052]	valid_0's binary_logloss: 0.983602
[1053]	valid_0's binary_logloss: 0.984934
[1054]	valid_0's binary_logloss: 0.983833
[1055]	valid_0's binary_logloss: 0

[1489]	valid_0's binary_logloss: 1.15533
[1490]	valid_0's binary_logloss: 1.1552
[1491]	valid_0's binary_logloss: 1.15511
[1492]	valid_0's binary_logloss: 1.15543
[1493]	valid_0's binary_logloss: 1.15573
[1494]	valid_0's binary_logloss: 1.15579
[1495]	valid_0's binary_logloss: 1.15547
[1496]	valid_0's binary_logloss: 1.15466
[1497]	valid_0's binary_logloss: 1.15461
[1498]	valid_0's binary_logloss: 1.15475
[1499]	valid_0's binary_logloss: 1.15415
[1500]	valid_0's binary_logloss: 1.15369
[1501]	valid_0's binary_logloss: 1.15395
[1502]	valid_0's binary_logloss: 1.15385
[1503]	valid_0's binary_logloss: 1.15378
[1504]	valid_0's binary_logloss: 1.15458
[1505]	valid_0's binary_logloss: 1.15489
[1506]	valid_0's binary_logloss: 1.15471
[1507]	valid_0's binary_logloss: 1.15629
[1508]	valid_0's binary_logloss: 1.15744
[1509]	valid_0's binary_logloss: 1.15752
[1510]	valid_0's binary_logloss: 1.15863
[1511]	valid_0's binary_logloss: 1.15929
[1512]	valid_0's binary_logloss: 1.15911
[1513]	valid_0's 

[286]	valid_0's binary_logloss: 0.624594
[287]	valid_0's binary_logloss: 0.625279
[288]	valid_0's binary_logloss: 0.625387
[289]	valid_0's binary_logloss: 0.625648
[290]	valid_0's binary_logloss: 0.625227
[291]	valid_0's binary_logloss: 0.62616
[292]	valid_0's binary_logloss: 0.62627
[293]	valid_0's binary_logloss: 0.628973
[294]	valid_0's binary_logloss: 0.63073
[295]	valid_0's binary_logloss: 0.632203
[296]	valid_0's binary_logloss: 0.631847
[297]	valid_0's binary_logloss: 0.629549
[298]	valid_0's binary_logloss: 0.632458
[299]	valid_0's binary_logloss: 0.635631
[300]	valid_0's binary_logloss: 0.638542
[301]	valid_0's binary_logloss: 0.640976
[302]	valid_0's binary_logloss: 0.640072
[303]	valid_0's binary_logloss: 0.639036
[304]	valid_0's binary_logloss: 0.639428
[305]	valid_0's binary_logloss: 0.638075
[306]	valid_0's binary_logloss: 0.639887
[307]	valid_0's binary_logloss: 0.641934
[308]	valid_0's binary_logloss: 0.642393
[309]	valid_0's binary_logloss: 0.643971
[310]	valid_0's bin

[635]	valid_0's binary_logloss: 0.861683
[636]	valid_0's binary_logloss: 0.862876
[637]	valid_0's binary_logloss: 0.863783
[638]	valid_0's binary_logloss: 0.86529
[639]	valid_0's binary_logloss: 0.865584
[640]	valid_0's binary_logloss: 0.865776
[641]	valid_0's binary_logloss: 0.867688
[642]	valid_0's binary_logloss: 0.867558
[643]	valid_0's binary_logloss: 0.867423
[644]	valid_0's binary_logloss: 0.867499
[645]	valid_0's binary_logloss: 0.870009
[646]	valid_0's binary_logloss: 0.869537
[647]	valid_0's binary_logloss: 0.868983
[648]	valid_0's binary_logloss: 0.870232
[649]	valid_0's binary_logloss: 0.871444
[650]	valid_0's binary_logloss: 0.872749
[651]	valid_0's binary_logloss: 0.870184
[652]	valid_0's binary_logloss: 0.87094
[653]	valid_0's binary_logloss: 0.871767
[654]	valid_0's binary_logloss: 0.871131
[655]	valid_0's binary_logloss: 0.874638
[656]	valid_0's binary_logloss: 0.875985
[657]	valid_0's binary_logloss: 0.877524
[658]	valid_0's binary_logloss: 0.879676
[659]	valid_0's bi

[983]	valid_0's binary_logloss: 1.07179
[984]	valid_0's binary_logloss: 1.07299
[985]	valid_0's binary_logloss: 1.07331
[986]	valid_0's binary_logloss: 1.07294
[987]	valid_0's binary_logloss: 1.07272
[988]	valid_0's binary_logloss: 1.07447
[989]	valid_0's binary_logloss: 1.0729
[990]	valid_0's binary_logloss: 1.07299
[991]	valid_0's binary_logloss: 1.07379
[992]	valid_0's binary_logloss: 1.07441
[993]	valid_0's binary_logloss: 1.07514
[994]	valid_0's binary_logloss: 1.07666
[995]	valid_0's binary_logloss: 1.07612
[996]	valid_0's binary_logloss: 1.07633
[997]	valid_0's binary_logloss: 1.07592
[998]	valid_0's binary_logloss: 1.07704
[999]	valid_0's binary_logloss: 1.07759
[1000]	valid_0's binary_logloss: 1.07773
[1001]	valid_0's binary_logloss: 1.08105
[1002]	valid_0's binary_logloss: 1.08175
[1003]	valid_0's binary_logloss: 1.08309
[1004]	valid_0's binary_logloss: 1.08311
[1005]	valid_0's binary_logloss: 1.08315
[1006]	valid_0's binary_logloss: 1.08357
[1007]	valid_0's binary_logloss: 1

[1327]	valid_0's binary_logloss: 1.2034
[1328]	valid_0's binary_logloss: 1.20338
[1329]	valid_0's binary_logloss: 1.20325
[1330]	valid_0's binary_logloss: 1.20323
[1331]	valid_0's binary_logloss: 1.20331
[1332]	valid_0's binary_logloss: 1.20374
[1333]	valid_0's binary_logloss: 1.20375
[1334]	valid_0's binary_logloss: 1.20362
[1335]	valid_0's binary_logloss: 1.20425
[1336]	valid_0's binary_logloss: 1.20381
[1337]	valid_0's binary_logloss: 1.20347
[1338]	valid_0's binary_logloss: 1.20393
[1339]	valid_0's binary_logloss: 1.204
[1340]	valid_0's binary_logloss: 1.20397
[1341]	valid_0's binary_logloss: 1.2051
[1342]	valid_0's binary_logloss: 1.20508
[1343]	valid_0's binary_logloss: 1.20719
[1344]	valid_0's binary_logloss: 1.20658
[1345]	valid_0's binary_logloss: 1.20636
[1346]	valid_0's binary_logloss: 1.20643
[1347]	valid_0's binary_logloss: 1.20619
[1348]	valid_0's binary_logloss: 1.20763
[1349]	valid_0's binary_logloss: 1.20762
[1350]	valid_0's binary_logloss: 1.20767
[1351]	valid_0's bin

[112]	valid_0's binary_logloss: 0.660849
[113]	valid_0's binary_logloss: 0.660577
[114]	valid_0's binary_logloss: 0.660296
[115]	valid_0's binary_logloss: 0.660019
[116]	valid_0's binary_logloss: 0.659765
[117]	valid_0's binary_logloss: 0.659491
[118]	valid_0's binary_logloss: 0.659245
[119]	valid_0's binary_logloss: 0.658946
[120]	valid_0's binary_logloss: 0.658688
[121]	valid_0's binary_logloss: 0.658391
[122]	valid_0's binary_logloss: 0.658126
[123]	valid_0's binary_logloss: 0.657834
[124]	valid_0's binary_logloss: 0.657542
[125]	valid_0's binary_logloss: 0.657279
[126]	valid_0's binary_logloss: 0.657006
[127]	valid_0's binary_logloss: 0.65673
[128]	valid_0's binary_logloss: 0.656437
[129]	valid_0's binary_logloss: 0.656169
[130]	valid_0's binary_logloss: 0.65588
[131]	valid_0's binary_logloss: 0.655606
[132]	valid_0's binary_logloss: 0.655337
[133]	valid_0's binary_logloss: 0.655049
[134]	valid_0's binary_logloss: 0.654781
[135]	valid_0's binary_logloss: 0.654509
[136]	valid_0's bi

[342]	valid_0's binary_logloss: 0.605367
[343]	valid_0's binary_logloss: 0.605162
[344]	valid_0's binary_logloss: 0.604935
[345]	valid_0's binary_logloss: 0.60475
[346]	valid_0's binary_logloss: 0.604522
[347]	valid_0's binary_logloss: 0.604324
[348]	valid_0's binary_logloss: 0.604122
[349]	valid_0's binary_logloss: 0.603916
[350]	valid_0's binary_logloss: 0.603717
[351]	valid_0's binary_logloss: 0.603538
[352]	valid_0's binary_logloss: 0.603335
[353]	valid_0's binary_logloss: 0.603126
[354]	valid_0's binary_logloss: 0.602914
[355]	valid_0's binary_logloss: 0.602717
[356]	valid_0's binary_logloss: 0.60251
[357]	valid_0's binary_logloss: 0.602315
[358]	valid_0's binary_logloss: 0.602117
[359]	valid_0's binary_logloss: 0.60191
[360]	valid_0's binary_logloss: 0.601705
[361]	valid_0's binary_logloss: 0.601517
[362]	valid_0's binary_logloss: 0.601311
[363]	valid_0's binary_logloss: 0.601096
[364]	valid_0's binary_logloss: 0.6009
[365]	valid_0's binary_logloss: 0.600705
[366]	valid_0's binar

[568]	valid_0's binary_logloss: 0.565542
[569]	valid_0's binary_logloss: 0.565384
[570]	valid_0's binary_logloss: 0.565226
[571]	valid_0's binary_logloss: 0.56505
[572]	valid_0's binary_logloss: 0.564904
[573]	valid_0's binary_logloss: 0.564747
[574]	valid_0's binary_logloss: 0.564564
[575]	valid_0's binary_logloss: 0.564415
[576]	valid_0's binary_logloss: 0.564245
[577]	valid_0's binary_logloss: 0.564083
[578]	valid_0's binary_logloss: 0.563929
[579]	valid_0's binary_logloss: 0.563773
[580]	valid_0's binary_logloss: 0.563604
[581]	valid_0's binary_logloss: 0.563433
[582]	valid_0's binary_logloss: 0.563289
[583]	valid_0's binary_logloss: 0.563118
[584]	valid_0's binary_logloss: 0.562953
[585]	valid_0's binary_logloss: 0.56279
[586]	valid_0's binary_logloss: 0.562643
[587]	valid_0's binary_logloss: 0.562502
[588]	valid_0's binary_logloss: 0.562326
[589]	valid_0's binary_logloss: 0.562184
[590]	valid_0's binary_logloss: 0.562024
[591]	valid_0's binary_logloss: 0.561853
[592]	valid_0's bi

[802]	valid_0's binary_logloss: 0.537068
[803]	valid_0's binary_logloss: 0.536988
[804]	valid_0's binary_logloss: 0.536907
[805]	valid_0's binary_logloss: 0.536814
[806]	valid_0's binary_logloss: 0.536727
[807]	valid_0's binary_logloss: 0.536639
[808]	valid_0's binary_logloss: 0.536559
[809]	valid_0's binary_logloss: 0.536491
[810]	valid_0's binary_logloss: 0.536413
[811]	valid_0's binary_logloss: 0.536295
[812]	valid_0's binary_logloss: 0.536202
[813]	valid_0's binary_logloss: 0.536107
[814]	valid_0's binary_logloss: 0.536008
[815]	valid_0's binary_logloss: 0.53589
[816]	valid_0's binary_logloss: 0.535812
[817]	valid_0's binary_logloss: 0.535738
[818]	valid_0's binary_logloss: 0.535658
[819]	valid_0's binary_logloss: 0.535549
[820]	valid_0's binary_logloss: 0.535459
[821]	valid_0's binary_logloss: 0.535351
[822]	valid_0's binary_logloss: 0.535274
[823]	valid_0's binary_logloss: 0.535188
[824]	valid_0's binary_logloss: 0.535108
[825]	valid_0's binary_logloss: 0.534995
[826]	valid_0's b

[1018]	valid_0's binary_logloss: 0.521348
[1019]	valid_0's binary_logloss: 0.521278
[1020]	valid_0's binary_logloss: 0.521202
[1021]	valid_0's binary_logloss: 0.521162
[1022]	valid_0's binary_logloss: 0.521096
[1023]	valid_0's binary_logloss: 0.521027
[1024]	valid_0's binary_logloss: 0.520958
[1025]	valid_0's binary_logloss: 0.520918
[1026]	valid_0's binary_logloss: 0.520878
[1027]	valid_0's binary_logloss: 0.520813
[1028]	valid_0's binary_logloss: 0.520742
[1029]	valid_0's binary_logloss: 0.520685
[1030]	valid_0's binary_logloss: 0.520616
[1031]	valid_0's binary_logloss: 0.520549
[1032]	valid_0's binary_logloss: 0.520479
[1033]	valid_0's binary_logloss: 0.520419
[1034]	valid_0's binary_logloss: 0.520346
[1035]	valid_0's binary_logloss: 0.520306
[1036]	valid_0's binary_logloss: 0.520237
[1037]	valid_0's binary_logloss: 0.520208
[1038]	valid_0's binary_logloss: 0.520138
[1039]	valid_0's binary_logloss: 0.520073
[1040]	valid_0's binary_logloss: 0.52004
[1041]	valid_0's binary_logloss: 0.

[1234]	valid_0's binary_logloss: 0.510054
[1235]	valid_0's binary_logloss: 0.510013
[1236]	valid_0's binary_logloss: 0.509949
[1237]	valid_0's binary_logloss: 0.509886
[1238]	valid_0's binary_logloss: 0.509823
[1239]	valid_0's binary_logloss: 0.509759
[1240]	valid_0's binary_logloss: 0.509696
[1241]	valid_0's binary_logloss: 0.509634
[1242]	valid_0's binary_logloss: 0.509593
[1243]	valid_0's binary_logloss: 0.509531
[1244]	valid_0's binary_logloss: 0.509472
[1245]	valid_0's binary_logloss: 0.509413
[1246]	valid_0's binary_logloss: 0.509351
[1247]	valid_0's binary_logloss: 0.509292
[1248]	valid_0's binary_logloss: 0.509234
[1249]	valid_0's binary_logloss: 0.509176
[1250]	valid_0's binary_logloss: 0.509117
[1251]	valid_0's binary_logloss: 0.509056
[1252]	valid_0's binary_logloss: 0.509001
[1253]	valid_0's binary_logloss: 0.508944
[1254]	valid_0's binary_logloss: 0.508889
[1255]	valid_0's binary_logloss: 0.508829
[1256]	valid_0's binary_logloss: 0.50879
[1257]	valid_0's binary_logloss: 0.

[1483]	valid_0's binary_logloss: 0.503122
[1484]	valid_0's binary_logloss: 0.503109
[1485]	valid_0's binary_logloss: 0.503084
[1486]	valid_0's binary_logloss: 0.503059
[1487]	valid_0's binary_logloss: 0.503055
[1488]	valid_0's binary_logloss: 0.503043
[1489]	valid_0's binary_logloss: 0.503018
[1490]	valid_0's binary_logloss: 0.502994
[1491]	valid_0's binary_logloss: 0.502986
[1492]	valid_0's binary_logloss: 0.502961
[1493]	valid_0's binary_logloss: 0.502937
[1494]	valid_0's binary_logloss: 0.502934
[1495]	valid_0's binary_logloss: 0.502926
[1496]	valid_0's binary_logloss: 0.502901
[1497]	valid_0's binary_logloss: 0.502881
[1498]	valid_0's binary_logloss: 0.502897
[1499]	valid_0's binary_logloss: 0.502886
[1500]	valid_0's binary_logloss: 0.50288
[1501]	valid_0's binary_logloss: 0.502861
[1502]	valid_0's binary_logloss: 0.502845
[1503]	valid_0's binary_logloss: 0.502839
[1504]	valid_0's binary_logloss: 0.502832
[1505]	valid_0's binary_logloss: 0.502809
[1506]	valid_0's binary_logloss: 0.

[230]	valid_0's binary_logloss: 0.914137
[231]	valid_0's binary_logloss: 0.921856
[232]	valid_0's binary_logloss: 0.920074
[233]	valid_0's binary_logloss: 0.922985
[234]	valid_0's binary_logloss: 0.923947
[235]	valid_0's binary_logloss: 0.927604
[236]	valid_0's binary_logloss: 0.927462
[237]	valid_0's binary_logloss: 0.93114
[238]	valid_0's binary_logloss: 0.931895
[239]	valid_0's binary_logloss: 0.932578
[240]	valid_0's binary_logloss: 0.932749
[241]	valid_0's binary_logloss: 0.933975
[242]	valid_0's binary_logloss: 0.9346
[243]	valid_0's binary_logloss: 0.936094
[244]	valid_0's binary_logloss: 0.937952
[245]	valid_0's binary_logloss: 0.940791
[246]	valid_0's binary_logloss: 0.939967
[247]	valid_0's binary_logloss: 0.939241
[248]	valid_0's binary_logloss: 0.9395
[249]	valid_0's binary_logloss: 0.93903
[250]	valid_0's binary_logloss: 0.939326
[251]	valid_0's binary_logloss: 0.941505
[252]	valid_0's binary_logloss: 0.942386
[253]	valid_0's binary_logloss: 0.944161
[254]	valid_0's binary

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.649568
[2]	valid_0's binary_logloss: 0.619209
[3]	valid_0's binary_logloss: 0.592349
[4]	valid_0's binary_logloss: 0.573391
[5]	valid_0's binary_logloss: 0.554443
[6]	valid_0's binary_logloss: 0.547073
[7]	valid_0's binary_logloss: 0.529374
[8]	valid_0's binary_logloss: 0.5228
[9]	valid_0's binary_logloss: 0.515726
[10]	valid_0's binary_logloss: 0.505907
[11]	valid_0's binary_logloss: 0.503947
[12]	valid_0's binary_logloss: 0.496387
[13]	valid_0's binary_logloss: 0.494524
[14]	valid_0's binary_logloss: 0.488686
[15]	valid_0's binary_logloss: 0.487562
[16]	valid_0's binary_logloss: 0.482823
[17]	valid_0's binary_logloss: 0.477289
[18]	valid_0's binary_logloss: 0.475014
[19]	valid_0's binary_logloss: 0.46325
[20]	valid_0's binary_logloss: 0.464249
[21]	valid_0's binary_logloss: 0.466403
[22]	valid_0's binary_logloss: 0.468284
[23]	valid_0's binary_logloss: 0.470497
[24]	valid_0's binary_logloss: 0.469085


[206]	valid_0's binary_logloss: 0.716172
[207]	valid_0's binary_logloss: 0.717723
[208]	valid_0's binary_logloss: 0.71975
[209]	valid_0's binary_logloss: 0.720451
[210]	valid_0's binary_logloss: 0.721473
[211]	valid_0's binary_logloss: 0.725061
[212]	valid_0's binary_logloss: 0.725182
[213]	valid_0's binary_logloss: 0.724468
[214]	valid_0's binary_logloss: 0.728148
[215]	valid_0's binary_logloss: 0.730268
[216]	valid_0's binary_logloss: 0.73343
[217]	valid_0's binary_logloss: 0.735556
[218]	valid_0's binary_logloss: 0.737208
[219]	valid_0's binary_logloss: 0.736119
[220]	valid_0's binary_logloss: 0.73751
[221]	valid_0's binary_logloss: 0.740554
[222]	valid_0's binary_logloss: 0.741767
[223]	valid_0's binary_logloss: 0.741655
[224]	valid_0's binary_logloss: 0.741477
[225]	valid_0's binary_logloss: 0.742328
[226]	valid_0's binary_logloss: 0.742963
[227]	valid_0's binary_logloss: 0.745606
[228]	valid_0's binary_logloss: 0.745794
[229]	valid_0's binary_logloss: 0.74786
[230]	valid_0's bina

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.66778
[2]	valid_0's binary_logloss: 0.642146
[3]	valid_0's binary_logloss: 0.621256
[4]	valid_0's binary_logloss: 0.599492
[5]	valid_0's binary_logloss: 0.581977
[6]	valid_0's binary_logloss: 0.567296
[7]	valid_0's binary_logloss: 0.553643
[8]	valid_0's binary_logloss: 0.541422
[9]	valid_0's binary_logloss: 0.530767
[10]	valid_0's binary_logloss: 0.521035
[11]	valid_0's binary_logloss: 0.519346
[12]	valid_0's binary_logloss: 0.511872
[13]	valid_0's binary_logloss: 0.507381
[14]	valid_0's binary_logloss: 0.503873
[15]	valid_0's binary_logloss: 0.498862
[16]	valid_0's binary_logloss: 0.497858
[17]	valid_0's binary_logloss: 0.493615
[18]	valid_0's binary_logloss: 0.492352
[19]	valid_0's binary_logloss: 0.49176
[20]	valid_0's binary_logloss: 0.491856
[21]	valid_0's binary_logloss: 0.488386
[22]	valid_0's binary_logloss: 0.488879
[23]	valid_0's binary_logloss: 0.487865
[24]	valid_0's binary_logloss: 0.487872

[227]	valid_0's binary_logloss: 0.72535
[228]	valid_0's binary_logloss: 0.726642
[229]	valid_0's binary_logloss: 0.72727
[230]	valid_0's binary_logloss: 0.731482
[231]	valid_0's binary_logloss: 0.732277
[232]	valid_0's binary_logloss: 0.734311
[233]	valid_0's binary_logloss: 0.736027
[234]	valid_0's binary_logloss: 0.738747
[235]	valid_0's binary_logloss: 0.740031
[236]	valid_0's binary_logloss: 0.740994
[237]	valid_0's binary_logloss: 0.743448
[238]	valid_0's binary_logloss: 0.742808
[239]	valid_0's binary_logloss: 0.743284
[240]	valid_0's binary_logloss: 0.745055
[241]	valid_0's binary_logloss: 0.746583
[242]	valid_0's binary_logloss: 0.746451
[243]	valid_0's binary_logloss: 0.745739
[244]	valid_0's binary_logloss: 0.746541
[245]	valid_0's binary_logloss: 0.747987
[246]	valid_0's binary_logloss: 0.749728
[247]	valid_0's binary_logloss: 0.750176
[248]	valid_0's binary_logloss: 0.751616
[249]	valid_0's binary_logloss: 0.754563
[250]	valid_0's binary_logloss: 0.75658
[251]	valid_0's bin

[1]	valid_0's binary_logloss: 0.670879
[2]	valid_0's binary_logloss: 0.650053
[3]	valid_0's binary_logloss: 0.638573
[4]	valid_0's binary_logloss: 0.619243
[5]	valid_0's binary_logloss: 0.608425
[6]	valid_0's binary_logloss: 0.59569
[7]	valid_0's binary_logloss: 0.585414
[8]	valid_0's binary_logloss: 0.574733
[9]	valid_0's binary_logloss: 0.568244
[10]	valid_0's binary_logloss: 0.56316
[11]	valid_0's binary_logloss: 0.549008
[12]	valid_0's binary_logloss: 0.549563
[13]	valid_0's binary_logloss: 0.551961
[14]	valid_0's binary_logloss: 0.542353
[15]	valid_0's binary_logloss: 0.544165
[16]	valid_0's binary_logloss: 0.538936
[17]	valid_0's binary_logloss: 0.536203
[18]	valid_0's binary_logloss: 0.531805
[19]	valid_0's binary_logloss: 0.530576
[20]	valid_0's binary_logloss: 0.526603
[21]	valid_0's binary_logloss: 0.529773
[22]	valid_0's binary_logloss: 0.527139
[23]	valid_0's binary_logloss: 0.523998
[24]	valid_0's binary_logloss: 0.522428
[25]	valid_0's binary_logloss: 0.525732
[26]	valid_

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.637912
[2]	valid_0's binary_logloss: 0.599266
[3]	valid_0's binary_logloss: 0.562343
[4]	valid_0's binary_logloss: 0.54816
[5]	valid_0's binary_logloss: 0.530394
[6]	valid_0's binary_logloss: 0.530394
[7]	valid_0's binary_logloss: 0.517463
[8]	valid_0's binary_logloss: 0.508869
[9]	valid_0's binary_logloss: 0.515671
[10]	valid_0's binary_logloss: 0.511871
[11]	valid_0's binary_logloss: 0.503723
[12]	valid_0's binary_logloss: 0.496633
[13]	valid_0's binary_logloss: 0.491934
[14]	valid_0's binary_logloss: 0.492087
[15]	valid_0's binary_logloss: 0.486152
[16]	valid_0's binary_logloss: 0.490584
[17]	valid_0's binary_logloss: 0.486853
[18]	valid_0's binary_logloss: 0.49106
[19]	valid_0's binary_logloss: 0.497704
[20]	valid_0's binary_logloss: 0.499436
[21]	valid_0's binary_logloss: 0.489957
[22]	valid_0's binary_logloss: 0.488632
[23]	valid_0's binary_logloss: 0.489118
[24]	valid_0's binary_logloss: 0.490138

[235]	valid_0's binary_logloss: 0.808317
[236]	valid_0's binary_logloss: 0.810408
[237]	valid_0's binary_logloss: 0.811799
[238]	valid_0's binary_logloss: 0.813966
[239]	valid_0's binary_logloss: 0.815277
[240]	valid_0's binary_logloss: 0.817508
[241]	valid_0's binary_logloss: 0.822364
[242]	valid_0's binary_logloss: 0.823622
[243]	valid_0's binary_logloss: 0.822379
[244]	valid_0's binary_logloss: 0.826967
[245]	valid_0's binary_logloss: 0.830747
[246]	valid_0's binary_logloss: 0.835798
[247]	valid_0's binary_logloss: 0.837572
[248]	valid_0's binary_logloss: 0.838439
[249]	valid_0's binary_logloss: 0.838439
[250]	valid_0's binary_logloss: 0.845595
[251]	valid_0's binary_logloss: 0.843647
[252]	valid_0's binary_logloss: 0.845821
[253]	valid_0's binary_logloss: 0.84795
[254]	valid_0's binary_logloss: 0.848777
[255]	valid_0's binary_logloss: 0.850968
[256]	valid_0's binary_logloss: 0.85129
[257]	valid_0's binary_logloss: 0.855503
[258]	valid_0's binary_logloss: 0.85848
[259]	valid_0's bin

[530]	valid_0's binary_logloss: 1.1348
[531]	valid_0's binary_logloss: 1.13463
[532]	valid_0's binary_logloss: 1.13615
[533]	valid_0's binary_logloss: 1.13623
[534]	valid_0's binary_logloss: 1.1363
[535]	valid_0's binary_logloss: 1.13742
[536]	valid_0's binary_logloss: 1.13819
[537]	valid_0's binary_logloss: 1.138
[538]	valid_0's binary_logloss: 1.13636
[539]	valid_0's binary_logloss: 1.13608
[540]	valid_0's binary_logloss: 1.13761
[541]	valid_0's binary_logloss: 1.13822
[542]	valid_0's binary_logloss: 1.13863
[543]	valid_0's binary_logloss: 1.13634
[544]	valid_0's binary_logloss: 1.13658
[545]	valid_0's binary_logloss: 1.13896
[546]	valid_0's binary_logloss: 1.14199
[547]	valid_0's binary_logloss: 1.14322
[548]	valid_0's binary_logloss: 1.14291
[549]	valid_0's binary_logloss: 1.14726
[550]	valid_0's binary_logloss: 1.15339
[551]	valid_0's binary_logloss: 1.15356
[552]	valid_0's binary_logloss: 1.1532
[553]	valid_0's binary_logloss: 1.15886
[554]	valid_0's binary_logloss: 1.15887
[555]

[828]	valid_0's binary_logloss: 1.23519
[829]	valid_0's binary_logloss: 1.23551
[830]	valid_0's binary_logloss: 1.23538
[831]	valid_0's binary_logloss: 1.2354
[832]	valid_0's binary_logloss: 1.23553
[833]	valid_0's binary_logloss: 1.23562
[834]	valid_0's binary_logloss: 1.23507
[835]	valid_0's binary_logloss: 1.23502
[836]	valid_0's binary_logloss: 1.23413
[837]	valid_0's binary_logloss: 1.23425
[838]	valid_0's binary_logloss: 1.23385
[839]	valid_0's binary_logloss: 1.23407
[840]	valid_0's binary_logloss: 1.23441
[841]	valid_0's binary_logloss: 1.23457
[842]	valid_0's binary_logloss: 1.23459
[843]	valid_0's binary_logloss: 1.23378
[844]	valid_0's binary_logloss: 1.23398
[845]	valid_0's binary_logloss: 1.2339
[846]	valid_0's binary_logloss: 1.23403
[847]	valid_0's binary_logloss: 1.23403
[848]	valid_0's binary_logloss: 1.23416
[849]	valid_0's binary_logloss: 1.23431
[850]	valid_0's binary_logloss: 1.2343
[851]	valid_0's binary_logloss: 1.23244
[852]	valid_0's binary_logloss: 1.23252
[85

[198]	valid_0's binary_logloss: 0.560708
[199]	valid_0's binary_logloss: 0.561718
[200]	valid_0's binary_logloss: 0.563868
[201]	valid_0's binary_logloss: 0.563783
[202]	valid_0's binary_logloss: 0.563096
[203]	valid_0's binary_logloss: 0.564236
[204]	valid_0's binary_logloss: 0.564548
[205]	valid_0's binary_logloss: 0.565649
[206]	valid_0's binary_logloss: 0.566211
[207]	valid_0's binary_logloss: 0.56504
[208]	valid_0's binary_logloss: 0.566291
[209]	valid_0's binary_logloss: 0.566676
[210]	valid_0's binary_logloss: 0.567841
[211]	valid_0's binary_logloss: 0.566814
[212]	valid_0's binary_logloss: 0.56839
[213]	valid_0's binary_logloss: 0.568764
[214]	valid_0's binary_logloss: 0.570026
[215]	valid_0's binary_logloss: 0.57069
[216]	valid_0's binary_logloss: 0.570808
[217]	valid_0's binary_logloss: 0.571269
[218]	valid_0's binary_logloss: 0.571829
[219]	valid_0's binary_logloss: 0.573639
[220]	valid_0's binary_logloss: 0.573868
[221]	valid_0's binary_logloss: 0.574371
[222]	valid_0's bin

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.668019
[2]	valid_0's binary_logloss: 0.645116
[3]	valid_0's binary_logloss: 0.633457
[4]	valid_0's binary_logloss: 0.612154
[5]	valid_0's binary_logloss: 0.598636
[6]	valid_0's binary_logloss: 0.585515
[7]	valid_0's binary_logloss: 0.573943
[8]	valid_0's binary_logloss: 0.563056
[9]	valid_0's binary_logloss: 0.550938
[10]	valid_0's binary_logloss: 0.553691
[11]	valid_0's binary_logloss: 0.548833
[12]	valid_0's binary_logloss: 0.541859
[13]	valid_0's binary_logloss: 0.536954
[14]	valid_0's binary_logloss: 0.529189
[15]	valid_0's binary_logloss: 0.529813
[16]	valid_0's binary_logloss: 0.531995
[17]	valid_0's binary_logloss: 0.524507
[18]	valid_0's binary_logloss: 0.521097
[19]	valid_0's binary_logloss: 0.524273
[20]	valid_0's binary_logloss: 0.51745
[21]	valid_0's binary_logloss: 0.517341
[22]	valid_0's binary_logloss: 0.518519
[23]	valid_0's binary_logloss: 0.514586
[24]	valid_0's binary_logloss: 0.51361

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.627428
[2]	valid_0's binary_logloss: 0.585637
[3]	valid_0's binary_logloss: 0.555341
[4]	valid_0's binary_logloss: 0.534821
[5]	valid_0's binary_logloss: 0.524669
[6]	valid_0's binary_logloss: 0.513383
[7]	valid_0's binary_logloss: 0.510073
[8]	valid_0's binary_logloss: 0.504965
[9]	valid_0's binary_logloss: 0.505768
[10]	valid_0's binary_logloss: 0.508527
[11]	valid_0's binary_logloss: 0.51035
[12]	valid_0's binary_logloss: 0.498625
[13]	valid_0's binary_logloss: 0.491082
[14]	valid_0's binary_logloss: 0.487289
[15]	valid_0's binary_logloss: 0.49454
[16]	valid_0's binary_logloss: 0.498823
[17]	valid_0's binary_logloss: 0.494896
[18]	valid_0's binary_logloss: 0.504964
[19]	valid_0's binary_logloss: 0.508003
[20]	valid_0's binary_logloss: 0.511993
[21]	valid_0's binary_logloss: 0.520742
[22]	valid_0's binary_logloss: 0.52764
[23]	valid_0's binary_logloss: 0.535187
[24]	valid_0's binary_logloss: 0.535298


[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.684147
[2]	valid_0's binary_logloss: 0.674859
[3]	valid_0's binary_logloss: 0.665294
[4]	valid_0's binary_logloss: 0.656798
[5]	valid_0's binary_logloss: 0.64824
[6]	valid_0's binary_logloss: 0.640765
[7]	valid_0's binary_logloss: 0.632949
[8]	valid_0's binary_logloss: 0.625218
[9]	valid_0's binary_logloss: 0.618423
[10]	valid_0's binary_logloss: 0.611196
[11]	valid_0's binary_logloss: 0.605543
[12]	valid_0's binary_logloss: 0.598731
[13]	valid_0's binary_logloss: 0.592715
[14]	valid_0's binary_logloss: 0.587017
[15]	valid_0's binary_logloss: 0.58187
[16]	valid_0's binary_logloss: 0.576003
[17]	valid_0's binary_logloss: 0.57077
[18]	valid_0's binary_logloss: 0.56637
[19]	valid_0's binary_logloss: 0.561717
[20]	valid_0's binary_logloss: 0.557157
[21]	valid_0's binary_logloss: 0.552684
[22]	valid_0's binary_logloss: 0.549205
[23]	valid_0's binary_logloss: 0.5455
[24]	valid_0's binary_logloss: 0.542606
[25

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.693139
[2]	valid_0's binary_logloss: 0.693019
[3]	valid_0's binary_logloss: 0.692899
[4]	valid_0's binary_logloss: 0.692779
[5]	valid_0's binary_logloss: 0.69266
[6]	valid_0's binary_logloss: 0.69254
[7]	valid_0's binary_logloss: 0.692421
[8]	valid_0's binary_logloss: 0.692303
[9]	valid_0's binary_logloss: 0.692184
[10]	valid_0's binary_logloss: 0.692066
[11]	valid_0's binary_logloss: 0.691948
[12]	valid_0's binary_logloss: 0.69183
[13]	valid_0's binary_logloss: 0.691713
[14]	valid_0's binary_logloss: 0.691596
[15]	valid_0's binary_logloss: 0.691479
[16]	valid_0's binary_logloss: 0.691362
[17]	valid_0's binary_logloss: 0.691246
[18]	valid_0's binary_logloss: 0.69113
[19]	valid_0's binary_logloss: 0.691014
[20]	valid_0's binary_logloss: 0.690899
[21]	valid_0's binary_logloss: 0.690783
[22]	valid_0's binary_logloss: 0.690668
[23]	valid_0's binary_logloss: 0.690553
[24]	valid_0's binary_logloss: 0.690439
[

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.69215
[2]	valid_0's binary_logloss: 0.691062
[3]	valid_0's binary_logloss: 0.689997
[4]	valid_0's binary_logloss: 0.688954
[5]	valid_0's binary_logloss: 0.687932
[6]	valid_0's binary_logloss: 0.686931
[7]	valid_0's binary_logloss: 0.68595
[8]	valid_0's binary_logloss: 0.684989
[9]	valid_0's binary_logloss: 0.684099
[10]	valid_0's binary_logloss: 0.683171
[11]	valid_0's binary_logloss: 0.682315
[12]	valid_0's binary_logloss: 0.681418
[13]	valid_0's binary_logloss: 0.680594
[14]	valid_0's binary_logloss: 0.679632
[15]	valid_0's binary_logloss: 0.67884
[16]	valid_0's binary_logloss: 0.677744
[17]	valid_0's binary_logloss: 0.676668
[18]	valid_0's binary_logloss: 0.67591
[19]	valid_0's binary_logloss: 0.674862
[20]	valid_0's binary_logloss: 0.673832
[21]	valid_0's binary_logloss: 0.67282
[22]	valid_0's binary_logloss: 0.672101
[23]	valid_0's binary_logloss: 0.671115
[24]	valid_0's binary_logloss: 0.670147
[2

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.680986
[2]	valid_0's binary_logloss: 0.668752
[3]	valid_0's binary_logloss: 0.655975
[4]	valid_0's binary_logloss: 0.645367
[5]	valid_0's binary_logloss: 0.634254
[6]	valid_0's binary_logloss: 0.623527
[7]	valid_0's binary_logloss: 0.614434
[8]	valid_0's binary_logloss: 0.605287
[9]	valid_0's binary_logloss: 0.596891
[10]	valid_0's binary_logloss: 0.58882
[11]	valid_0's binary_logloss: 0.581377
[12]	valid_0's binary_logloss: 0.573829
[13]	valid_0's binary_logloss: 0.567515
[14]	valid_0's binary_logloss: 0.560741
[15]	valid_0's binary_logloss: 0.554418
[16]	valid_0's binary_logloss: 0.548761
[17]	valid_0's binary_logloss: 0.544078
[18]	valid_0's binary_logloss: 0.53841
[19]	valid_0's binary_logloss: 0.534169
[20]	valid_0's binary_logloss: 0.530984
[21]	valid_0's binary_logloss: 0.528592
[22]	valid_0's binary_logloss: 0.525705
[23]	valid_0's binary_logloss: 0.521681
[24]	valid_0's binary_logloss: 0.519932

[259]	valid_0's binary_logloss: 0.5805
[260]	valid_0's binary_logloss: 0.581637
[261]	valid_0's binary_logloss: 0.582711
[262]	valid_0's binary_logloss: 0.582943
[263]	valid_0's binary_logloss: 0.583898
[264]	valid_0's binary_logloss: 0.584813
[265]	valid_0's binary_logloss: 0.586038
[266]	valid_0's binary_logloss: 0.586618
[267]	valid_0's binary_logloss: 0.587294
[268]	valid_0's binary_logloss: 0.587221
[269]	valid_0's binary_logloss: 0.58763
[270]	valid_0's binary_logloss: 0.587783
[271]	valid_0's binary_logloss: 0.588102
[272]	valid_0's binary_logloss: 0.590282
[273]	valid_0's binary_logloss: 0.590377
[274]	valid_0's binary_logloss: 0.591475
[275]	valid_0's binary_logloss: 0.59267
[276]	valid_0's binary_logloss: 0.592387
[277]	valid_0's binary_logloss: 0.593202
[278]	valid_0's binary_logloss: 0.593567
[279]	valid_0's binary_logloss: 0.594602
[280]	valid_0's binary_logloss: 0.594553
[281]	valid_0's binary_logloss: 0.595767
[282]	valid_0's binary_logloss: 0.596418
[283]	valid_0's bina

[134]	valid_0's binary_logloss: 0.992583
[135]	valid_0's binary_logloss: 0.996415
[136]	valid_0's binary_logloss: 0.99899
[137]	valid_0's binary_logloss: 0.996207
[138]	valid_0's binary_logloss: 0.997573
[139]	valid_0's binary_logloss: 0.996715
[140]	valid_0's binary_logloss: 1.00261
[141]	valid_0's binary_logloss: 1.00126
[142]	valid_0's binary_logloss: 1.00423
[143]	valid_0's binary_logloss: 1.00946
[144]	valid_0's binary_logloss: 1.01136
[145]	valid_0's binary_logloss: 1.01503
[146]	valid_0's binary_logloss: 1.02445
[147]	valid_0's binary_logloss: 1.02654
[148]	valid_0's binary_logloss: 1.02619
[149]	valid_0's binary_logloss: 1.02936
[150]	valid_0's binary_logloss: 1.03341
[151]	valid_0's binary_logloss: 1.03358
[152]	valid_0's binary_logloss: 1.03423
[153]	valid_0's binary_logloss: 1.03297
[154]	valid_0's binary_logloss: 1.03758
[155]	valid_0's binary_logloss: 1.03932
[156]	valid_0's binary_logloss: 1.04173
[157]	valid_0's binary_logloss: 1.04155
[158]	valid_0's binary_logloss: 1.0

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.684045
[2]	valid_0's binary_logloss: 0.674658
[3]	valid_0's binary_logloss: 0.664998
[4]	valid_0's binary_logloss: 0.656423
[5]	valid_0's binary_logloss: 0.64779
[6]	valid_0's binary_logloss: 0.640256
[7]	valid_0's binary_logloss: 0.632719
[8]	valid_0's binary_logloss: 0.624589
[9]	valid_0's binary_logloss: 0.617748
[10]	valid_0's binary_logloss: 0.610473
[11]	valid_0's binary_logloss: 0.604791
[12]	valid_0's binary_logloss: 0.597938
[13]	valid_0's binary_logloss: 0.591891
[14]	valid_0's binary_logloss: 0.586166
[15]	valid_0's binary_logloss: 0.580999
[16]	valid_0's binary_logloss: 0.575108
[17]	valid_0's binary_logloss: 0.569856
[18]	valid_0's binary_logloss: 0.565447
[19]	valid_0's binary_logloss: 0.560783
[20]	valid_0's binary_logloss: 0.556213
[21]	valid_0's binary_logloss: 0.551445
[22]	valid_0's binary_logloss: 0.547921
[23]	valid_0's binary_logloss: 0.544219
[24]	valid_0's binary_logloss: 0.54092

[163]	valid_0's binary_logloss: 0.714264
[164]	valid_0's binary_logloss: 0.718265
[165]	valid_0's binary_logloss: 0.723533
[166]	valid_0's binary_logloss: 0.72632
[167]	valid_0's binary_logloss: 0.723739
[168]	valid_0's binary_logloss: 0.724585
[169]	valid_0's binary_logloss: 0.726993
[170]	valid_0's binary_logloss: 0.729425
[171]	valid_0's binary_logloss: 0.732435
[172]	valid_0's binary_logloss: 0.733775
[173]	valid_0's binary_logloss: 0.737662
[174]	valid_0's binary_logloss: 0.740209
[175]	valid_0's binary_logloss: 0.746927
[176]	valid_0's binary_logloss: 0.747895
[177]	valid_0's binary_logloss: 0.752286
[178]	valid_0's binary_logloss: 0.754336
[179]	valid_0's binary_logloss: 0.757424
| 30        | 0.761     | 0.1287    | 8.098     | 179.1     |
[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.691711
[2]	valid_0's binary_logloss: 0.69019
[3]	valid_0's binary_logloss: 0.688694
[4]	valid_0's binary_logloss: 0.687064
[5]	valid_0's binary_logloss: 0.685

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.626446
[2]	valid_0's binary_logloss: 0.584519
[3]	valid_0's binary_logloss: 0.53823
[4]	valid_0's binary_logloss: 0.519456
[5]	valid_0's binary_logloss: 0.511307
[6]	valid_0's binary_logloss: 0.504292
[7]	valid_0's binary_logloss: 0.501887
[8]	valid_0's binary_logloss: 0.49753
[9]	valid_0's binary_logloss: 0.492296
[10]	valid_0's binary_logloss: 0.495113
[11]	valid_0's binary_logloss: 0.489018
[12]	valid_0's binary_logloss: 0.492609
[13]	valid_0's binary_logloss: 0.490985
[14]	valid_0's binary_logloss: 0.4968
[15]	valid_0's binary_logloss: 0.501163
[16]	valid_0's binary_logloss: 0.502333
[17]	valid_0's binary_logloss: 0.498135
[18]	valid_0's binary_logloss: 0.501238
[19]	valid_0's binary_logloss: 0.51151
[20]	valid_0's binary_logloss: 0.513795
[21]	valid_0's binary_logloss: 0.519912
[22]	valid_0's binary_logloss: 0.528172
[23]	valid_0's binary_logloss: 0.527527
[24]	valid_0's binary_logloss: 0.531942
[2

[145]	valid_0's binary_logloss: 1.03243
[146]	valid_0's binary_logloss: 1.0346
[147]	valid_0's binary_logloss: 1.03566
[148]	valid_0's binary_logloss: 1.03812
[149]	valid_0's binary_logloss: 1.04237
[150]	valid_0's binary_logloss: 1.0427
[151]	valid_0's binary_logloss: 1.04218
[152]	valid_0's binary_logloss: 1.05317
[153]	valid_0's binary_logloss: 1.05472
[154]	valid_0's binary_logloss: 1.05878
[155]	valid_0's binary_logloss: 1.05901
[156]	valid_0's binary_logloss: 1.06418
[157]	valid_0's binary_logloss: 1.0649
[158]	valid_0's binary_logloss: 1.06832
[159]	valid_0's binary_logloss: 1.06966
[160]	valid_0's binary_logloss: 1.06921
[161]	valid_0's binary_logloss: 1.07077
[162]	valid_0's binary_logloss: 1.07158
[163]	valid_0's binary_logloss: 1.07692
[164]	valid_0's binary_logloss: 1.07805
[165]	valid_0's binary_logloss: 1.07671
[166]	valid_0's binary_logloss: 1.08212
[167]	valid_0's binary_logloss: 1.08425
[168]	valid_0's binary_logloss: 1.09221
[169]	valid_0's binary_logloss: 1.09814
[17

| 35        | 0.7451    | 0.248     | 6.348     | 217.3     |
[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.681922
[2]	valid_0's binary_logloss: 0.6709
[3]	valid_0's binary_logloss: 0.661627
[4]	valid_0's binary_logloss: 0.652055
[5]	valid_0's binary_logloss: 0.644491
[6]	valid_0's binary_logloss: 0.635717
[7]	valid_0's binary_logloss: 0.62763
[8]	valid_0's binary_logloss: 0.619779
[9]	valid_0's binary_logloss: 0.612436
[10]	valid_0's binary_logloss: 0.60606
[11]	valid_0's binary_logloss: 0.599142
[12]	valid_0's binary_logloss: 0.593858
[13]	valid_0's binary_logloss: 0.588386
[14]	valid_0's binary_logloss: 0.58245
[15]	valid_0's binary_logloss: 0.577782
[16]	valid_0's binary_logloss: 0.573323
[17]	valid_0's binary_logloss: 0.56876
[18]	valid_0's binary_logloss: 0.5639
[19]	valid_0's binary_logloss: 0.560406
[20]	valid_0's binary_logloss: 0.555864
[21]	valid_0's binary_logloss: 0.552015
[22]	valid_0's binary_logloss: 0.549127
[23]	valid_0's binary_l

[224]	valid_0's binary_logloss: 0.499788
[225]	valid_0's binary_logloss: 0.500252
[226]	valid_0's binary_logloss: 0.501556
[227]	valid_0's binary_logloss: 0.501761
[228]	valid_0's binary_logloss: 0.501823
[229]	valid_0's binary_logloss: 0.501714
[230]	valid_0's binary_logloss: 0.502849
[231]	valid_0's binary_logloss: 0.503219
[232]	valid_0's binary_logloss: 0.504313
[233]	valid_0's binary_logloss: 0.506461
[234]	valid_0's binary_logloss: 0.506986
[235]	valid_0's binary_logloss: 0.506271
[236]	valid_0's binary_logloss: 0.506664
[237]	valid_0's binary_logloss: 0.506823
[238]	valid_0's binary_logloss: 0.507637
[239]	valid_0's binary_logloss: 0.508971
[240]	valid_0's binary_logloss: 0.509295
[241]	valid_0's binary_logloss: 0.510104
[242]	valid_0's binary_logloss: 0.510541
[243]	valid_0's binary_logloss: 0.510883
[244]	valid_0's binary_logloss: 0.512585
[245]	valid_0's binary_logloss: 0.513505
[246]	valid_0's binary_logloss: 0.513067
[247]	valid_0's binary_logloss: 0.512815
[248]	valid_0's 

[425]	valid_0's binary_logloss: 0.597406
[426]	valid_0's binary_logloss: 0.597916
[427]	valid_0's binary_logloss: 0.598015
[428]	valid_0's binary_logloss: 0.598383
[429]	valid_0's binary_logloss: 0.598946
[430]	valid_0's binary_logloss: 0.599331
[431]	valid_0's binary_logloss: 0.599447
[432]	valid_0's binary_logloss: 0.599166
| 36        | 0.77      | 0.03947   | 6.794     | 432.3     |
[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.68592
[2]	valid_0's binary_logloss: 0.678612
[3]	valid_0's binary_logloss: 0.673025
[4]	valid_0's binary_logloss: 0.666711
[5]	valid_0's binary_logloss: 0.661217
[6]	valid_0's binary_logloss: 0.655469
[7]	valid_0's binary_logloss: 0.650274
[8]	valid_0's binary_logloss: 0.646799
[9]	valid_0's binary_logloss: 0.643412
[10]	valid_0's binary_logloss: 0.638656
[11]	valid_0's binary_logloss: 0.633881
[12]	valid_0's binary_logloss: 0.629624
[13]	valid_0's binary_logloss: 0.625548
[14]	valid_0's binary_logloss: 0.621418
[15]	val

[425]	valid_0's binary_logloss: 0.49413
[426]	valid_0's binary_logloss: 0.494271
[427]	valid_0's binary_logloss: 0.494469
[428]	valid_0's binary_logloss: 0.494413
[429]	valid_0's binary_logloss: 0.494187
[430]	valid_0's binary_logloss: 0.494218
[431]	valid_0's binary_logloss: 0.494621
[432]	valid_0's binary_logloss: 0.494728
[433]	valid_0's binary_logloss: 0.495227
[434]	valid_0's binary_logloss: 0.495122
[435]	valid_0's binary_logloss: 0.495682
[436]	valid_0's binary_logloss: 0.495429
| 37        | 0.7513    | 0.04062   | 3.341     | 436.4     |
[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.671056
[2]	valid_0's binary_logloss: 0.653967
[3]	valid_0's binary_logloss: 0.638096
[4]	valid_0's binary_logloss: 0.622685
[5]	valid_0's binary_logloss: 0.611379
[6]	valid_0's binary_logloss: 0.600132
[7]	valid_0's binary_logloss: 0.5893
[8]	valid_0's binary_logloss: 0.581688
[9]	valid_0's binary_logloss: 0.572042
[10]	valid_0's binary_logloss: 0.56487
[11]	va

[254]	valid_0's binary_logloss: 0.615968
[255]	valid_0's binary_logloss: 0.617067
[256]	valid_0's binary_logloss: 0.616869
[257]	valid_0's binary_logloss: 0.617833
[258]	valid_0's binary_logloss: 0.618926
[259]	valid_0's binary_logloss: 0.618777
[260]	valid_0's binary_logloss: 0.619237
[261]	valid_0's binary_logloss: 0.62022
[262]	valid_0's binary_logloss: 0.621479
[263]	valid_0's binary_logloss: 0.621777
[264]	valid_0's binary_logloss: 0.62222
[265]	valid_0's binary_logloss: 0.6228
[266]	valid_0's binary_logloss: 0.623749
[267]	valid_0's binary_logloss: 0.624613
[268]	valid_0's binary_logloss: 0.624853
[269]	valid_0's binary_logloss: 0.628044
[270]	valid_0's binary_logloss: 0.627651
[271]	valid_0's binary_logloss: 0.628202
[272]	valid_0's binary_logloss: 0.628387
[273]	valid_0's binary_logloss: 0.628619
[274]	valid_0's binary_logloss: 0.629518
[275]	valid_0's binary_logloss: 0.62977
[276]	valid_0's binary_logloss: 0.631122
[277]	valid_0's binary_logloss: 0.632124
[278]	valid_0's binar

[140]	valid_0's binary_logloss: 0.955282
[141]	valid_0's binary_logloss: 0.958397
[142]	valid_0's binary_logloss: 0.9607
[143]	valid_0's binary_logloss: 0.964313
[144]	valid_0's binary_logloss: 0.966942
[145]	valid_0's binary_logloss: 0.973155
[146]	valid_0's binary_logloss: 0.974533
[147]	valid_0's binary_logloss: 0.972916
[148]	valid_0's binary_logloss: 0.978676
[149]	valid_0's binary_logloss: 0.978989
[150]	valid_0's binary_logloss: 0.97969
[151]	valid_0's binary_logloss: 0.979771
[152]	valid_0's binary_logloss: 0.981327
[153]	valid_0's binary_logloss: 0.987009
[154]	valid_0's binary_logloss: 0.987254
[155]	valid_0's binary_logloss: 0.994693
[156]	valid_0's binary_logloss: 0.994289
[157]	valid_0's binary_logloss: 0.99746
[158]	valid_0's binary_logloss: 0.999312
[159]	valid_0's binary_logloss: 0.999667
[160]	valid_0's binary_logloss: 1.00699
[161]	valid_0's binary_logloss: 1.01276
[162]	valid_0's binary_logloss: 1.01642
[163]	valid_0's binary_logloss: 1.01664
[164]	valid_0's binary_l

[476]	valid_0's binary_logloss: 1.21517
[477]	valid_0's binary_logloss: 1.21509
[478]	valid_0's binary_logloss: 1.21493
[479]	valid_0's binary_logloss: 1.21511
[480]	valid_0's binary_logloss: 1.21504
[481]	valid_0's binary_logloss: 1.21509
[482]	valid_0's binary_logloss: 1.21565
[483]	valid_0's binary_logloss: 1.21574
[484]	valid_0's binary_logloss: 1.21587
[485]	valid_0's binary_logloss: 1.22123
[486]	valid_0's binary_logloss: 1.22125
[487]	valid_0's binary_logloss: 1.22141
[488]	valid_0's binary_logloss: 1.2214
[489]	valid_0's binary_logloss: 1.22139
[490]	valid_0's binary_logloss: 1.22138
[491]	valid_0's binary_logloss: 1.22141
[492]	valid_0's binary_logloss: 1.22132
[493]	valid_0's binary_logloss: 1.22138
[494]	valid_0's binary_logloss: 1.2214
[495]	valid_0's binary_logloss: 1.2214
[496]	valid_0's binary_logloss: 1.22145
[497]	valid_0's binary_logloss: 1.22139
[498]	valid_0's binary_logloss: 1.22148
[499]	valid_0's binary_logloss: 1.22157
[500]	valid_0's binary_logloss: 1.22176
[50

[745]	valid_0's binary_logloss: 1.24407
[746]	valid_0's binary_logloss: 1.24421
[747]	valid_0's binary_logloss: 1.24429
[748]	valid_0's binary_logloss: 1.24433
[749]	valid_0's binary_logloss: 1.24435
[750]	valid_0's binary_logloss: 1.24432
[751]	valid_0's binary_logloss: 1.24451
[752]	valid_0's binary_logloss: 1.24461
[753]	valid_0's binary_logloss: 1.24331
[754]	valid_0's binary_logloss: 1.24344
[755]	valid_0's binary_logloss: 1.24351
[756]	valid_0's binary_logloss: 1.24364
[757]	valid_0's binary_logloss: 1.24372
[758]	valid_0's binary_logloss: 1.24382
[759]	valid_0's binary_logloss: 1.24382
[760]	valid_0's binary_logloss: 1.24387
[761]	valid_0's binary_logloss: 1.24392
[762]	valid_0's binary_logloss: 1.24408
[763]	valid_0's binary_logloss: 1.24426
[764]	valid_0's binary_logloss: 1.24428
[765]	valid_0's binary_logloss: 1.24433
[766]	valid_0's binary_logloss: 1.24431
[767]	valid_0's binary_logloss: 1.2444
[768]	valid_0's binary_logloss: 1.24449
[769]	valid_0's binary_logloss: 1.24449
[

[1097]	valid_0's binary_logloss: 1.26111
[1098]	valid_0's binary_logloss: 1.26121
[1099]	valid_0's binary_logloss: 1.26124
[1100]	valid_0's binary_logloss: 1.26124
[1101]	valid_0's binary_logloss: 1.26127
[1102]	valid_0's binary_logloss: 1.26131
[1103]	valid_0's binary_logloss: 1.26131
[1104]	valid_0's binary_logloss: 1.26131
[1105]	valid_0's binary_logloss: 1.26145
[1106]	valid_0's binary_logloss: 1.26152
[1107]	valid_0's binary_logloss: 1.26154
[1108]	valid_0's binary_logloss: 1.26156
[1109]	valid_0's binary_logloss: 1.26157
[1110]	valid_0's binary_logloss: 1.26164
[1111]	valid_0's binary_logloss: 1.26168
[1112]	valid_0's binary_logloss: 1.26177
[1113]	valid_0's binary_logloss: 1.26184
[1114]	valid_0's binary_logloss: 1.26187
[1115]	valid_0's binary_logloss: 1.26188
[1116]	valid_0's binary_logloss: 1.26191
[1117]	valid_0's binary_logloss: 1.26191
[1118]	valid_0's binary_logloss: 1.26191
[1119]	valid_0's binary_logloss: 1.2619
[1120]	valid_0's binary_logloss: 1.26196
[1121]	valid_0's 

[1341]	valid_0's binary_logloss: 1.27542
[1342]	valid_0's binary_logloss: 1.27549
[1343]	valid_0's binary_logloss: 1.27556
[1344]	valid_0's binary_logloss: 1.27566
[1345]	valid_0's binary_logloss: 1.27567
[1346]	valid_0's binary_logloss: 1.27564
[1347]	valid_0's binary_logloss: 1.27557
[1348]	valid_0's binary_logloss: 1.27568
[1349]	valid_0's binary_logloss: 1.27568
[1350]	valid_0's binary_logloss: 1.27579
[1351]	valid_0's binary_logloss: 1.27585
[1352]	valid_0's binary_logloss: 1.2759
[1353]	valid_0's binary_logloss: 1.27598
[1354]	valid_0's binary_logloss: 1.27607
[1355]	valid_0's binary_logloss: 1.27614
[1356]	valid_0's binary_logloss: 1.27617
[1357]	valid_0's binary_logloss: 1.27615
[1358]	valid_0's binary_logloss: 1.27617
[1359]	valid_0's binary_logloss: 1.27617
[1360]	valid_0's binary_logloss: 1.27613
[1361]	valid_0's binary_logloss: 1.27621
[1362]	valid_0's binary_logloss: 1.27622
[1363]	valid_0's binary_logloss: 1.27624
[1364]	valid_0's binary_logloss: 1.27633
[1365]	valid_0's 

[132]	valid_0's binary_logloss: 0.775516
[133]	valid_0's binary_logloss: 0.775119
[134]	valid_0's binary_logloss: 0.777088
[135]	valid_0's binary_logloss: 0.777886
[136]	valid_0's binary_logloss: 0.77872
[137]	valid_0's binary_logloss: 0.783393
[138]	valid_0's binary_logloss: 0.78849
[139]	valid_0's binary_logloss: 0.788639
[140]	valid_0's binary_logloss: 0.794684
[141]	valid_0's binary_logloss: 0.795763
[142]	valid_0's binary_logloss: 0.797115
[143]	valid_0's binary_logloss: 0.799894
[144]	valid_0's binary_logloss: 0.799264
[145]	valid_0's binary_logloss: 0.80519
[146]	valid_0's binary_logloss: 0.805212
[147]	valid_0's binary_logloss: 0.807107
[148]	valid_0's binary_logloss: 0.808505
[149]	valid_0's binary_logloss: 0.811229
[150]	valid_0's binary_logloss: 0.813034
[151]	valid_0's binary_logloss: 0.816186
[152]	valid_0's binary_logloss: 0.81758
[153]	valid_0's binary_logloss: 0.820903
[154]	valid_0's binary_logloss: 0.825135
[155]	valid_0's binary_logloss: 0.828117
[156]	valid_0's bina

[507]	valid_0's binary_logloss: 1.26618
[508]	valid_0's binary_logloss: 1.26631
[509]	valid_0's binary_logloss: 1.26734
[510]	valid_0's binary_logloss: 1.26727
[511]	valid_0's binary_logloss: 1.26742
[512]	valid_0's binary_logloss: 1.26764
[513]	valid_0's binary_logloss: 1.26871
[514]	valid_0's binary_logloss: 1.26864
[515]	valid_0's binary_logloss: 1.27069
[516]	valid_0's binary_logloss: 1.27046
[517]	valid_0's binary_logloss: 1.27065
[518]	valid_0's binary_logloss: 1.2708
[519]	valid_0's binary_logloss: 1.27084
[520]	valid_0's binary_logloss: 1.27088
[521]	valid_0's binary_logloss: 1.27102
[522]	valid_0's binary_logloss: 1.27088
[523]	valid_0's binary_logloss: 1.27094
[524]	valid_0's binary_logloss: 1.27106
[525]	valid_0's binary_logloss: 1.2732
[526]	valid_0's binary_logloss: 1.27317
[527]	valid_0's binary_logloss: 1.27316
[528]	valid_0's binary_logloss: 1.27318
[529]	valid_0's binary_logloss: 1.27328
[530]	valid_0's binary_logloss: 1.27319
[531]	valid_0's binary_logloss: 1.27324
[5

[918]	valid_0's binary_logloss: 1.32377
[919]	valid_0's binary_logloss: 1.32382
[920]	valid_0's binary_logloss: 1.32391
[921]	valid_0's binary_logloss: 1.32394
[922]	valid_0's binary_logloss: 1.32402
[923]	valid_0's binary_logloss: 1.32408
[924]	valid_0's binary_logloss: 1.32409
[925]	valid_0's binary_logloss: 1.32416
[926]	valid_0's binary_logloss: 1.32422
[927]	valid_0's binary_logloss: 1.32426
[928]	valid_0's binary_logloss: 1.32431
[929]	valid_0's binary_logloss: 1.32442
[930]	valid_0's binary_logloss: 1.3245
[931]	valid_0's binary_logloss: 1.32508
[932]	valid_0's binary_logloss: 1.32508
[933]	valid_0's binary_logloss: 1.32511
[934]	valid_0's binary_logloss: 1.32516
[935]	valid_0's binary_logloss: 1.32525
[936]	valid_0's binary_logloss: 1.32524
[937]	valid_0's binary_logloss: 1.32531
[938]	valid_0's binary_logloss: 1.32539
[939]	valid_0's binary_logloss: 1.32547
[940]	valid_0's binary_logloss: 1.32553
[941]	valid_0's binary_logloss: 1.32558
[942]	valid_0's binary_logloss: 1.32564
[

[1349]	valid_0's binary_logloss: 1.35224
[1350]	valid_0's binary_logloss: 1.35222
[1351]	valid_0's binary_logloss: 1.35225
[1352]	valid_0's binary_logloss: 1.35485
[1353]	valid_0's binary_logloss: 1.35483
[1354]	valid_0's binary_logloss: 1.35486
[1355]	valid_0's binary_logloss: 1.35489
[1356]	valid_0's binary_logloss: 1.35492
[1357]	valid_0's binary_logloss: 1.35492
[1358]	valid_0's binary_logloss: 1.35495
[1359]	valid_0's binary_logloss: 1.35496
[1360]	valid_0's binary_logloss: 1.35504
[1361]	valid_0's binary_logloss: 1.35517
[1362]	valid_0's binary_logloss: 1.3552
[1363]	valid_0's binary_logloss: 1.35525
[1364]	valid_0's binary_logloss: 1.35527
[1365]	valid_0's binary_logloss: 1.35529
[1366]	valid_0's binary_logloss: 1.35532
[1367]	valid_0's binary_logloss: 1.35532
[1368]	valid_0's binary_logloss: 1.35536
[1369]	valid_0's binary_logloss: 1.35539
[1370]	valid_0's binary_logloss: 1.35539
[1371]	valid_0's binary_logloss: 1.35544
[1372]	valid_0's binary_logloss: 1.35554
[1373]	valid_0's 

[149]	valid_0's binary_logloss: 0.739878
[150]	valid_0's binary_logloss: 0.743889
[151]	valid_0's binary_logloss: 0.747389
[152]	valid_0's binary_logloss: 0.750499
[153]	valid_0's binary_logloss: 0.753617
[154]	valid_0's binary_logloss: 0.753601
[155]	valid_0's binary_logloss: 0.754454
[156]	valid_0's binary_logloss: 0.75506
[157]	valid_0's binary_logloss: 0.761924
[158]	valid_0's binary_logloss: 0.765904
[159]	valid_0's binary_logloss: 0.768179
[160]	valid_0's binary_logloss: 0.766607
[161]	valid_0's binary_logloss: 0.771372
[162]	valid_0's binary_logloss: 0.772772
[163]	valid_0's binary_logloss: 0.77626
[164]	valid_0's binary_logloss: 0.776466
[165]	valid_0's binary_logloss: 0.780774
[166]	valid_0's binary_logloss: 0.784257
[167]	valid_0's binary_logloss: 0.788915
[168]	valid_0's binary_logloss: 0.792279
[169]	valid_0's binary_logloss: 0.793324
[170]	valid_0's binary_logloss: 0.793869
[171]	valid_0's binary_logloss: 0.79512
[172]	valid_0's binary_logloss: 0.797639
[173]	valid_0's bin

[490]	valid_0's binary_logloss: 1.15157
[491]	valid_0's binary_logloss: 1.15295
[492]	valid_0's binary_logloss: 1.15619
[493]	valid_0's binary_logloss: 1.15672
[494]	valid_0's binary_logloss: 1.15685
[495]	valid_0's binary_logloss: 1.15994
[496]	valid_0's binary_logloss: 1.16022
[497]	valid_0's binary_logloss: 1.16087
[498]	valid_0's binary_logloss: 1.16244
[499]	valid_0's binary_logloss: 1.16236
[500]	valid_0's binary_logloss: 1.16405
[501]	valid_0's binary_logloss: 1.16532
[502]	valid_0's binary_logloss: 1.1653
[503]	valid_0's binary_logloss: 1.16522
[504]	valid_0's binary_logloss: 1.16642
[505]	valid_0's binary_logloss: 1.16645
[506]	valid_0's binary_logloss: 1.16649
[507]	valid_0's binary_logloss: 1.16722
[508]	valid_0's binary_logloss: 1.16727
[509]	valid_0's binary_logloss: 1.16723
[510]	valid_0's binary_logloss: 1.16793
[511]	valid_0's binary_logloss: 1.16787
[512]	valid_0's binary_logloss: 1.16727
[513]	valid_0's binary_logloss: 1.16749
[514]	valid_0's binary_logloss: 1.16754
[

[827]	valid_0's binary_logloss: 1.21935
[828]	valid_0's binary_logloss: 1.21945
[829]	valid_0's binary_logloss: 1.21952
[830]	valid_0's binary_logloss: 1.21959
[831]	valid_0's binary_logloss: 1.2197
[832]	valid_0's binary_logloss: 1.21968
[833]	valid_0's binary_logloss: 1.2197
[834]	valid_0's binary_logloss: 1.21975
[835]	valid_0's binary_logloss: 1.21982
[836]	valid_0's binary_logloss: 1.21984
[837]	valid_0's binary_logloss: 1.21996
[838]	valid_0's binary_logloss: 1.22005
[839]	valid_0's binary_logloss: 1.22016
[840]	valid_0's binary_logloss: 1.22012
[841]	valid_0's binary_logloss: 1.22013
[842]	valid_0's binary_logloss: 1.22013
[843]	valid_0's binary_logloss: 1.22017
[844]	valid_0's binary_logloss: 1.22021
[845]	valid_0's binary_logloss: 1.22032
[846]	valid_0's binary_logloss: 1.22038
[847]	valid_0's binary_logloss: 1.2204
[848]	valid_0's binary_logloss: 1.22045
[849]	valid_0's binary_logloss: 1.22048
[850]	valid_0's binary_logloss: 1.22052
[851]	valid_0's binary_logloss: 1.22048
[85

[1172]	valid_0's binary_logloss: 1.24527
[1173]	valid_0's binary_logloss: 1.24533
[1174]	valid_0's binary_logloss: 1.24539
[1175]	valid_0's binary_logloss: 1.24535
[1176]	valid_0's binary_logloss: 1.24533
[1177]	valid_0's binary_logloss: 1.24537
[1178]	valid_0's binary_logloss: 1.24542
[1179]	valid_0's binary_logloss: 1.24543
[1180]	valid_0's binary_logloss: 1.24545
[1181]	valid_0's binary_logloss: 1.24547
[1182]	valid_0's binary_logloss: 1.24552
[1183]	valid_0's binary_logloss: 1.24559
[1184]	valid_0's binary_logloss: 1.24564
[1185]	valid_0's binary_logloss: 1.24568
[1186]	valid_0's binary_logloss: 1.24573
[1187]	valid_0's binary_logloss: 1.24575
[1188]	valid_0's binary_logloss: 1.24579
[1189]	valid_0's binary_logloss: 1.24576
[1190]	valid_0's binary_logloss: 1.24581
[1191]	valid_0's binary_logloss: 1.24583
[1192]	valid_0's binary_logloss: 1.24477
[1193]	valid_0's binary_logloss: 1.24482
[1194]	valid_0's binary_logloss: 1.24486
[1195]	valid_0's binary_logloss: 1.24493
[1196]	valid_0's

[1515]	valid_0's binary_logloss: 1.26301
[1516]	valid_0's binary_logloss: 1.26304
[1517]	valid_0's binary_logloss: 1.26308
[1518]	valid_0's binary_logloss: 1.26316
[1519]	valid_0's binary_logloss: 1.26316
| 41        | 0.7586    | 0.1298    | 9.948     | 1.52e+03  |
[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.680004
[2]	valid_0's binary_logloss: 0.666842
[3]	valid_0's binary_logloss: 0.653597
[4]	valid_0's binary_logloss: 0.643678
[5]	valid_0's binary_logloss: 0.633927
[6]	valid_0's binary_logloss: 0.623487
[7]	valid_0's binary_logloss: 0.613205
[8]	valid_0's binary_logloss: 0.605338
[9]	valid_0's binary_logloss: 0.597124
[10]	valid_0's binary_logloss: 0.589045
[11]	valid_0's binary_logloss: 0.581614
[12]	valid_0's binary_logloss: 0.573066
[13]	valid_0's binary_logloss: 0.56595
[14]	valid_0's binary_logloss: 0.558576
[15]	valid_0's binary_logloss: 0.552453
[16]	valid_0's binary_logloss: 0.546789
[17]	valid_0's binary_logloss: 0.542978
[18]	valid_

[299]	valid_0's binary_logloss: 0.5958
[300]	valid_0's binary_logloss: 0.596769
[301]	valid_0's binary_logloss: 0.596932
[302]	valid_0's binary_logloss: 0.597175
[303]	valid_0's binary_logloss: 0.597841
[304]	valid_0's binary_logloss: 0.59826
[305]	valid_0's binary_logloss: 0.598772
[306]	valid_0's binary_logloss: 0.598307
[307]	valid_0's binary_logloss: 0.599245
[308]	valid_0's binary_logloss: 0.600207
[309]	valid_0's binary_logloss: 0.600631
[310]	valid_0's binary_logloss: 0.601363
[311]	valid_0's binary_logloss: 0.601898
[312]	valid_0's binary_logloss: 0.602931
[313]	valid_0's binary_logloss: 0.603424
[314]	valid_0's binary_logloss: 0.604528
[315]	valid_0's binary_logloss: 0.60482
[316]	valid_0's binary_logloss: 0.605005
[317]	valid_0's binary_logloss: 0.606352
[318]	valid_0's binary_logloss: 0.60676
[319]	valid_0's binary_logloss: 0.60792
[320]	valid_0's binary_logloss: 0.608557
[321]	valid_0's binary_logloss: 0.61079
[322]	valid_0's binary_logloss: 0.612539
[323]	valid_0's binary_

[550]	valid_0's binary_logloss: 0.780193
[551]	valid_0's binary_logloss: 0.779721
[552]	valid_0's binary_logloss: 0.780271
[553]	valid_0's binary_logloss: 0.780809
[554]	valid_0's binary_logloss: 0.782952
[555]	valid_0's binary_logloss: 0.78303
[556]	valid_0's binary_logloss: 0.78342
[557]	valid_0's binary_logloss: 0.783917
[558]	valid_0's binary_logloss: 0.784444
[559]	valid_0's binary_logloss: 0.78653
[560]	valid_0's binary_logloss: 0.78767
[561]	valid_0's binary_logloss: 0.78787
[562]	valid_0's binary_logloss: 0.789657
[563]	valid_0's binary_logloss: 0.790207
[564]	valid_0's binary_logloss: 0.790544
[565]	valid_0's binary_logloss: 0.791568
[566]	valid_0's binary_logloss: 0.792812
[567]	valid_0's binary_logloss: 0.794185
[568]	valid_0's binary_logloss: 0.794835
[569]	valid_0's binary_logloss: 0.79473
[570]	valid_0's binary_logloss: 0.79411
[571]	valid_0's binary_logloss: 0.795637
[572]	valid_0's binary_logloss: 0.795707
[573]	valid_0's binary_logloss: 0.796126
[574]	valid_0's binary_

[894]	valid_0's binary_logloss: 0.935297
[895]	valid_0's binary_logloss: 0.935717
[896]	valid_0's binary_logloss: 0.936214
[897]	valid_0's binary_logloss: 0.936433
[898]	valid_0's binary_logloss: 0.937013
[899]	valid_0's binary_logloss: 0.937094
[900]	valid_0's binary_logloss: 0.937572
[901]	valid_0's binary_logloss: 0.937875
[902]	valid_0's binary_logloss: 0.93799
[903]	valid_0's binary_logloss: 0.937845
[904]	valid_0's binary_logloss: 0.937725
[905]	valid_0's binary_logloss: 0.937465
[906]	valid_0's binary_logloss: 0.937636
[907]	valid_0's binary_logloss: 0.938394
[908]	valid_0's binary_logloss: 0.938543
[909]	valid_0's binary_logloss: 0.938819
[910]	valid_0's binary_logloss: 0.939085
[911]	valid_0's binary_logloss: 0.939698
[912]	valid_0's binary_logloss: 0.93973
[913]	valid_0's binary_logloss: 0.940067
[914]	valid_0's binary_logloss: 0.940749
[915]	valid_0's binary_logloss: 0.941443
[916]	valid_0's binary_logloss: 0.941703
[917]	valid_0's binary_logloss: 0.942215
[918]	valid_0's bi

[1231]	valid_0's binary_logloss: 1.04535
[1232]	valid_0's binary_logloss: 1.04556
[1233]	valid_0's binary_logloss: 1.04652
[1234]	valid_0's binary_logloss: 1.04709
[1235]	valid_0's binary_logloss: 1.04771
[1236]	valid_0's binary_logloss: 1.04811
[1237]	valid_0's binary_logloss: 1.04829
[1238]	valid_0's binary_logloss: 1.04851
[1239]	valid_0's binary_logloss: 1.04909
[1240]	valid_0's binary_logloss: 1.04928
[1241]	valid_0's binary_logloss: 1.0491
[1242]	valid_0's binary_logloss: 1.0498
[1243]	valid_0's binary_logloss: 1.04978
[1244]	valid_0's binary_logloss: 1.04946
[1245]	valid_0's binary_logloss: 1.04929
[1246]	valid_0's binary_logloss: 1.0501
[1247]	valid_0's binary_logloss: 1.05003
[1248]	valid_0's binary_logloss: 1.05002
[1249]	valid_0's binary_logloss: 1.05087
[1250]	valid_0's binary_logloss: 1.05116
[1251]	valid_0's binary_logloss: 1.0509
[1252]	valid_0's binary_logloss: 1.05164
[1253]	valid_0's binary_logloss: 1.05189
[1254]	valid_0's binary_logloss: 1.05185
[1255]	valid_0's bin

| 42        | 0.7363    | 0.04363   | 8.315     | 1.509e+03 |
[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.644435
[2]	valid_0's binary_logloss: 0.603415
[3]	valid_0's binary_logloss: 0.571921
[4]	valid_0's binary_logloss: 0.546734
[5]	valid_0's binary_logloss: 0.535025
[6]	valid_0's binary_logloss: 0.528966
[7]	valid_0's binary_logloss: 0.523462
[8]	valid_0's binary_logloss: 0.513529
[9]	valid_0's binary_logloss: 0.509122
[10]	valid_0's binary_logloss: 0.507915
[11]	valid_0's binary_logloss: 0.504177
[12]	valid_0's binary_logloss: 0.499701
[13]	valid_0's binary_logloss: 0.497737
[14]	valid_0's binary_logloss: 0.493057
[15]	valid_0's binary_logloss: 0.496306
[16]	valid_0's binary_logloss: 0.49715
[17]	valid_0's binary_logloss: 0.494826
[18]	valid_0's binary_logloss: 0.49655
[19]	valid_0's binary_logloss: 0.49874
[20]	valid_0's binary_logloss: 0.496567
[21]	valid_0's binary_logloss: 0.501032
[22]	valid_0's binary_logloss: 0.503057
[23]	valid_0's bin

[332]	valid_0's binary_logloss: 1.14541
[333]	valid_0's binary_logloss: 1.14728
[334]	valid_0's binary_logloss: 1.14865
[335]	valid_0's binary_logloss: 1.15062
[336]	valid_0's binary_logloss: 1.15318
[337]	valid_0's binary_logloss: 1.15287
[338]	valid_0's binary_logloss: 1.15471
[339]	valid_0's binary_logloss: 1.15316
[340]	valid_0's binary_logloss: 1.1548
[341]	valid_0's binary_logloss: 1.15482
[342]	valid_0's binary_logloss: 1.1589
[343]	valid_0's binary_logloss: 1.1616
[344]	valid_0's binary_logloss: 1.16194
[345]	valid_0's binary_logloss: 1.16294
[346]	valid_0's binary_logloss: 1.16385
[347]	valid_0's binary_logloss: 1.16436
[348]	valid_0's binary_logloss: 1.16443
[349]	valid_0's binary_logloss: 1.1664
[350]	valid_0's binary_logloss: 1.16783
[351]	valid_0's binary_logloss: 1.16891
[352]	valid_0's binary_logloss: 1.16809
[353]	valid_0's binary_logloss: 1.1702
[354]	valid_0's binary_logloss: 1.17164
[355]	valid_0's binary_logloss: 1.17254
[356]	valid_0's binary_logloss: 1.1734
[357]	

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.689509
[2]	valid_0's binary_logloss: 0.686033
[3]	valid_0's binary_logloss: 0.682273
[4]	valid_0's binary_logloss: 0.678985
[5]	valid_0's binary_logloss: 0.675362
[6]	valid_0's binary_logloss: 0.671927
[7]	valid_0's binary_logloss: 0.668377
[8]	valid_0's binary_logloss: 0.665494
[9]	valid_0's binary_logloss: 0.662159
[10]	valid_0's binary_logloss: 0.659194
[11]	valid_0's binary_logloss: 0.656057
[12]	valid_0's binary_logloss: 0.653348
[13]	valid_0's binary_logloss: 0.650577
[14]	valid_0's binary_logloss: 0.647481
[15]	valid_0's binary_logloss: 0.644269
[16]	valid_0's binary_logloss: 0.641153
[17]	valid_0's binary_logloss: 0.638374
[18]	valid_0's binary_logloss: 0.635293
[19]	valid_0's binary_logloss: 0.632273
[20]	valid_0's binary_logloss: 0.629584
[21]	valid_0's binary_logloss: 0.626912
[22]	valid_0's binary_logloss: 0.623954
[23]	valid_0's binary_logloss: 0.621189
[24]	valid_0's binary_logloss: 0.6186

[139]	valid_0's binary_logloss: 0.82006
[140]	valid_0's binary_logloss: 0.821999
[141]	valid_0's binary_logloss: 0.824489
[142]	valid_0's binary_logloss: 0.833494
[143]	valid_0's binary_logloss: 0.835203
[144]	valid_0's binary_logloss: 0.834765
[145]	valid_0's binary_logloss: 0.836103
[146]	valid_0's binary_logloss: 0.838045
[147]	valid_0's binary_logloss: 0.836747
[148]	valid_0's binary_logloss: 0.841286
[149]	valid_0's binary_logloss: 0.842876
[150]	valid_0's binary_logloss: 0.844324
[151]	valid_0's binary_logloss: 0.846788
[152]	valid_0's binary_logloss: 0.849795
[153]	valid_0's binary_logloss: 0.852192
[154]	valid_0's binary_logloss: 0.854776
[155]	valid_0's binary_logloss: 0.858664
[156]	valid_0's binary_logloss: 0.860654
[157]	valid_0's binary_logloss: 0.86326
[158]	valid_0's binary_logloss: 0.865604
[159]	valid_0's binary_logloss: 0.86979
[160]	valid_0's binary_logloss: 0.873035
[161]	valid_0's binary_logloss: 0.873523
[162]	valid_0's binary_logloss: 0.875245
[163]	valid_0's bin

[177]	valid_0's binary_logloss: 0.932379
[178]	valid_0's binary_logloss: 0.933764
[179]	valid_0's binary_logloss: 0.936836
[180]	valid_0's binary_logloss: 0.942114
[181]	valid_0's binary_logloss: 0.942398
[182]	valid_0's binary_logloss: 0.943928
[183]	valid_0's binary_logloss: 0.943267
[184]	valid_0's binary_logloss: 0.941708
[185]	valid_0's binary_logloss: 0.941992
[186]	valid_0's binary_logloss: 0.946458
[187]	valid_0's binary_logloss: 0.948108
[188]	valid_0's binary_logloss: 0.948013
[189]	valid_0's binary_logloss: 0.947178
[190]	valid_0's binary_logloss: 0.946434
[191]	valid_0's binary_logloss: 0.948113
[192]	valid_0's binary_logloss: 0.948466
[193]	valid_0's binary_logloss: 0.953061
[194]	valid_0's binary_logloss: 0.952748
[195]	valid_0's binary_logloss: 0.952828
[196]	valid_0's binary_logloss: 0.954332
[197]	valid_0's binary_logloss: 0.955469
[198]	valid_0's binary_logloss: 0.95723
[199]	valid_0's binary_logloss: 0.96151
[200]	valid_0's binary_logloss: 0.961395
[201]	valid_0's bi

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.626149
[2]	valid_0's binary_logloss: 0.584185
[3]	valid_0's binary_logloss: 0.537842
[4]	valid_0's binary_logloss: 0.51913
[5]	valid_0's binary_logloss: 0.511084
[6]	valid_0's binary_logloss: 0.511124
[7]	valid_0's binary_logloss: 0.509352
[8]	valid_0's binary_logloss: 0.496584
[9]	valid_0's binary_logloss: 0.481347
[10]	valid_0's binary_logloss: 0.468831
[11]	valid_0's binary_logloss: 0.480467
[12]	valid_0's binary_logloss: 0.471946
[13]	valid_0's binary_logloss: 0.474522
[14]	valid_0's binary_logloss: 0.477901
[15]	valid_0's binary_logloss: 0.472369
[16]	valid_0's binary_logloss: 0.486338
[17]	valid_0's binary_logloss: 0.490567
[18]	valid_0's binary_logloss: 0.494417
[19]	valid_0's binary_logloss: 0.494641
[20]	valid_0's binary_logloss: 0.500145
[21]	valid_0's binary_logloss: 0.50962
[22]	valid_0's binary_logloss: 0.514994
[23]	valid_0's binary_logloss: 0.524313
[24]	valid_0's binary_logloss: 0.527354

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.624411
[2]	valid_0's binary_logloss: 0.578928
[3]	valid_0's binary_logloss: 0.545147
[4]	valid_0's binary_logloss: 0.522741
[5]	valid_0's binary_logloss: 0.501299
[6]	valid_0's binary_logloss: 0.497563
[7]	valid_0's binary_logloss: 0.495347
[8]	valid_0's binary_logloss: 0.481917
[9]	valid_0's binary_logloss: 0.474601
[10]	valid_0's binary_logloss: 0.473613
[11]	valid_0's binary_logloss: 0.478536
[12]	valid_0's binary_logloss: 0.480629
[13]	valid_0's binary_logloss: 0.486962
[14]	valid_0's binary_logloss: 0.489333
[15]	valid_0's binary_logloss: 0.493515
[16]	valid_0's binary_logloss: 0.483697
[17]	valid_0's binary_logloss: 0.486784
[18]	valid_0's binary_logloss: 0.48311
[19]	valid_0's binary_logloss: 0.492307
[20]	valid_0's binary_logloss: 0.492834
[21]	valid_0's binary_logloss: 0.492079
[22]	valid_0's binary_logloss: 0.495864
[23]	valid_0's binary_logloss: 0.509109
[24]	valid_0's binary_logloss: 0.51537

[161]	valid_0's binary_logloss: 0.911029
[162]	valid_0's binary_logloss: 0.911888
[163]	valid_0's binary_logloss: 0.912885
[164]	valid_0's binary_logloss: 0.914317
[165]	valid_0's binary_logloss: 0.917204
[166]	valid_0's binary_logloss: 0.920025
[167]	valid_0's binary_logloss: 0.922104
[168]	valid_0's binary_logloss: 0.923762
[169]	valid_0's binary_logloss: 0.928816
[170]	valid_0's binary_logloss: 0.93136
[171]	valid_0's binary_logloss: 0.941303
[172]	valid_0's binary_logloss: 0.942669
[173]	valid_0's binary_logloss: 0.943718
[174]	valid_0's binary_logloss: 0.943649
[175]	valid_0's binary_logloss: 0.94424
[176]	valid_0's binary_logloss: 0.943915
[177]	valid_0's binary_logloss: 0.949159
[178]	valid_0's binary_logloss: 0.950972
[179]	valid_0's binary_logloss: 0.952523
[180]	valid_0's binary_logloss: 0.955649
[181]	valid_0's binary_logloss: 0.957696
[182]	valid_0's binary_logloss: 0.96283
[183]	valid_0's binary_logloss: 0.965295
[184]	valid_0's binary_logloss: 0.970434
[185]	valid_0's bin

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.654492
[2]	valid_0's binary_logloss: 0.619713
[3]	valid_0's binary_logloss: 0.590818
[4]	valid_0's binary_logloss: 0.568718
[5]	valid_0's binary_logloss: 0.554242
[6]	valid_0's binary_logloss: 0.538434
[7]	valid_0's binary_logloss: 0.52705
[8]	valid_0's binary_logloss: 0.517332
[9]	valid_0's binary_logloss: 0.51203
[10]	valid_0's binary_logloss: 0.505454
[11]	valid_0's binary_logloss: 0.503494
[12]	valid_0's binary_logloss: 0.501582
[13]	valid_0's binary_logloss: 0.490661
[14]	valid_0's binary_logloss: 0.492031
[15]	valid_0's binary_logloss: 0.489297
[16]	valid_0's binary_logloss: 0.484296
[17]	valid_0's binary_logloss: 0.487843
[18]	valid_0's binary_logloss: 0.487394
[19]	valid_0's binary_logloss: 0.483749
[20]	valid_0's binary_logloss: 0.479424
[21]	valid_0's binary_logloss: 0.483844
[22]	valid_0's binary_logloss: 0.484471
[23]	valid_0's binary_logloss: 0.483964
[24]	valid_0's binary_logloss: 0.487591

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.62422
[2]	valid_0's binary_logloss: 0.589336
[3]	valid_0's binary_logloss: 0.56415
[4]	valid_0's binary_logloss: 0.553814
[5]	valid_0's binary_logloss: 0.536628
[6]	valid_0's binary_logloss: 0.529324
[7]	valid_0's binary_logloss: 0.505175
[8]	valid_0's binary_logloss: 0.494948
[9]	valid_0's binary_logloss: 0.495035
[10]	valid_0's binary_logloss: 0.485397
[11]	valid_0's binary_logloss: 0.481955
[12]	valid_0's binary_logloss: 0.48215
[13]	valid_0's binary_logloss: 0.482579
[14]	valid_0's binary_logloss: 0.487717
[15]	valid_0's binary_logloss: 0.487041
[16]	valid_0's binary_logloss: 0.488004
[17]	valid_0's binary_logloss: 0.486562
[18]	valid_0's binary_logloss: 0.486836
[19]	valid_0's binary_logloss: 0.48237
[20]	valid_0's binary_logloss: 0.482613
[21]	valid_0's binary_logloss: 0.478676
[22]	valid_0's binary_logloss: 0.475895
[23]	valid_0's binary_logloss: 0.476736
[24]	valid_0's binary_logloss: 0.479419
[

[227]	valid_0's binary_logloss: 0.93081
[228]	valid_0's binary_logloss: 0.932313
[229]	valid_0's binary_logloss: 0.93547
[230]	valid_0's binary_logloss: 0.937509
[231]	valid_0's binary_logloss: 0.939015
[232]	valid_0's binary_logloss: 0.940051
[233]	valid_0's binary_logloss: 0.94205
[234]	valid_0's binary_logloss: 0.945168
[235]	valid_0's binary_logloss: 0.950649
[236]	valid_0's binary_logloss: 0.954551
[237]	valid_0's binary_logloss: 0.9557
[238]	valid_0's binary_logloss: 0.953929
[239]	valid_0's binary_logloss: 0.958857
[240]	valid_0's binary_logloss: 0.961668
[241]	valid_0's binary_logloss: 0.961774
[242]	valid_0's binary_logloss: 0.963038
[243]	valid_0's binary_logloss: 0.964311
[244]	valid_0's binary_logloss: 0.964782
[245]	valid_0's binary_logloss: 0.966942
[246]	valid_0's binary_logloss: 0.967268
[247]	valid_0's binary_logloss: 0.966713
[248]	valid_0's binary_logloss: 0.969167
[249]	valid_0's binary_logloss: 0.975025
[250]	valid_0's binary_logloss: 0.971959
[251]	valid_0's binar

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.692954
[2]	valid_0's binary_logloss: 0.692663
[3]	valid_0's binary_logloss: 0.69237
[4]	valid_0's binary_logloss: 0.69208
[5]	valid_0's binary_logloss: 0.691788
[6]	valid_0's binary_logloss: 0.6915
[7]	valid_0's binary_logloss: 0.691208
[8]	valid_0's binary_logloss: 0.690922
[9]	valid_0's binary_logloss: 0.690632
[10]	valid_0's binary_logloss: 0.690347
[11]	valid_0's binary_logloss: 0.690059
[12]	valid_0's binary_logloss: 0.689775
[13]	valid_0's binary_logloss: 0.689488
[14]	valid_0's binary_logloss: 0.689205
[15]	valid_0's binary_logloss: 0.68892
[16]	valid_0's binary_logloss: 0.68861
[17]	valid_0's binary_logloss: 0.688326
[18]	valid_0's binary_logloss: 0.688017
[19]	valid_0's binary_logloss: 0.687734
[20]	valid_0's binary_logloss: 0.687426
[21]	valid_0's binary_logloss: 0.687145
[22]	valid_0's binary_logloss: 0.686839
[23]	valid_0's binary_logloss: 0.68653
[24]	valid_0's binary_logloss: 0.686254
[25]

[326]	valid_0's binary_logloss: 0.568562
[327]	valid_0's binary_logloss: 0.567909
[328]	valid_0's binary_logloss: 0.56884
[329]	valid_0's binary_logloss: 0.56814
[330]	valid_0's binary_logloss: 0.569287
[331]	valid_0's binary_logloss: 0.570067
[332]	valid_0's binary_logloss: 0.570063
[333]	valid_0's binary_logloss: 0.569891
[334]	valid_0's binary_logloss: 0.57052
[335]	valid_0's binary_logloss: 0.570705
[336]	valid_0's binary_logloss: 0.571006
[337]	valid_0's binary_logloss: 0.569915
[338]	valid_0's binary_logloss: 0.570111
[339]	valid_0's binary_logloss: 0.570892
[340]	valid_0's binary_logloss: 0.570479
[341]	valid_0's binary_logloss: 0.571675
[342]	valid_0's binary_logloss: 0.571522
[343]	valid_0's binary_logloss: 0.572107
[344]	valid_0's binary_logloss: 0.572432
[345]	valid_0's binary_logloss: 0.573354
[346]	valid_0's binary_logloss: 0.574262
[347]	valid_0's binary_logloss: 0.575312
[348]	valid_0's binary_logloss: 0.574864
[349]	valid_0's binary_logloss: 0.574738
[350]	valid_0's bin

[708]	valid_0's binary_logloss: 0.739525
[709]	valid_0's binary_logloss: 0.739092
[710]	valid_0's binary_logloss: 0.738918
[711]	valid_0's binary_logloss: 0.739266
[712]	valid_0's binary_logloss: 0.740389
[713]	valid_0's binary_logloss: 0.741041
[714]	valid_0's binary_logloss: 0.74292
[715]	valid_0's binary_logloss: 0.744149
[716]	valid_0's binary_logloss: 0.744267
[717]	valid_0's binary_logloss: 0.746006
[718]	valid_0's binary_logloss: 0.746093
[719]	valid_0's binary_logloss: 0.746435
[720]	valid_0's binary_logloss: 0.745614
[721]	valid_0's binary_logloss: 0.746569
[722]	valid_0's binary_logloss: 0.747239
[723]	valid_0's binary_logloss: 0.74619
[724]	valid_0's binary_logloss: 0.746307
[725]	valid_0's binary_logloss: 0.746418
[726]	valid_0's binary_logloss: 0.748077
[727]	valid_0's binary_logloss: 0.749315
[728]	valid_0's binary_logloss: 0.749035
[729]	valid_0's binary_logloss: 0.751005
[730]	valid_0's binary_logloss: 0.751161
[731]	valid_0's binary_logloss: 0.752263
[732]	valid_0's bi

[1260]	valid_0's binary_logloss: 0.95962
[1261]	valid_0's binary_logloss: 0.960157
[1262]	valid_0's binary_logloss: 0.960068
[1263]	valid_0's binary_logloss: 0.960098
[1264]	valid_0's binary_logloss: 0.960227
[1265]	valid_0's binary_logloss: 0.960983
[1266]	valid_0's binary_logloss: 0.961361
[1267]	valid_0's binary_logloss: 0.962771
[1268]	valid_0's binary_logloss: 0.962208
[1269]	valid_0's binary_logloss: 0.962364
[1270]	valid_0's binary_logloss: 0.962938
[1271]	valid_0's binary_logloss: 0.962843
[1272]	valid_0's binary_logloss: 0.962616
[1273]	valid_0's binary_logloss: 0.962437
[1274]	valid_0's binary_logloss: 0.962498
[1275]	valid_0's binary_logloss: 0.962695
[1276]	valid_0's binary_logloss: 0.962721
[1277]	valid_0's binary_logloss: 0.962963
[1278]	valid_0's binary_logloss: 0.962876
[1279]	valid_0's binary_logloss: 0.962873
[1280]	valid_0's binary_logloss: 0.962943
[1281]	valid_0's binary_logloss: 0.962949
[1282]	valid_0's binary_logloss: 0.962947
[1283]	valid_0's binary_logloss: 0.

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.69169
[2]	valid_0's binary_logloss: 0.690165
[3]	valid_0's binary_logloss: 0.688685
[4]	valid_0's binary_logloss: 0.687248
[5]	valid_0's binary_logloss: 0.685852
[6]	valid_0's binary_logloss: 0.684497
[7]	valid_0's binary_logloss: 0.683248
[8]	valid_0's binary_logloss: 0.681957
[9]	valid_0's binary_logloss: 0.680776
[10]	valid_0's binary_logloss: 0.67941
[11]	valid_0's binary_logloss: 0.678294
[12]	valid_0's binary_logloss: 0.676752
[13]	valid_0's binary_logloss: 0.675249
[14]	valid_0's binary_logloss: 0.6742
[15]	valid_0's binary_logloss: 0.67275
[16]	valid_0's binary_logloss: 0.671338
[17]	valid_0's binary_logloss: 0.669961
[18]	valid_0's binary_logloss: 0.668994
[19]	valid_0's binary_logloss: 0.667665
[20]	valid_0's binary_logloss: 0.666369
[21]	valid_0's binary_logloss: 0.665133
[22]	valid_0's binary_logloss: 0.664234
[23]	valid_0's binary_logloss: 0.663013
[24]	valid_0's binary_logloss: 0.661848
[2

[394]	valid_0's binary_logloss: 0.529437
[395]	valid_0's binary_logloss: 0.52929
[396]	valid_0's binary_logloss: 0.529018
[397]	valid_0's binary_logloss: 0.529171
[398]	valid_0's binary_logloss: 0.529125
[399]	valid_0's binary_logloss: 0.528821
[400]	valid_0's binary_logloss: 0.528613
[401]	valid_0's binary_logloss: 0.528493
[402]	valid_0's binary_logloss: 0.528264
[403]	valid_0's binary_logloss: 0.528127
[404]	valid_0's binary_logloss: 0.527864
[405]	valid_0's binary_logloss: 0.527368
[406]	valid_0's binary_logloss: 0.527523
[407]	valid_0's binary_logloss: 0.527463
[408]	valid_0's binary_logloss: 0.5274
[409]	valid_0's binary_logloss: 0.527285
[410]	valid_0's binary_logloss: 0.527102
[411]	valid_0's binary_logloss: 0.526879
[412]	valid_0's binary_logloss: 0.526623
[413]	valid_0's binary_logloss: 0.52678
[414]	valid_0's binary_logloss: 0.526704
[415]	valid_0's binary_logloss: 0.526503
[416]	valid_0's binary_logloss: 0.526393
[417]	valid_0's binary_logloss: 0.526266
[418]	valid_0's bina

In [34]:
best_hyperparameters = bayesian_opt.max
best_hyperparameters['params'] = {param: int(value) if param in [
    'depth', 'iterations', 'n_estimators'] else value for param, value in best_hyperparameters['params'].items()}
print("Best hyperparameters:", best_hyperparameters['params'])
print(f"Best R-squared Score: {best_hyperparameters['target']:.4f}")

Best hyperparameters: {'learning_rate': 0.1213437386005643, 'max_depth': 7.990207206075692, 'n_estimators': 170}
Best R-squared Score: 0.7783


In [35]:
params = {
    'max_depth': 7,            
    'learning_rate': 0.1213437386005643,  
    'n_estimators': 170
}

model_LGBM = LGBMClassifier(**params, random_state=27)
model_LGBM.fit(x_train_LGBM, y_train_LGBM)
# предсказание ответов для тренеровочной выборки
y_pred_LGBM_train = model_LGBM.predict(x_train_LGBM)
# предсказание ответов для тестовой выборки
y_pred_LGBM = model_LGBM.predict(x_valid_LGBM)

print("Train LGBM f1_score: ", f1_score(y_train_LGBM, y_pred_LGBM_train))
print("Train LGBM accuracy_score: ", accuracy_score(y_train_LGBM, y_pred_LGBM_train))
print("Validation LGBM f1_score: ", f1_score(y_valid_LGBM, y_pred_LGBM))
print("Validation LGBM accuracy_score: ", accuracy_score(y_valid_LGBM, y_pred_LGBM))

Train LGBM f1_score:  0.9703703703703703
Train LGBM accuracy_score:  0.9699248120300752
Validation LGBM f1_score:  0.7783251231527093
Validation LGBM accuracy_score:  0.775


После подбора гиперпараметров мы незначительно улучшили метрики LGBMClassifier на вадидации f1_score: 0.778, accuracy_score: 0.775.



**xgboost**

In [36]:
def XGB_cv(max_depth, learning_rate, n_estimators):
    max_depth = int(max_depth)
    n_estimators = int(n_estimators)
    model = xg.XGBClassifier(
        max_depth=max_depth,
        learning_rate=learning_rate,
        n_estimators=n_estimators,
        random_seed=27
    )
    model.fit(x_train_xgb, y_train_xgb)
    return f1_score(y_valid_xgb, model.predict(x_valid_xgb))

In [37]:
param_space = {
    'max_depth': (2, 10),            
    'learning_rate': (0.001, 0.3),  
    'n_estimators': (10, 2000)
}

bayesian_opt = BayesianOptimization(
    allow_duplicate_points=True,f=XGB_cv, pbounds=param_space, random_state=27)
bayesian_opt.maximize(init_points=5, n_iter=50)
results = pd.DataFrame(bayesian_opt.res)
results.sort_values(by='target', ascending=False, inplace=True)

|   iter    |  target   | learni... | max_depth | n_esti... |
-------------------------------------------------------------


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:12] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 1         | 0.7624    | 0.1283    | 8.517     | 1.473e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:14] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 2         | 0.7685    | 0.2605    | 5.067     | 1.959e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:17] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 3         | 0.7638    | 0.2681    | 3.678     | 1.486e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:18] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 4         | 0.7576    | 0.1993    | 9.094     | 1.717e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:21] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 5         | 0.7411    | 0.225     | 8.961     | 381.6     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:22] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 6         | 0.7437    | 0.009447  | 5.454     | 1.96e+03  |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:25] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 7         | 0.75      | 0.003044  | 6.786     | 591.6     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:27] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 8         | 0.7538    | 0.0709    | 3.473     | 1.487e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:29] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 9         | 0.7538    | 0.1031    | 2.767     | 312.7     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:29] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 10        | 0.7562    | 0.2714    | 8.774     | 284.1     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:30] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 11        | 0.7512    | 0.002048  | 3.922     | 1.8e+03   |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:32] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 12        | 0.75      | 0.02006   | 9.471     | 11.37     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:32] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 13        | 0.7437    | 0.01293   | 9.046     | 617.4     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:35] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 14        | 0.7685    | 0.07053   | 5.957     | 1.825e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:38] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 15        | 0.7662    | 0.1242    | 3.996     | 1.365e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:39] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 16        | 0.7437    | 0.1635    | 8.502     | 1.007e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:41] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 17        | 0.75      | 0.1904    | 6.239     | 852.1     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:43] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 18        | 0.76      | 0.1359    | 8.292     | 908.7     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:44] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 19        | 0.7337    | 0.01653   | 3.068     | 516.9     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:45] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 20        | 0.76      | 0.2141    | 3.651     | 1.366e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:46] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 21        | 0.7576    | 0.1399    | 3.931     | 1.366e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:47] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 22        | 0.77      | 0.2962    | 4.049     | 1.365e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:49] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 23        | 0.7624    | 0.2917    | 4.228     | 1.959e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:51] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 24        | 0.7538    | 0.1763    | 6.576     | 1.825e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:53] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 25        | 0.7463    | 0.2389    | 2.998     | 1.012e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:54] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 26        | 0.7562    | 0.1588    | 3.658     | 1.365e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:55] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 27        | 0.7374    | 0.02421   | 3.87      | 1.266e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:56] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 28        | 0.7513    | 0.05271   | 3.623     | 1.486e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:58] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 29        | 0.75      | 0.1274    | 4.576     | 805.3     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:37:59] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 30        | 0.7411    | 0.003393  | 5.987     | 1.825e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:02] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 31        | 0.7562    | 0.2411    | 3.293     | 117.6     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:03] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 32        | 0.7761    | 0.2276    | 8.396     | 1.473e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:05] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 33        | 0.731     | 0.01288   | 5.615     | 503.0     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:06] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 34        | 0.7638    | 0.09231   | 6.351     | 786.8     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:08] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 35        | 0.7761    | 0.2806    | 4.653     | 1.263e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:09] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 36        | 0.74      | 0.1475    | 9.847     | 1.057e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:11] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 37        | 0.7624    | 0.2468    | 7.127     | 418.9     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:12] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 38        | 0.7488    | 0.1003    | 2.204     | 1.34e+03  |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:13] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 39        | 0.7624    | 0.09681   | 4.705     | 1.263e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:15] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 40        | 0.7374    | 0.03027   | 3.898     | 1.371e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:16] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 41        | 0.78      | 0.2416    | 8.442     | 1.015e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:18] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 42        | 0.7437    | 0.07949   | 5.7       | 1.825e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:20] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 43        | 0.75      | 0.1902    | 5.56      | 304.1     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:21] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 44        | 0.7562    | 0.2444    | 6.036     | 946.8     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:22] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 45        | 0.7475    | 0.06955   | 8.365     | 1.015e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:25] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 46        | 0.7475    | 0.1027    | 6.655     | 1.453e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:27] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 47        | 0.7562    | 0.2648    | 5.978     | 1.41e+03  |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:28] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 48        | 0.7638    | 0.1691    | 6.238     | 946.8     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:30] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 49        | 0.7662    | 0.1413    | 6.235     | 947.1     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:32] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 50        | 0.7538    | 0.1823    | 7.446     | 1.82e+03  |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:34] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 51        | 0.7624    | 0.1325    | 3.194     | 1.781e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:36] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 52        | 0.7624    | 0.2187    | 4.994     | 1.959e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:38] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 53        | 0.731     | 0.0836    | 6.92      | 136.5     |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:39] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 54        | 0.7562    | 0.2578    | 4.306     | 1.959e+03 |


/home/rik/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:38:41] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "random_seed" } are not used.

  warnings.warn(smsg, UserWarning)


| 55        | 0.7488    | 0.01312   | 2.343     | 697.7     |


In [38]:
best_hyperparameters = bayesian_opt.max
best_hyperparameters['params'] = {param: int(value) if param in [
    'depth', 'iterations', 'n_estimators'] else value for param, value in best_hyperparameters['params'].items()}
print("Best hyperparameters:", best_hyperparameters['params'])
print(f"Best R-squared Score: {best_hyperparameters['target']:.4f}")

Best hyperparameters: {'learning_rate': 0.24156191458213627, 'max_depth': 8.44220920786574, 'n_estimators': 1014}
Best R-squared Score: 0.7800


In [39]:
params = {
    'max_depth': 8,            
    'learning_rate':0.24156191458213627
    ,  
    'n_estimators': 1014  
}
model_XGB = xg.XGBClassifier(**params, random_state=27)
model_XGB.fit(x_train_xgb, y_train_xgb)
y_pred_xgb = model_XGB.predict(x_train_xgb)
y_val_xgb = model_XGB.predict(x_valid_xgb)
print("Train f1_score: ", f1_score(y_train_xgb, y_pred_xgb))
print("Train accuracy_score: ", accuracy_score(y_train_xgb, y_pred_xgb))
print("Validation f1_score: ", f1_score(y_valid_xgb, y_val_xgb))
print("Validation accuracy_score: ", accuracy_score(y_valid_xgb, y_val_xgb))

Train f1_score:  0.9703703703703703
Train accuracy_score:  0.9699248120300752
Validation f1_score:  0.7799999999999999
Validation accuracy_score:  0.78


После подбора гиперпараметров мы улучшили метрики для модели XGBClassifier на вадидации f1_score: 0.78, accuracy_score: 0.78.

**Выводы**

Мы сравнили 4 регрессионые модели: DecisionTreeRegressor, CatBoostRegressor, LGBMRegressor, XGBRegressor. Наилучший результат показала модель CatBoostClassifier с результатом на трейне: f1_score= 0.97 и accuracy_score= 0.97 и тесте: f1_score=0.7864, accuracy_score=0.78.

**Рекомендации**

Для улучшения значения метрики и снижения переобучения нужно будет увеличить количество данных.